In [5]:
import seaborn as sns
import pandas as pd

flights= sns.load_dataset("flights")
flights

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [12]:
import pandas as pd

pd.set_option("display.max_rows", None)
flights

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
5    1949   Jun         135
6    1949   Jul         148
7    1949   Aug         148
8    1949   Sep         136
9    1949   Oct         119
10   1949   Nov         104
11   1949   Dec         118
12   1950   Jan         115
13   1950   Feb         126
14   1950   Mar         141
15   1950   Apr         135
16   1950   May         125
17   1950   Jun         149
18   1950   Jul         170
19   1950   Aug         170
20   1950   Sep         158
21   1950   Oct         133
22   1950   Nov         114
23   1950   Dec         140
24   1951   Jan         145
25   1951   Feb         150
26   1951   Mar         178
27   1951   Apr         163
28   1951   May         172
29   1951   Jun         178
30   1951   Jul         199
31   1951   Aug         199
32   1951   Sep         184
33   1951   Oct         162
34   1951   Nov         146
35   1951   Dec         166
36   1952   Jan         171
37   1952   Feb         180
38   1952   Mar         193
39   1952   Apr         181
40   1952   May         183
41   1952   Jun         218
42   1952   Jul         230
43   1952   Aug         242
44   1952   Sep         209
45   1952   Oct         191
46   1952   Nov         172
47   1952   Dec         194
48   1953   Jan         196
49   1953   Feb         196
50   1953   Mar         236
51   1953   Apr         235
52   1953   May         229
53   1953   Jun         243
54   1953   Jul         264
55   1953   Aug         272
56   1953   Sep         237
57   1953   Oct         211
58   1953   Nov         180
59   1953   Dec         201
60   1954   Jan         204
61   1954   Feb         188
62   1954   Mar         235
63   1954   Apr         227
64   1954   May         234
65   1954   Jun         264
66   1954   Jul         302
67   1954   Aug         293
68   1954   Sep         259
69   1954   Oct         229
70   1954   Nov         203
71   1954   Dec         229
72   1955   Jan         242
73   1955   Feb         233
74   1955   Mar         267
75   1955   Apr         269
76   1955   May         270
77   1955   Jun         315
78   1955   Jul         364
79   1955   Aug         347
80   1955   Sep         312
81   1955   Oct         274
82   1955   Nov         237
83   1955   Dec         278
84   1956   Jan         284
85   1956   Feb         277
86   1956   Mar         317
87   1956   Apr         313
88   1956   May         318
89   1956   Jun         374
90   1956   Jul         413
91   1956   Aug         405
92   1956   Sep         355
93   1956   Oct         306
94   1956   Nov         271
95   1956   Dec         306
96   1957   Jan         315
97   1957   Feb         301
98   1957   Mar         356
99   1957   Apr         348
100  1957   May         355
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
104  1957   Sep         404
105  1957   Oct         347
106  1957   Nov         305
107  1957   Dec         336
108  1958   Jan         340
109  1958   Feb         318
110  1958   Mar         362
111  1958   Apr         348
112  1958   May         363
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
116  1958   Sep         404
117  1958   Oct         359
118  1958   Nov         310
119  1958   Dec         337
120  1959   Jan         360
121  1959   Feb         342
122  1959   Mar         406
123  1959   Apr         396
124  1959   May         420
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
129  1959   Oct         407
130  1959   Nov         362
131  1959   Dec         405
132  1960   Jan         417
133  1960   Feb         391
134  1960   Mar         419
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

In [16]:
# Display first 5 rows
flights.head()
flights.tail()
flights.shape
flights.columns

Index(['year', 'month', 'passengers'], dtype='object')

In [20]:
flights.dtypes

year             int64
month         category
passengers       int64
dtype: object

In [21]:
# Use describe()
flights.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

In [23]:
# Count total rows
flights.count(axis=0)

year          144
month         144
passengers    144
dtype: int64

In [24]:
len(flights)

144

In [25]:
# Select passengers column
flights["passengers"]

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
30     199
31     199
32     184
33     162
34     146
35     166
36     171
37     180
38     193
39     181
40     183
41     218
42     230
43     242
44     209
45     191
46     172
47     194
48     196
49     196
50     236
51     235
52     229
53     243
54     264
55     272
56     237
57     211
58     180
59     201
60     204
61     188
62     235
63     227
64     234
65     264
66     302
67     293
68     259
69     229
70     203
71     229
72     242
73     233
74     267
75     269
76     270
77     315
78     364
79     347
80     312
81     274
82     237
83     278
84     284
85     277
86     317
87     313
88     318
89     374
90     413
91     405
92     355
93     306
94     271
95     306
96     315
97     301
98     356
99     348
100    355
101    422
102    465
103    467
104    404
105    347
106    305
107    336
108    340
109    318
110    362
111    348
112    363
113    435
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: passengers, dtype: int64

In [28]:
# Select year & month
flights[["year","month"]]

     year month
0    1949   Jan
1    1949   Feb
2    1949   Mar
3    1949   Apr
4    1949   May
5    1949   Jun
6    1949   Jul
7    1949   Aug
8    1949   Sep
9    1949   Oct
10   1949   Nov
11   1949   Dec
12   1950   Jan
13   1950   Feb
14   1950   Mar
15   1950   Apr
16   1950   May
17   1950   Jun
18   1950   Jul
19   1950   Aug
20   1950   Sep
21   1950   Oct
22   1950   Nov
23   1950   Dec
24   1951   Jan
25   1951   Feb
26   1951   Mar
27   1951   Apr
28   1951   May
29   1951   Jun
30   1951   Jul
31   1951   Aug
32   1951   Sep
33   1951   Oct
34   1951   Nov
35   1951   Dec
36   1952   Jan
37   1952   Feb
38   1952   Mar
39   1952   Apr
40   1952   May
41   1952   Jun
42   1952   Jul
43   1952   Aug
44   1952   Sep
45   1952   Oct
46   1952   Nov
47   1952   Dec
48   1953   Jan
49   1953   Feb
50   1953   Mar
51   1953   Apr
52   1953   May
53   1953   Jun
54   1953   Jul
55   1953   Aug
56   1953   Sep
57   1953   Oct
58   1953   Nov
59   1953   Dec
60   1954   Jan
61   1954   Feb
62   1954   Mar
63   1954   Apr
64   1954   May
65   1954   Jun
66   1954   Jul
67   1954   Aug
68   1954   Sep
69   1954   Oct
70   1954   Nov
71   1954   Dec
72   1955   Jan
73   1955   Feb
74   1955   Mar
75   1955   Apr
76   1955   May
77   1955   Jun
78   1955   Jul
79   1955   Aug
80   1955   Sep
81   1955   Oct
82   1955   Nov
83   1955   Dec
84   1956   Jan
85   1956   Feb
86   1956   Mar
87   1956   Apr
88   1956   May
89   1956   Jun
90   1956   Jul
91   1956   Aug
92   1956   Sep
93   1956   Oct
94   1956   Nov
95   1956   Dec
96   1957   Jan
97   1957   Feb
98   1957   Mar
99   1957   Apr
100  1957   May
101  1957   Jun
102  1957   Jul
103  1957   Aug
104  1957   Sep
105  1957   Oct
106  1957   Nov
107  1957   Dec
108  1958   Jan
109  1958   Feb
110  1958   Mar
111  1958   Apr
112  1958   May
113  1958   Jun
114  1958   Jul
115  1958   Aug
116  1958   Sep
117  1958   Oct
118  1958   Nov
119  1958   Dec
120  1959   Jan
121  1959   Feb
122  1959   Mar
123  1959   Apr
124  1959   May
125  1959   Jun
126  1959   Jul
127  1959   Aug
128  1959   Sep
129  1959   Oct
130  1959   Nov
131  1959   Dec
132  1960   Jan
133  1960   Feb
134  1960   Mar
135  1960   Apr
136  1960   May
137  1960   Jun
138  1960   Jul
139  1960   Aug
140  1960   Sep
141  1960   Oct
142  1960   Nov
143  1960   Dec

In [31]:
# Access 10th row using iloc
flights.iloc[9]

year          1949
month          Oct
passengers     119
Name: 9, dtype: object

In [37]:
# Access row with index 5 using loc
flights.loc[5]

year          1949
month          Jun
passengers     135
Name: 5, dtype: object

In [36]:
# Find unique years
flights["year"].unique()

array([1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
       1960])

In [39]:
# Find unique months
flights["month"].unique()

['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
Length: 12
Categories (12, object): ['Jan', 'Feb', 'Mar', 'Apr', ..., 'Sep', 'Oct', 'Nov', 'Dec']

In [43]:
# Count number of months
flights["month"].unique()

['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
Length: 12
Categories (12, object): ['Jan', 'Feb', 'Mar', 'Apr', ..., 'Sep', 'Oct', 'Nov', 'Dec']

In [44]:
flights.isna().sum()

year          0
month         0
passengers    0
dtype: int64

In [47]:
# Rename column passengers → count
flights.rename(columns={"passengers":"count"},inplace=True)
flights

     year month  count
0    1949   Jan    112
1    1949   Feb    118
2    1949   Mar    132
3    1949   Apr    129
4    1949   May    121
5    1949   Jun    135
6    1949   Jul    148
7    1949   Aug    148
8    1949   Sep    136
9    1949   Oct    119
10   1949   Nov    104
11   1949   Dec    118
12   1950   Jan    115
13   1950   Feb    126
14   1950   Mar    141
15   1950   Apr    135
16   1950   May    125
17   1950   Jun    149
18   1950   Jul    170
19   1950   Aug    170
20   1950   Sep    158
21   1950   Oct    133
22   1950   Nov    114
23   1950   Dec    140
24   1951   Jan    145
25   1951   Feb    150
26   1951   Mar    178
27   1951   Apr    163
28   1951   May    172
29   1951   Jun    178
30   1951   Jul    199
31   1951   Aug    199
32   1951   Sep    184
33   1951   Oct    162
34   1951   Nov    146
35   1951   Dec    166
36   1952   Jan    171
37   1952   Feb    180
38   1952   Mar    193
39   1952   Apr    181
40   1952   May    183
41   1952   Jun    218
42   1952   Jul    230
43   1952   Aug    242
44   1952   Sep    209
45   1952   Oct    191
46   1952   Nov    172
47   1952   Dec    194
48   1953   Jan    196
49   1953   Feb    196
50   1953   Mar    236
51   1953   Apr    235
52   1953   May    229
53   1953   Jun    243
54   1953   Jul    264
55   1953   Aug    272
56   1953   Sep    237
57   1953   Oct    211
58   1953   Nov    180
59   1953   Dec    201
60   1954   Jan    204
61   1954   Feb    188
62   1954   Mar    235
63   1954   Apr    227
64   1954   May    234
65   1954   Jun    264
66   1954   Jul    302
67   1954   Aug    293
68   1954   Sep    259
69   1954   Oct    229
70   1954   Nov    203
71   1954   Dec    229
72   1955   Jan    242
73   1955   Feb    233
74   1955   Mar    267
75   1955   Apr    269
76   1955   May    270
77   1955   Jun    315
78   1955   Jul    364
79   1955   Aug    347
80   1955   Sep    312
81   1955   Oct    274
82   1955   Nov    237
83   1955   Dec    278
84   1956   Jan    284
85   1956   Feb    277
86   1956   Mar    317
87   1956   Apr    313
88   1956   May    318
89   1956   Jun    374
90   1956   Jul    413
91   1956   Aug    405
92   1956   Sep    355
93   1956   Oct    306
94   1956   Nov    271
95   1956   Dec    306
96   1957   Jan    315
97   1957   Feb    301
98   1957   Mar    356
99   1957   Apr    348
100  1957   May    355
101  1957   Jun    422
102  1957   Jul    465
103  1957   Aug    467
104  1957   Sep    404
105  1957   Oct    347
106  1957   Nov    305
107  1957   Dec    336
108  1958   Jan    340
109  1958   Feb    318
110  1958   Mar    362
111  1958   Apr    348
112  1958   May    363
113  1958   Jun    435
114  1958   Jul    491
115  1958   Aug    505
116  1958   Sep    404
117  1958   Oct    359
118  1958   Nov    310
119  1958   Dec    337
120  1959   Jan    360
121  1959   Feb    342
122  1959   Mar    406
123  1959   Apr    396
124  1959   May    420
125  1959   Jun    472
126  1959   Jul    548
127  1959   Aug    559
128  1959   Sep    463
129  1959   Oct    407
130  1959   Nov    362
131  1959   Dec    405
132  1960   Jan    417
133  1960   Feb    391
134  1960   Mar    419
135  1960   Apr    461
136  1960   May    472
137  1960   Jun    535
138  1960   Jul    622
139  1960   Aug    606
140  1960   Sep    508
141  1960   Oct    461
142  1960   Nov    390
143  1960   Dec    432

In [48]:
# Sort by passengers
flights.sort_values("count")

     year month  count
10   1949   Nov    104
0    1949   Jan    112
22   1950   Nov    114
12   1950   Jan    115
11   1949   Dec    118
1    1949   Feb    118
9    1949   Oct    119
4    1949   May    121
16   1950   May    125
13   1950   Feb    126
3    1949   Apr    129
2    1949   Mar    132
21   1950   Oct    133
5    1949   Jun    135
15   1950   Apr    135
8    1949   Sep    136
23   1950   Dec    140
14   1950   Mar    141
24   1951   Jan    145
34   1951   Nov    146
6    1949   Jul    148
7    1949   Aug    148
17   1950   Jun    149
25   1951   Feb    150
20   1950   Sep    158
33   1951   Oct    162
27   1951   Apr    163
35   1951   Dec    166
18   1950   Jul    170
19   1950   Aug    170
36   1952   Jan    171
28   1951   May    172
46   1952   Nov    172
26   1951   Mar    178
29   1951   Jun    178
37   1952   Feb    180
58   1953   Nov    180
39   1952   Apr    181
40   1952   May    183
32   1951   Sep    184
61   1954   Feb    188
45   1952   Oct    191
38   1952   Mar    193
47   1952   Dec    194
49   1953   Feb    196
48   1953   Jan    196
31   1951   Aug    199
30   1951   Jul    199
59   1953   Dec    201
70   1954   Nov    203
60   1954   Jan    204
44   1952   Sep    209
57   1953   Oct    211
41   1952   Jun    218
63   1954   Apr    227
52   1953   May    229
69   1954   Oct    229
71   1954   Dec    229
42   1952   Jul    230
73   1955   Feb    233
64   1954   May    234
62   1954   Mar    235
51   1953   Apr    235
50   1953   Mar    236
56   1953   Sep    237
82   1955   Nov    237
72   1955   Jan    242
43   1952   Aug    242
53   1953   Jun    243
68   1954   Sep    259
65   1954   Jun    264
54   1953   Jul    264
74   1955   Mar    267
75   1955   Apr    269
76   1955   May    270
94   1956   Nov    271
55   1953   Aug    272
81   1955   Oct    274
85   1956   Feb    277
83   1955   Dec    278
84   1956   Jan    284
67   1954   Aug    293
97   1957   Feb    301
66   1954   Jul    302
106  1957   Nov    305
93   1956   Oct    306
95   1956   Dec    306
118  1958   Nov    310
80   1955   Sep    312
87   1956   Apr    313
96   1957   Jan    315
77   1955   Jun    315
86   1956   Mar    317
88   1956   May    318
109  1958   Feb    318
107  1957   Dec    336
119  1958   Dec    337
108  1958   Jan    340
121  1959   Feb    342
105  1957   Oct    347
79   1955   Aug    347
111  1958   Apr    348
99   1957   Apr    348
92   1956   Sep    355
100  1957   May    355
98   1957   Mar    356
117  1958   Oct    359
120  1959   Jan    360
110  1958   Mar    362
130  1959   Nov    362
112  1958   May    363
78   1955   Jul    364
89   1956   Jun    374
142  1960   Nov    390
133  1960   Feb    391
123  1959   Apr    396
116  1958   Sep    404
104  1957   Sep    404
131  1959   Dec    405
91   1956   Aug    405
122  1959   Mar    406
129  1959   Oct    407
90   1956   Jul    413
132  1960   Jan    417
134  1960   Mar    419
124  1959   May    420
101  1957   Jun    422
143  1960   Dec    432
113  1958   Jun    435
141  1960   Oct    461
135  1960   Apr    461
128  1959   Sep    463
102  1957   Jul    465
103  1957   Aug    467
125  1959   Jun    472
136  1960   May    472
114  1958   Jul    491
115  1958   Aug    505
140  1960   Sep    508
137  1960   Jun    535
126  1959   Jul    548
127  1959   Aug    559
139  1960   Aug    606
138  1960   Jul    622

In [50]:
# Sort descending by year
flights.sort_values("count",ascending=0)

     year month  count
138  1960   Jul    622
139  1960   Aug    606
127  1959   Aug    559
126  1959   Jul    548
137  1960   Jun    535
140  1960   Sep    508
115  1958   Aug    505
114  1958   Jul    491
136  1960   May    472
125  1959   Jun    472
103  1957   Aug    467
102  1957   Jul    465
128  1959   Sep    463
141  1960   Oct    461
135  1960   Apr    461
113  1958   Jun    435
143  1960   Dec    432
101  1957   Jun    422
124  1959   May    420
134  1960   Mar    419
132  1960   Jan    417
90   1956   Jul    413
129  1959   Oct    407
122  1959   Mar    406
131  1959   Dec    405
91   1956   Aug    405
104  1957   Sep    404
116  1958   Sep    404
123  1959   Apr    396
133  1960   Feb    391
142  1960   Nov    390
89   1956   Jun    374
78   1955   Jul    364
112  1958   May    363
110  1958   Mar    362
130  1959   Nov    362
120  1959   Jan    360
117  1958   Oct    359
98   1957   Mar    356
100  1957   May    355
92   1956   Sep    355
99   1957   Apr    348
111  1958   Apr    348
79   1955   Aug    347
105  1957   Oct    347
121  1959   Feb    342
108  1958   Jan    340
119  1958   Dec    337
107  1957   Dec    336
109  1958   Feb    318
88   1956   May    318
86   1956   Mar    317
77   1955   Jun    315
96   1957   Jan    315
87   1956   Apr    313
80   1955   Sep    312
118  1958   Nov    310
95   1956   Dec    306
93   1956   Oct    306
106  1957   Nov    305
66   1954   Jul    302
97   1957   Feb    301
67   1954   Aug    293
84   1956   Jan    284
83   1955   Dec    278
85   1956   Feb    277
81   1955   Oct    274
55   1953   Aug    272
94   1956   Nov    271
76   1955   May    270
75   1955   Apr    269
74   1955   Mar    267
54   1953   Jul    264
65   1954   Jun    264
68   1954   Sep    259
53   1953   Jun    243
43   1952   Aug    242
72   1955   Jan    242
56   1953   Sep    237
82   1955   Nov    237
50   1953   Mar    236
51   1953   Apr    235
62   1954   Mar    235
64   1954   May    234
73   1955   Feb    233
42   1952   Jul    230
52   1953   May    229
69   1954   Oct    229
71   1954   Dec    229
63   1954   Apr    227
41   1952   Jun    218
57   1953   Oct    211
44   1952   Sep    209
60   1954   Jan    204
70   1954   Nov    203
59   1953   Dec    201
31   1951   Aug    199
30   1951   Jul    199
49   1953   Feb    196
48   1953   Jan    196
47   1952   Dec    194
38   1952   Mar    193
45   1952   Oct    191
61   1954   Feb    188
32   1951   Sep    184
40   1952   May    183
39   1952   Apr    181
37   1952   Feb    180
58   1953   Nov    180
29   1951   Jun    178
26   1951   Mar    178
28   1951   May    172
46   1952   Nov    172
36   1952   Jan    171
19   1950   Aug    170
18   1950   Jul    170
35   1951   Dec    166
27   1951   Apr    163
33   1951   Oct    162
20   1950   Sep    158
25   1951   Feb    150
17   1950   Jun    149
7    1949   Aug    148
6    1949   Jul    148
34   1951   Nov    146
24   1951   Jan    145
14   1950   Mar    141
23   1950   Dec    140
8    1949   Sep    136
5    1949   Jun    135
15   1950   Apr    135
21   1950   Oct    133
2    1949   Mar    132
3    1949   Apr    129
13   1950   Feb    126
16   1950   May    125
4    1949   May    121
9    1949   Oct    119
1    1949   Feb    118
11   1949   Dec    118
12   1950   Jan    115
22   1950   Nov    114
0    1949   Jan    112
10   1949   Nov    104

In [54]:
# Reset index
flights.reset_index(drop=True, inplace=True)

In [52]:
flights

     year month  count
0    1949   Jan    112
1    1949   Feb    118
2    1949   Mar    132
3    1949   Apr    129
4    1949   May    121
5    1949   Jun    135
6    1949   Jul    148
7    1949   Aug    148
8    1949   Sep    136
9    1949   Oct    119
10   1949   Nov    104
11   1949   Dec    118
12   1950   Jan    115
13   1950   Feb    126
14   1950   Mar    141
15   1950   Apr    135
16   1950   May    125
17   1950   Jun    149
18   1950   Jul    170
19   1950   Aug    170
20   1950   Sep    158
21   1950   Oct    133
22   1950   Nov    114
23   1950   Dec    140
24   1951   Jan    145
25   1951   Feb    150
26   1951   Mar    178
27   1951   Apr    163
28   1951   May    172
29   1951   Jun    178
30   1951   Jul    199
31   1951   Aug    199
32   1951   Sep    184
33   1951   Oct    162
34   1951   Nov    146
35   1951   Dec    166
36   1952   Jan    171
37   1952   Feb    180
38   1952   Mar    193
39   1952   Apr    181
40   1952   May    183
41   1952   Jun    218
42   1952   Jul    230
43   1952   Aug    242
44   1952   Sep    209
45   1952   Oct    191
46   1952   Nov    172
47   1952   Dec    194
48   1953   Jan    196
49   1953   Feb    196
50   1953   Mar    236
51   1953   Apr    235
52   1953   May    229
53   1953   Jun    243
54   1953   Jul    264
55   1953   Aug    272
56   1953   Sep    237
57   1953   Oct    211
58   1953   Nov    180
59   1953   Dec    201
60   1954   Jan    204
61   1954   Feb    188
62   1954   Mar    235
63   1954   Apr    227
64   1954   May    234
65   1954   Jun    264
66   1954   Jul    302
67   1954   Aug    293
68   1954   Sep    259
69   1954   Oct    229
70   1954   Nov    203
71   1954   Dec    229
72   1955   Jan    242
73   1955   Feb    233
74   1955   Mar    267
75   1955   Apr    269
76   1955   May    270
77   1955   Jun    315
78   1955   Jul    364
79   1955   Aug    347
80   1955   Sep    312
81   1955   Oct    274
82   1955   Nov    237
83   1955   Dec    278
84   1956   Jan    284
85   1956   Feb    277
86   1956   Mar    317
87   1956   Apr    313
88   1956   May    318
89   1956   Jun    374
90   1956   Jul    413
91   1956   Aug    405
92   1956   Sep    355
93   1956   Oct    306
94   1956   Nov    271
95   1956   Dec    306
96   1957   Jan    315
97   1957   Feb    301
98   1957   Mar    356
99   1957   Apr    348
100  1957   May    355
101  1957   Jun    422
102  1957   Jul    465
103  1957   Aug    467
104  1957   Sep    404
105  1957   Oct    347
106  1957   Nov    305
107  1957   Dec    336
108  1958   Jan    340
109  1958   Feb    318
110  1958   Mar    362
111  1958   Apr    348
112  1958   May    363
113  1958   Jun    435
114  1958   Jul    491
115  1958   Aug    505
116  1958   Sep    404
117  1958   Oct    359
118  1958   Nov    310
119  1958   Dec    337
120  1959   Jan    360
121  1959   Feb    342
122  1959   Mar    406
123  1959   Apr    396
124  1959   May    420
125  1959   Jun    472
126  1959   Jul    548
127  1959   Aug    559
128  1959   Sep    463
129  1959   Oct    407
130  1959   Nov    362
131  1959   Dec    405
132  1960   Jan    417
133  1960   Feb    391
134  1960   Mar    419
135  1960   Apr    461
136  1960   May    472
137  1960   Jun    535
138  1960   Jul    622
139  1960   Aug    606
140  1960   Sep    508
141  1960   Oct    461
142  1960   Nov    390
143  1960   Dec    432

In [63]:
flights

     level_0  index month  count
0          0      0   Jan    112
1          1      1   Feb    118
2          2      2   Mar    132
3          3      3   Apr    129
4          4      4   May    121
5          5      5   Jun    135
6          6      6   Jul    148
7          7      7   Aug    148
8          8      8   Sep    136
9          9      9   Oct    119
10        10     10   Nov    104
11        11     11   Dec    118
12        12     12   Jan    115
13        13     13   Feb    126
14        14     14   Mar    141
15        15     15   Apr    135
16        16     16   May    125
17        17     17   Jun    149
18        18     18   Jul    170
19        19     19   Aug    170
20        20     20   Sep    158
21        21     21   Oct    133
22        22     22   Nov    114
23        23     23   Dec    140
24        24     24   Jan    145
25        25     25   Feb    150
26        26     26   Mar    178
27        27     27   Apr    163
28        28     28   May    172
29        29     29   Jun    178
30        30     30   Jul    199
31        31     31   Aug    199
32        32     32   Sep    184
33        33     33   Oct    162
34        34     34   Nov    146
35        35     35   Dec    166
36        36     36   Jan    171
37        37     37   Feb    180
38        38     38   Mar    193
39        39     39   Apr    181
40        40     40   May    183
41        41     41   Jun    218
42        42     42   Jul    230
43        43     43   Aug    242
44        44     44   Sep    209
45        45     45   Oct    191
46        46     46   Nov    172
47        47     47   Dec    194
48        48     48   Jan    196
49        49     49   Feb    196
50        50     50   Mar    236
51        51     51   Apr    235
52        52     52   May    229
53        53     53   Jun    243
54        54     54   Jul    264
55        55     55   Aug    272
56        56     56   Sep    237
57        57     57   Oct    211
58        58     58   Nov    180
59        59     59   Dec    201
60        60     60   Jan    204
61        61     61   Feb    188
62        62     62   Mar    235
63        63     63   Apr    227
64        64     64   May    234
65        65     65   Jun    264
66        66     66   Jul    302
67        67     67   Aug    293
68        68     68   Sep    259
69        69     69   Oct    229
70        70     70   Nov    203
71        71     71   Dec    229
72        72     72   Jan    242
73        73     73   Feb    233
74        74     74   Mar    267
75        75     75   Apr    269
76        76     76   May    270
77        77     77   Jun    315
78        78     78   Jul    364
79        79     79   Aug    347
80        80     80   Sep    312
81        81     81   Oct    274
82        82     82   Nov    237
83        83     83   Dec    278
84        84     84   Jan    284
85        85     85   Feb    277
86        86     86   Mar    317
87        87     87   Apr    313
88        88     88   May    318
89        89     89   Jun    374
90        90     90   Jul    413
91        91     91   Aug    405
92        92     92   Sep    355
93        93     93   Oct    306
94        94     94   Nov    271
95        95     95   Dec    306
96        96     96   Jan    315
97        97     97   Feb    301
98        98     98   Mar    356
99        99     99   Apr    348
100      100    100   May    355
101      101    101   Jun    422
102      102    102   Jul    465
103      103    103   Aug    467
104      104    104   Sep    404
105      105    105   Oct    347
106      106    106   Nov    305
107      107    107   Dec    336
108      108    108   Jan    340
109      109    109   Feb    318
110      110    110   Mar    362
111      111    111   Apr    348
112      112    112   May    363
113      113    113   Jun    435
114      114    114   Jul    491
115      115    115   Aug    505
116      116    116   Sep    404
117      117    117   Oct    359
118      118    118   Nov    310
119      119    119   Dec    337
120      120    120   Jan    360
121      121    121   Feb    342
122      122    122   Mar    406
123      123    123   Apr    396
124      124    124   May    420
125      125    125   Jun    472
126      126    126   Jul    548
127      127    127   Aug    559
128      128    128   Sep    463
129      129    129   Oct    407
130      130    130   Nov    362
131      131    131   Dec    405
132      132    132   Jan    417
133      133    133   Feb    391
134      134    134   Mar    419
135      135    135   Apr    461
136      136    136   May    472
137      137    137   Jun    535
138      138    138   Jul    622
139      139    139   Aug    606
140      140    140   Sep    508
141      141    141   Oct    461
142      142    142   Nov    390
143      143    143   Dec    432

In [72]:
flights.drop("level_0", inplace=True,axis=1)
flights

     index month  count
0        0   Jan    112
1        1   Feb    118
2        2   Mar    132
3        3   Apr    129
4        4   May    121
5        5   Jun    135
6        6   Jul    148
7        7   Aug    148
8        8   Sep    136
9        9   Oct    119
10      10   Nov    104
11      11   Dec    118
12      12   Jan    115
13      13   Feb    126
14      14   Mar    141
15      15   Apr    135
16      16   May    125
17      17   Jun    149
18      18   Jul    170
19      19   Aug    170
20      20   Sep    158
21      21   Oct    133
22      22   Nov    114
23      23   Dec    140
24      24   Jan    145
25      25   Feb    150
26      26   Mar    178
27      27   Apr    163
28      28   May    172
29      29   Jun    178
30      30   Jul    199
31      31   Aug    199
32      32   Sep    184
33      33   Oct    162
34      34   Nov    146
35      35   Dec    166
36      36   Jan    171
37      37   Feb    180
38      38   Mar    193
39      39   Apr    181
40      40   May    183
41      41   Jun    218
42      42   Jul    230
43      43   Aug    242
44      44   Sep    209
45      45   Oct    191
46      46   Nov    172
47      47   Dec    194
48      48   Jan    196
49      49   Feb    196
50      50   Mar    236
51      51   Apr    235
52      52   May    229
53      53   Jun    243
54      54   Jul    264
55      55   Aug    272
56      56   Sep    237
57      57   Oct    211
58      58   Nov    180
59      59   Dec    201
60      60   Jan    204
61      61   Feb    188
62      62   Mar    235
63      63   Apr    227
64      64   May    234
65      65   Jun    264
66      66   Jul    302
67      67   Aug    293
68      68   Sep    259
69      69   Oct    229
70      70   Nov    203
71      71   Dec    229
72      72   Jan    242
73      73   Feb    233
74      74   Mar    267
75      75   Apr    269
76      76   May    270
77      77   Jun    315
78      78   Jul    364
79      79   Aug    347
80      80   Sep    312
81      81   Oct    274
82      82   Nov    237
83      83   Dec    278
84      84   Jan    284
85      85   Feb    277
86      86   Mar    317
87      87   Apr    313
88      88   May    318
89      89   Jun    374
90      90   Jul    413
91      91   Aug    405
92      92   Sep    355
93      93   Oct    306
94      94   Nov    271
95      95   Dec    306
96      96   Jan    315
97      97   Feb    301
98      98   Mar    356
99      99   Apr    348
100    100   May    355
101    101   Jun    422
102    102   Jul    465
103    103   Aug    467
104    104   Sep    404
105    105   Oct    347
106    106   Nov    305
107    107   Dec    336
108    108   Jan    340
109    109   Feb    318
110    110   Mar    362
111    111   Apr    348
112    112   May    363
113    113   Jun    435
114    114   Jul    491
115    115   Aug    505
116    116   Sep    404
117    117   Oct    359
118    118   Nov    310
119    119   Dec    337
120    120   Jan    360
121    121   Feb    342
122    122   Mar    406
123    123   Apr    396
124    124   May    420
125    125   Jun    472
126    126   Jul    548
127    127   Aug    559
128    128   Sep    463
129    129   Oct    407
130    130   Nov    362
131    131   Dec    405
132    132   Jan    417
133    133   Feb    391
134    134   Mar    419
135    135   Apr    461
136    136   May    472
137    137   Jun    535
138    138   Jul    622
139    139   Aug    606
140    140   Sep    508
141    141   Oct    461
142    142   Nov    390
143    143   Dec    432

In [73]:
flights

     index month  count
0        0   Jan    112
1        1   Feb    118
2        2   Mar    132
3        3   Apr    129
4        4   May    121
5        5   Jun    135
6        6   Jul    148
7        7   Aug    148
8        8   Sep    136
9        9   Oct    119
10      10   Nov    104
11      11   Dec    118
12      12   Jan    115
13      13   Feb    126
14      14   Mar    141
15      15   Apr    135
16      16   May    125
17      17   Jun    149
18      18   Jul    170
19      19   Aug    170
20      20   Sep    158
21      21   Oct    133
22      22   Nov    114
23      23   Dec    140
24      24   Jan    145
25      25   Feb    150
26      26   Mar    178
27      27   Apr    163
28      28   May    172
29      29   Jun    178
30      30   Jul    199
31      31   Aug    199
32      32   Sep    184
33      33   Oct    162
34      34   Nov    146
35      35   Dec    166
36      36   Jan    171
37      37   Feb    180
38      38   Mar    193
39      39   Apr    181
40      40   May    183
41      41   Jun    218
42      42   Jul    230
43      43   Aug    242
44      44   Sep    209
45      45   Oct    191
46      46   Nov    172
47      47   Dec    194
48      48   Jan    196
49      49   Feb    196
50      50   Mar    236
51      51   Apr    235
52      52   May    229
53      53   Jun    243
54      54   Jul    264
55      55   Aug    272
56      56   Sep    237
57      57   Oct    211
58      58   Nov    180
59      59   Dec    201
60      60   Jan    204
61      61   Feb    188
62      62   Mar    235
63      63   Apr    227
64      64   May    234
65      65   Jun    264
66      66   Jul    302
67      67   Aug    293
68      68   Sep    259
69      69   Oct    229
70      70   Nov    203
71      71   Dec    229
72      72   Jan    242
73      73   Feb    233
74      74   Mar    267
75      75   Apr    269
76      76   May    270
77      77   Jun    315
78      78   Jul    364
79      79   Aug    347
80      80   Sep    312
81      81   Oct    274
82      82   Nov    237
83      83   Dec    278
84      84   Jan    284
85      85   Feb    277
86      86   Mar    317
87      87   Apr    313
88      88   May    318
89      89   Jun    374
90      90   Jul    413
91      91   Aug    405
92      92   Sep    355
93      93   Oct    306
94      94   Nov    271
95      95   Dec    306
96      96   Jan    315
97      97   Feb    301
98      98   Mar    356
99      99   Apr    348
100    100   May    355
101    101   Jun    422
102    102   Jul    465
103    103   Aug    467
104    104   Sep    404
105    105   Oct    347
106    106   Nov    305
107    107   Dec    336
108    108   Jan    340
109    109   Feb    318
110    110   Mar    362
111    111   Apr    348
112    112   May    363
113    113   Jun    435
114    114   Jul    491
115    115   Aug    505
116    116   Sep    404
117    117   Oct    359
118    118   Nov    310
119    119   Dec    337
120    120   Jan    360
121    121   Feb    342
122    122   Mar    406
123    123   Apr    396
124    124   May    420
125    125   Jun    472
126    126   Jul    548
127    127   Aug    559
128    128   Sep    463
129    129   Oct    407
130    130   Nov    362
131    131   Dec    405
132    132   Jan    417
133    133   Feb    391
134    134   Mar    419
135    135   Apr    461
136    136   May    472
137    137   Jun    535
138    138   Jul    622
139    139   Aug    606
140    140   Sep    508
141    141   Oct    461
142    142   Nov    390
143    143   Dec    432

In [74]:
flights["count"].min()

104

In [76]:
flights["count"].max()

622

In [77]:
import pandas as pd
import seaborn as sns
flights=sns.load_dataset("flights")
flights

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
5    1949   Jun         135
6    1949   Jul         148
7    1949   Aug         148
8    1949   Sep         136
9    1949   Oct         119
10   1949   Nov         104
11   1949   Dec         118
12   1950   Jan         115
13   1950   Feb         126
14   1950   Mar         141
15   1950   Apr         135
16   1950   May         125
17   1950   Jun         149
18   1950   Jul         170
19   1950   Aug         170
20   1950   Sep         158
21   1950   Oct         133
22   1950   Nov         114
23   1950   Dec         140
24   1951   Jan         145
25   1951   Feb         150
26   1951   Mar         178
27   1951   Apr         163
28   1951   May         172
29   1951   Jun         178
30   1951   Jul         199
31   1951   Aug         199
32   1951   Sep         184
33   1951   Oct         162
34   1951   Nov         146
35   1951   Dec         166
36   1952   Jan         171
37   1952   Feb         180
38   1952   Mar         193
39   1952   Apr         181
40   1952   May         183
41   1952   Jun         218
42   1952   Jul         230
43   1952   Aug         242
44   1952   Sep         209
45   1952   Oct         191
46   1952   Nov         172
47   1952   Dec         194
48   1953   Jan         196
49   1953   Feb         196
50   1953   Mar         236
51   1953   Apr         235
52   1953   May         229
53   1953   Jun         243
54   1953   Jul         264
55   1953   Aug         272
56   1953   Sep         237
57   1953   Oct         211
58   1953   Nov         180
59   1953   Dec         201
60   1954   Jan         204
61   1954   Feb         188
62   1954   Mar         235
63   1954   Apr         227
64   1954   May         234
65   1954   Jun         264
66   1954   Jul         302
67   1954   Aug         293
68   1954   Sep         259
69   1954   Oct         229
70   1954   Nov         203
71   1954   Dec         229
72   1955   Jan         242
73   1955   Feb         233
74   1955   Mar         267
75   1955   Apr         269
76   1955   May         270
77   1955   Jun         315
78   1955   Jul         364
79   1955   Aug         347
80   1955   Sep         312
81   1955   Oct         274
82   1955   Nov         237
83   1955   Dec         278
84   1956   Jan         284
85   1956   Feb         277
86   1956   Mar         317
87   1956   Apr         313
88   1956   May         318
89   1956   Jun         374
90   1956   Jul         413
91   1956   Aug         405
92   1956   Sep         355
93   1956   Oct         306
94   1956   Nov         271
95   1956   Dec         306
96   1957   Jan         315
97   1957   Feb         301
98   1957   Mar         356
99   1957   Apr         348
100  1957   May         355
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
104  1957   Sep         404
105  1957   Oct         347
106  1957   Nov         305
107  1957   Dec         336
108  1958   Jan         340
109  1958   Feb         318
110  1958   Mar         362
111  1958   Apr         348
112  1958   May         363
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
116  1958   Sep         404
117  1958   Oct         359
118  1958   Nov         310
119  1958   Dec         337
120  1959   Jan         360
121  1959   Feb         342
122  1959   Mar         406
123  1959   Apr         396
124  1959   May         420
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
129  1959   Oct         407
130  1959   Nov         362
131  1959   Dec         405
132  1960   Jan         417
133  1960   Feb         391
134  1960   Mar         419
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

In [78]:
# Find average passengers
flights["passengers"].mean()

np.float64(280.2986111111111)

In [79]:
# Count rows per year
flights["year"].count()

np.int64(144)

In [82]:
# Filter rows where passengers > 300
flights[flights["passengers"]>500]

     year month  passengers
115  1958   Aug         505
126  1959   Jul         548
127  1959   Aug         559
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508

In [83]:
# Filter data for year = 1955
flights[flights["year"]==1955]

    year month  passengers
72  1955   Jan         242
73  1955   Feb         233
74  1955   Mar         267
75  1955   Apr         269
76  1955   May         270
77  1955   Jun         315
78  1955   Jul         364
79  1955   Aug         347
80  1955   Sep         312
81  1955   Oct         274
82  1955   Nov         237
83  1955   Dec         278

In [89]:
# Filter months = "Jan"
flights[flights["month"]=="Jan"]

     year month  passengers
0    1949   Jan         112
12   1950   Jan         115
24   1951   Jan         145
36   1952   Jan         171
48   1953   Jan         196
60   1954   Jan         204
72   1955   Jan         242
84   1956   Jan         284
96   1957   Jan         315
108  1958   Jan         340
120  1959   Jan         360
132  1960   Jan         417

In [92]:
# Filter multiple conditions (year > 1955 & passengers > 400)
flights[(flights["year"]>1955)&(flights["passengers"]>400)]

     year month  passengers
90   1956   Jul         413
91   1956   Aug         405
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
104  1957   Sep         404
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
116  1958   Sep         404
122  1959   Mar         406
124  1959   May         420
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
129  1959   Oct         407
131  1959   Dec         405
132  1960   Jan         417
134  1960   Mar         419
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
143  1960   Dec         432

In [96]:
# Find average passengers per year
flights.groupby("year")["passengers"].mean()

year
1949    126.666667
1950    139.666667
1951    170.166667
1952    197.000000
1953    225.000000
1954    238.916667
1955    284.000000
1956    328.250000
1957    368.416667
1958    381.000000
1959    428.333333
1960    476.166667
Name: passengers, dtype: float64

In [98]:
# # Find average passengers per year
flights.groupby("year")["passengers"].max()

year
1949    148
1950    170
1951    199
1952    242
1953    272
1954    302
1955    364
1956    413
1957    467
1958    505
1959    559
1960    622
Name: passengers, dtype: int64

In [99]:
# Find min passengers per year
flights.groupby("year")["passengers"].min()

year
1949    104
1950    114
1951    145
1952    171
1953    180
1954    188
1955    233
1956    271
1957    301
1958    310
1959    342
1960    390
Name: passengers, dtype: int64

In [101]:
# Group by month and find average passengers
flights.groupby("month")["passengers"].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_17076\2478422218.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby("month")["passengers"].mean()

month
Jan    241.750000
Feb    235.000000
Mar    270.166667
Apr    267.083333
May    271.833333
Jun    311.666667
Jul    351.333333
Aug    351.083333
Sep    302.416667
Oct    266.583333
Nov    232.833333
Dec    261.833333
Name: passengers, dtype: float64

In [104]:
# Find busiest month overall
flights.groupby("month")["passengers"].sum().sort_values(ascending=False).head(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_17076\1401349432.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby("month")["passengers"].sum().sort_values(ascending=False).head(1)

month
Jul    4216
Name: passengers, dtype: int64

In [105]:
# Find least busy month
flights.groupby("month")["passengers"].sum().sort_values().head(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_17076\3911061504.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby("month")["passengers"].sum().sort_values().head(1)

month
Nov    2794
Name: passengers, dtype: int64

In [106]:
flights["month"].value_counts()

month
Jan    12
Feb    12
Mar    12
Apr    12
May    12
Jun    12
Jul    12
Aug    12
Sep    12
Oct    12
Nov    12
Dec    12
Name: count, dtype: int64

In [107]:
# Add new column: passengers growth (dummy logic)
flights["passengers_growth"]=flights["passengers"]+34

In [108]:
flights

     year month  passengers  passengers_growth
0    1949   Jan         112                146
1    1949   Feb         118                152
2    1949   Mar         132                166
3    1949   Apr         129                163
4    1949   May         121                155
5    1949   Jun         135                169
6    1949   Jul         148                182
7    1949   Aug         148                182
8    1949   Sep         136                170
9    1949   Oct         119                153
10   1949   Nov         104                138
11   1949   Dec         118                152
12   1950   Jan         115                149
13   1950   Feb         126                160
14   1950   Mar         141                175
15   1950   Apr         135                169
16   1950   May         125                159
17   1950   Jun         149                183
18   1950   Jul         170                204
19   1950   Aug         170                204
20   1950   Sep         158                192
21   1950   Oct         133                167
22   1950   Nov         114                148
23   1950   Dec         140                174
24   1951   Jan         145                179
25   1951   Feb         150                184
26   1951   Mar         178                212
27   1951   Apr         163                197
28   1951   May         172                206
29   1951   Jun         178                212
30   1951   Jul         199                233
31   1951   Aug         199                233
32   1951   Sep         184                218
33   1951   Oct         162                196
34   1951   Nov         146                180
35   1951   Dec         166                200
36   1952   Jan         171                205
37   1952   Feb         180                214
38   1952   Mar         193                227
39   1952   Apr         181                215
40   1952   May         183                217
41   1952   Jun         218                252
42   1952   Jul         230                264
43   1952   Aug         242                276
44   1952   Sep         209                243
45   1952   Oct         191                225
46   1952   Nov         172                206
47   1952   Dec         194                228
48   1953   Jan         196                230
49   1953   Feb         196                230
50   1953   Mar         236                270
51   1953   Apr         235                269
52   1953   May         229                263
53   1953   Jun         243                277
54   1953   Jul         264                298
55   1953   Aug         272                306
56   1953   Sep         237                271
57   1953   Oct         211                245
58   1953   Nov         180                214
59   1953   Dec         201                235
60   1954   Jan         204                238
61   1954   Feb         188                222
62   1954   Mar         235                269
63   1954   Apr         227                261
64   1954   May         234                268
65   1954   Jun         264                298
66   1954   Jul         302                336
67   1954   Aug         293                327
68   1954   Sep         259                293
69   1954   Oct         229                263
70   1954   Nov         203                237
71   1954   Dec         229                263
72   1955   Jan         242                276
73   1955   Feb         233                267
74   1955   Mar         267                301
75   1955   Apr         269                303
76   1955   May         270                304
77   1955   Jun         315                349
78   1955   Jul         364                398
79   1955   Aug         347                381
80   1955   Sep         312                346
81   1955   Oct         274                308
82   1955   Nov         237                271
83   1955   Dec         278                312
84   1956   Jan         284                318
85   1956   Feb         277                311
86   1956   Mar         317                351
87   1956   Apr         313                347
88   1956   May         318                352
89   1956   Jun         374                408
90   1956   Jul         413                447
91   1956   Aug         405                439
92   1956   Sep         355                389
93   1956   Oct         306                340
94   1956   Nov         271                305
95   1956   Dec         306                340
96   1957   Jan         315                349
97   1957   Feb         301                335
98   1957   Mar         356                390
99   1957   Apr         348                382
100  1957   May         355                389
101  1957   Jun         422                456
102  1957   Jul         465                499
103  1957   Aug         467                501
104  1957   Sep         404                438
105  1957   Oct         347                381
106  1957   Nov         305                339
107  1957   Dec         336                370
108  1958   Jan         340                374
109  1958   Feb         318                352
110  1958   Mar         362                396
111  1958   Apr         348                382
112  1958   May         363                397
113  1958   Jun         435                469
114  1958   Jul         491                525
115  1958   Aug         505                539
116  1958   Sep         404                438
117  1958   Oct         359                393
118  1958   Nov         310                344
119  1958   Dec         337                371
120  1959   Jan         360                394
121  1959   Feb         342                376
122  1959   Mar         406                440
123  1959   Apr         396                430
124  1959   May         420                454
125  1959   Jun         472                506
126  1959   Jul         548                582
127  1959   Aug         559                593
128  1959   Sep         463                497
129  1959   Oct         407                441
130  1959   Nov         362                396
131  1959   Dec         405                439
132  1960   Jan         417                451
133  1960   Feb         391                425
134  1960   Mar         419                453
135  1960   Apr         461                495
136  1960   May         472                506
137  1960   Jun         535                569
138  1960   Jul         622                656
139  1960   Aug         606                640
140  1960   Sep         508                542
141  1960   Oct         461                495
142  1960   Nov         390                424
143  1960   Dec         432                466

In [111]:
# Apply lambda to increase passengers by 10%
flights["passengers"]=flights["passengers"].apply(lambda x:x*1.10)
flights

     year month  passengers  passengers_growth
0    1949   Jan      135.52                146
1    1949   Feb      142.78                152
2    1949   Mar      159.72                166
3    1949   Apr      156.09                163
4    1949   May      146.41                155
5    1949   Jun      163.35                169
6    1949   Jul      179.08                182
7    1949   Aug      179.08                182
8    1949   Sep      164.56                170
9    1949   Oct      143.99                153
10   1949   Nov      125.84                138
11   1949   Dec      142.78                152
12   1950   Jan      139.15                149
13   1950   Feb      152.46                160
14   1950   Mar      170.61                175
15   1950   Apr      163.35                169
16   1950   May      151.25                159
17   1950   Jun      180.29                183
18   1950   Jul      205.70                204
19   1950   Aug      205.70                204
20   1950   Sep      191.18                192
21   1950   Oct      160.93                167
22   1950   Nov      137.94                148
23   1950   Dec      169.40                174
24   1951   Jan      175.45                179
25   1951   Feb      181.50                184
26   1951   Mar      215.38                212
27   1951   Apr      197.23                197
28   1951   May      208.12                206
29   1951   Jun      215.38                212
30   1951   Jul      240.79                233
31   1951   Aug      240.79                233
32   1951   Sep      222.64                218
33   1951   Oct      196.02                196
34   1951   Nov      176.66                180
35   1951   Dec      200.86                200
36   1952   Jan      206.91                205
37   1952   Feb      217.80                214
38   1952   Mar      233.53                227
39   1952   Apr      219.01                215
40   1952   May      221.43                217
41   1952   Jun      263.78                252
42   1952   Jul      278.30                264
43   1952   Aug      292.82                276
44   1952   Sep      252.89                243
45   1952   Oct      231.11                225
46   1952   Nov      208.12                206
47   1952   Dec      234.74                228
48   1953   Jan      237.16                230
49   1953   Feb      237.16                230
50   1953   Mar      285.56                270
51   1953   Apr      284.35                269
52   1953   May      277.09                263
53   1953   Jun      294.03                277
54   1953   Jul      319.44                298
55   1953   Aug      329.12                306
56   1953   Sep      286.77                271
57   1953   Oct      255.31                245
58   1953   Nov      217.80                214
59   1953   Dec      243.21                235
60   1954   Jan      246.84                238
61   1954   Feb      227.48                222
62   1954   Mar      284.35                269
63   1954   Apr      274.67                261
64   1954   May      283.14                268
65   1954   Jun      319.44                298
66   1954   Jul      365.42                336
67   1954   Aug      354.53                327
68   1954   Sep      313.39                293
69   1954   Oct      277.09                263
70   1954   Nov      245.63                237
71   1954   Dec      277.09                263
72   1955   Jan      292.82                276
73   1955   Feb      281.93                267
74   1955   Mar      323.07                301
75   1955   Apr      325.49                303
76   1955   May      326.70                304
77   1955   Jun      381.15                349
78   1955   Jul      440.44                398
79   1955   Aug      419.87                381
80   1955   Sep      377.52                346
81   1955   Oct      331.54                308
82   1955   Nov      286.77                271
83   1955   Dec      336.38                312
84   1956   Jan      343.64                318
85   1956   Feb      335.17                311
86   1956   Mar      383.57                351
87   1956   Apr      378.73                347
88   1956   May      384.78                352
89   1956   Jun      452.54                408
90   1956   Jul      499.73                447
91   1956   Aug      490.05                439
92   1956   Sep      429.55                389
93   1956   Oct      370.26                340
94   1956   Nov      327.91                305
95   1956   Dec      370.26                340
96   1957   Jan      381.15                349
97   1957   Feb      364.21                335
98   1957   Mar      430.76                390
99   1957   Apr      421.08                382
100  1957   May      429.55                389
101  1957   Jun      510.62                456
102  1957   Jul      562.65                499
103  1957   Aug      565.07                501
104  1957   Sep      488.84                438
105  1957   Oct      419.87                381
106  1957   Nov      369.05                339
107  1957   Dec      406.56                370
108  1958   Jan      411.40                374
109  1958   Feb      384.78                352
110  1958   Mar      438.02                396
111  1958   Apr      421.08                382
112  1958   May      439.23                397
113  1958   Jun      526.35                469
114  1958   Jul      594.11                525
115  1958   Aug      611.05                539
116  1958   Sep      488.84                438
117  1958   Oct      434.39                393
118  1958   Nov      375.10                344
119  1958   Dec      407.77                371
120  1959   Jan      435.60                394
121  1959   Feb      413.82                376
122  1959   Mar      491.26                440
123  1959   Apr      479.16                430
124  1959   May      508.20                454
125  1959   Jun      571.12                506
126  1959   Jul      663.08                582
127  1959   Aug      676.39                593
128  1959   Sep      560.23                497
129  1959   Oct      492.47                441
130  1959   Nov      438.02                396
131  1959   Dec      490.05                439
132  1960   Jan      504.57                451
133  1960   Feb      473.11                425
134  1960   Mar      506.99                453
135  1960   Apr      557.81                495
136  1960   May      571.12                506
137  1960   Jun      647.35                569
138  1960   Jul      752.62                656
139  1960   Aug      733.26                640
140  1960   Sep      614.68                542
141  1960   Oct      557.81                495
142  1960   Nov      471.90                424
143  1960   Dec      522.72                466

In [114]:
month_map = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
    "May": 5, "Jun": 6, "Jul": 7, "Aug": 8,
    "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12
}

In [116]:
flights["month"]=flights["month"].map(month_map)

In [120]:
flights

     year month  passengers  passengers_growth
0    1949     1      135.52                146
1    1949     2      142.78                152
2    1949     3      159.72                166
3    1949     4      156.09                163
4    1949     5      146.41                155
5    1949     6      163.35                169
6    1949     7      179.08                182
7    1949     8      179.08                182
8    1949     9      164.56                170
9    1949    10      143.99                153
10   1949    11      125.84                138
11   1949    12      142.78                152
12   1950     1      139.15                149
13   1950     2      152.46                160
14   1950     3      170.61                175
15   1950     4      163.35                169
16   1950     5      151.25                159
17   1950     6      180.29                183
18   1950     7      205.70                204
19   1950     8      205.70                204
20   1950     9      191.18                192
21   1950    10      160.93                167
22   1950    11      137.94                148
23   1950    12      169.40                174
24   1951     1      175.45                179
25   1951     2      181.50                184
26   1951     3      215.38                212
27   1951     4      197.23                197
28   1951     5      208.12                206
29   1951     6      215.38                212
30   1951     7      240.79                233
31   1951     8      240.79                233
32   1951     9      222.64                218
33   1951    10      196.02                196
34   1951    11      176.66                180
35   1951    12      200.86                200
36   1952     1      206.91                205
37   1952     2      217.80                214
38   1952     3      233.53                227
39   1952     4      219.01                215
40   1952     5      221.43                217
41   1952     6      263.78                252
42   1952     7      278.30                264
43   1952     8      292.82                276
44   1952     9      252.89                243
45   1952    10      231.11                225
46   1952    11      208.12                206
47   1952    12      234.74                228
48   1953     1      237.16                230
49   1953     2      237.16                230
50   1953     3      285.56                270
51   1953     4      284.35                269
52   1953     5      277.09                263
53   1953     6      294.03                277
54   1953     7      319.44                298
55   1953     8      329.12                306
56   1953     9      286.77                271
57   1953    10      255.31                245
58   1953    11      217.80                214
59   1953    12      243.21                235
60   1954     1      246.84                238
61   1954     2      227.48                222
62   1954     3      284.35                269
63   1954     4      274.67                261
64   1954     5      283.14                268
65   1954     6      319.44                298
66   1954     7      365.42                336
67   1954     8      354.53                327
68   1954     9      313.39                293
69   1954    10      277.09                263
70   1954    11      245.63                237
71   1954    12      277.09                263
72   1955     1      292.82                276
73   1955     2      281.93                267
74   1955     3      323.07                301
75   1955     4      325.49                303
76   1955     5      326.70                304
77   1955     6      381.15                349
78   1955     7      440.44                398
79   1955     8      419.87                381
80   1955     9      377.52                346
81   1955    10      331.54                308
82   1955    11      286.77                271
83   1955    12      336.38                312
84   1956     1      343.64                318
85   1956     2      335.17                311
86   1956     3      383.57                351
87   1956     4      378.73                347
88   1956     5      384.78                352
89   1956     6      452.54                408
90   1956     7      499.73                447
91   1956     8      490.05                439
92   1956     9      429.55                389
93   1956    10      370.26                340
94   1956    11      327.91                305
95   1956    12      370.26                340
96   1957     1      381.15                349
97   1957     2      364.21                335
98   1957     3      430.76                390
99   1957     4      421.08                382
100  1957     5      429.55                389
101  1957     6      510.62                456
102  1957     7      562.65                499
103  1957     8      565.07                501
104  1957     9      488.84                438
105  1957    10      419.87                381
106  1957    11      369.05                339
107  1957    12      406.56                370
108  1958     1      411.40                374
109  1958     2      384.78                352
110  1958     3      438.02                396
111  1958     4      421.08                382
112  1958     5      439.23                397
113  1958     6      526.35                469
114  1958     7      594.11                525
115  1958     8      611.05                539
116  1958     9      488.84                438
117  1958    10      434.39                393
118  1958    11      375.10                344
119  1958    12      407.77                371
120  1959     1      435.60                394
121  1959     2      413.82                376
122  1959     3      491.26                440
123  1959     4      479.16                430
124  1959     5      508.20                454
125  1959     6      571.12                506
126  1959     7      663.08                582
127  1959     8      676.39                593
128  1959     9      560.23                497
129  1959    10      492.47                441
130  1959    11      438.02                396
131  1959    12      490.05                439
132  1960     1      504.57                451
133  1960     2      473.11                425
134  1960     3      506.99                453
135  1960     4      557.81                495
136  1960     5      571.12                506
137  1960     6      647.35                569
138  1960     7      752.62                656
139  1960     8      733.26                640
140  1960     9      614.68                542
141  1960    10      557.81                495
142  1960    11      471.90                424
143  1960    12      522.72                466

In [122]:
# Sort by year and passengers
flights.sort_values(["year","passengers"])

     year month  passengers  passengers_growth
10   1949    11      125.84                138
0    1949     1      135.52                146
1    1949     2      142.78                152
11   1949    12      142.78                152
9    1949    10      143.99                153
4    1949     5      146.41                155
3    1949     4      156.09                163
2    1949     3      159.72                166
5    1949     6      163.35                169
8    1949     9      164.56                170
6    1949     7      179.08                182
7    1949     8      179.08                182
22   1950    11      137.94                148
12   1950     1      139.15                149
16   1950     5      151.25                159
13   1950     2      152.46                160
21   1950    10      160.93                167
15   1950     4      163.35                169
23   1950    12      169.40                174
14   1950     3      170.61                175
17   1950     6      180.29                183
20   1950     9      191.18                192
18   1950     7      205.70                204
19   1950     8      205.70                204
24   1951     1      175.45                179
34   1951    11      176.66                180
25   1951     2      181.50                184
33   1951    10      196.02                196
27   1951     4      197.23                197
35   1951    12      200.86                200
28   1951     5      208.12                206
26   1951     3      215.38                212
29   1951     6      215.38                212
32   1951     9      222.64                218
30   1951     7      240.79                233
31   1951     8      240.79                233
36   1952     1      206.91                205
46   1952    11      208.12                206
37   1952     2      217.80                214
39   1952     4      219.01                215
40   1952     5      221.43                217
45   1952    10      231.11                225
38   1952     3      233.53                227
47   1952    12      234.74                228
44   1952     9      252.89                243
41   1952     6      263.78                252
42   1952     7      278.30                264
43   1952     8      292.82                276
58   1953    11      217.80                214
48   1953     1      237.16                230
49   1953     2      237.16                230
59   1953    12      243.21                235
57   1953    10      255.31                245
52   1953     5      277.09                263
51   1953     4      284.35                269
50   1953     3      285.56                270
56   1953     9      286.77                271
53   1953     6      294.03                277
54   1953     7      319.44                298
55   1953     8      329.12                306
61   1954     2      227.48                222
70   1954    11      245.63                237
60   1954     1      246.84                238
63   1954     4      274.67                261
69   1954    10      277.09                263
71   1954    12      277.09                263
64   1954     5      283.14                268
62   1954     3      284.35                269
68   1954     9      313.39                293
65   1954     6      319.44                298
67   1954     8      354.53                327
66   1954     7      365.42                336
73   1955     2      281.93                267
82   1955    11      286.77                271
72   1955     1      292.82                276
74   1955     3      323.07                301
75   1955     4      325.49                303
76   1955     5      326.70                304
81   1955    10      331.54                308
83   1955    12      336.38                312
80   1955     9      377.52                346
77   1955     6      381.15                349
79   1955     8      419.87                381
78   1955     7      440.44                398
94   1956    11      327.91                305
85   1956     2      335.17                311
84   1956     1      343.64                318
93   1956    10      370.26                340
95   1956    12      370.26                340
87   1956     4      378.73                347
86   1956     3      383.57                351
88   1956     5      384.78                352
92   1956     9      429.55                389
89   1956     6      452.54                408
91   1956     8      490.05                439
90   1956     7      499.73                447
97   1957     2      364.21                335
106  1957    11      369.05                339
96   1957     1      381.15                349
107  1957    12      406.56                370
105  1957    10      419.87                381
99   1957     4      421.08                382
100  1957     5      429.55                389
98   1957     3      430.76                390
104  1957     9      488.84                438
101  1957     6      510.62                456
102  1957     7      562.65                499
103  1957     8      565.07                501
118  1958    11      375.10                344
109  1958     2      384.78                352
119  1958    12      407.77                371
108  1958     1      411.40                374
111  1958     4      421.08                382
117  1958    10      434.39                393
110  1958     3      438.02                396
112  1958     5      439.23                397
116  1958     9      488.84                438
113  1958     6      526.35                469
114  1958     7      594.11                525
115  1958     8      611.05                539
121  1959     2      413.82                376
120  1959     1      435.60                394
130  1959    11      438.02                396
123  1959     4      479.16                430
131  1959    12      490.05                439
122  1959     3      491.26                440
129  1959    10      492.47                441
124  1959     5      508.20                454
128  1959     9      560.23                497
125  1959     6      571.12                506
126  1959     7      663.08                582
127  1959     8      676.39                593
142  1960    11      471.90                424
133  1960     2      473.11                425
132  1960     1      504.57                451
134  1960     3      506.99                453
143  1960    12      522.72                466
135  1960     4      557.81                495
141  1960    10      557.81                495
136  1960     5      571.12                506
140  1960     9      614.68                542
137  1960     6      647.35                569
139  1960     8      733.26                640
138  1960     7      752.62                656

In [123]:
# Create new column: passengers per 100
flights["passengers_per_100"] =flights["passengers"]/100
flights

     year month  passengers  passengers_growth  passengers_per_100
0    1949     1      135.52                146              1.3552
1    1949     2      142.78                152              1.4278
2    1949     3      159.72                166              1.5972
3    1949     4      156.09                163              1.5609
4    1949     5      146.41                155              1.4641
5    1949     6      163.35                169              1.6335
6    1949     7      179.08                182              1.7908
7    1949     8      179.08                182              1.7908
8    1949     9      164.56                170              1.6456
9    1949    10      143.99                153              1.4399
10   1949    11      125.84                138              1.2584
11   1949    12      142.78                152              1.4278
12   1950     1      139.15                149              1.3915
13   1950     2      152.46                160              1.5246
14   1950     3      170.61                175              1.7061
15   1950     4      163.35                169              1.6335
16   1950     5      151.25                159              1.5125
17   1950     6      180.29                183              1.8029
18   1950     7      205.70                204              2.0570
19   1950     8      205.70                204              2.0570
20   1950     9      191.18                192              1.9118
21   1950    10      160.93                167              1.6093
22   1950    11      137.94                148              1.3794
23   1950    12      169.40                174              1.6940
24   1951     1      175.45                179              1.7545
25   1951     2      181.50                184              1.8150
26   1951     3      215.38                212              2.1538
27   1951     4      197.23                197              1.9723
28   1951     5      208.12                206              2.0812
29   1951     6      215.38                212              2.1538
30   1951     7      240.79                233              2.4079
31   1951     8      240.79                233              2.4079
32   1951     9      222.64                218              2.2264
33   1951    10      196.02                196              1.9602
34   1951    11      176.66                180              1.7666
35   1951    12      200.86                200              2.0086
36   1952     1      206.91                205              2.0691
37   1952     2      217.80                214              2.1780
38   1952     3      233.53                227              2.3353
39   1952     4      219.01                215              2.1901
40   1952     5      221.43                217              2.2143
41   1952     6      263.78                252              2.6378
42   1952     7      278.30                264              2.7830
43   1952     8      292.82                276              2.9282
44   1952     9      252.89                243              2.5289
45   1952    10      231.11                225              2.3111
46   1952    11      208.12                206              2.0812
47   1952    12      234.74                228              2.3474
48   1953     1      237.16                230              2.3716
49   1953     2      237.16                230              2.3716
50   1953     3      285.56                270              2.8556
51   1953     4      284.35                269              2.8435
52   1953     5      277.09                263              2.7709
53   1953     6      294.03                277              2.9403
54   1953     7      319.44                298              3.1944
55   1953     8      329.12                306              3.2912
56   1953     9      286.77                271              2.8677
57   1953    10      255.31                245              2.5531
58   1953    11      217.80                214              2.1780
59   1953    12      243.21                235              2.4321
60   1954     1      246.84                238              2.4684
61   1954     2      227.48                222              2.2748
62   1954     3      284.35                269              2.8435
63   1954     4      274.67                261              2.7467
64   1954     5      283.14                268              2.8314
65   1954     6      319.44                298              3.1944
66   1954     7      365.42                336              3.6542
67   1954     8      354.53                327              3.5453
68   1954     9      313.39                293              3.1339
69   1954    10      277.09                263              2.7709
70   1954    11      245.63                237              2.4563
71   1954    12      277.09                263              2.7709
72   1955     1      292.82                276              2.9282
73   1955     2      281.93                267              2.8193
74   1955     3      323.07                301              3.2307
75   1955     4      325.49                303              3.2549
76   1955     5      326.70                304              3.2670
77   1955     6      381.15                349              3.8115
78   1955     7      440.44                398              4.4044
79   1955     8      419.87                381              4.1987
80   1955     9      377.52                346              3.7752
81   1955    10      331.54                308              3.3154
82   1955    11      286.77                271              2.8677
83   1955    12      336.38                312              3.3638
84   1956     1      343.64                318              3.4364
85   1956     2      335.17                311              3.3517
86   1956     3      383.57                351              3.8357
87   1956     4      378.73                347              3.7873
88   1956     5      384.78                352              3.8478
89   1956     6      452.54                408              4.5254
90   1956     7      499.73                447              4.9973
91   1956     8      490.05                439              4.9005
92   1956     9      429.55                389              4.2955
93   1956    10      370.26                340              3.7026
94   1956    11      327.91                305              3.2791
95   1956    12      370.26                340              3.7026
96   1957     1      381.15                349              3.8115
97   1957     2      364.21                335              3.6421
98   1957     3      430.76                390              4.3076
99   1957     4      421.08                382              4.2108
100  1957     5      429.55                389              4.2955
101  1957     6      510.62                456              5.1062
102  1957     7      562.65                499              5.6265
103  1957     8      565.07                501              5.6507
104  1957     9      488.84                438              4.8884
105  1957    10      419.87                381              4.1987
106  1957    11      369.05                339              3.6905
107  1957    12      406.56                370              4.0656
108  1958     1      411.40                374              4.1140
109  1958     2      384.78                352              3.8478
110  1958     3      438.02                396              4.3802
111  1958     4      421.08                382              4.2108
112  1958     5      439.23                397              4.3923
113  1958     6      526.35                469              5.2635
114  1958     7      594.11                525              5.9411
115  1958     8      611.05                539              6.1105
116  1958     9      488.84                438              4.8884
117  1958    10      434.39                393              4.3439
118  1958    11      375.10                344              3.7510
119  1958    12      407.77                371              4.0777
120  1959     1      435.60                394              4.3560
121  1959     2      413.82                376              4.1382
122  1959     3      491.26                440              4.9126
123  1959     4      479.16                430              4.7916
124  1959     5      508.20                454              5.0820
125  1959     6      571.12                506              5.7112
126  1959     7      663.08                582              6.6308
127  1959     8      676.39                593              6.7639
128  1959     9      560.23                497              5.6023
129  1959    10      492.47                441              4.9247
130  1959    11      438.02                396              4.3802
131  1959    12      490.05                439              4.9005
132  1960     1      504.57                451              5.0457
133  1960     2      473.11                425              4.7311
134  1960     3      506.99                453              5.0699
135  1960     4      557.81                495              5.5781
136  1960     5      571.12                506              5.7112
137  1960     6      647.35                569              6.4735
138  1960     7      752.62                656              7.5262
139  1960     8      733.26                640              7.3326
140  1960     9      614.68                542              6.1468
141  1960    10      557.81                495              5.5781
142  1960    11      471.90                424              4.7190
143  1960    12      522.72                466              5.2272

In [ ]:
# What is normalization?

Normalization means scaling your data to a standard range, usually 0 to 1, so it’s easier to compare values across different columns or datasets.

    normalized=max(x)−min(x)/x−min(x)

In [124]:
# Normalize passengers
flights["passengers"]=flights["passengers"]-flights["passengers"].min()/flights["passengers"].max()-flights["passengers"].min()

In [125]:
flights

     year month  passengers  passengers_growth  passengers_per_100
0    1949     1    9.512797                146              1.3552
1    1949     2   16.772797                152              1.4278
2    1949     3   33.712797                166              1.5972
3    1949     4   30.082797                163              1.5609
4    1949     5   20.402797                155              1.4641
5    1949     6   37.342797                169              1.6335
6    1949     7   53.072797                182              1.7908
7    1949     8   53.072797                182              1.7908
8    1949     9   38.552797                170              1.6456
9    1949    10   17.982797                153              1.4399
10   1949    11   -0.167203                138              1.2584
11   1949    12   16.772797                152              1.4278
12   1950     1   13.142797                149              1.3915
13   1950     2   26.452797                160              1.5246
14   1950     3   44.602797                175              1.7061
15   1950     4   37.342797                169              1.6335
16   1950     5   25.242797                159              1.5125
17   1950     6   54.282797                183              1.8029
18   1950     7   79.692797                204              2.0570
19   1950     8   79.692797                204              2.0570
20   1950     9   65.172797                192              1.9118
21   1950    10   34.922797                167              1.6093
22   1950    11   11.932797                148              1.3794
23   1950    12   43.392797                174              1.6940
24   1951     1   49.442797                179              1.7545
25   1951     2   55.492797                184              1.8150
26   1951     3   89.372797                212              2.1538
27   1951     4   71.222797                197              1.9723
28   1951     5   82.112797                206              2.0812
29   1951     6   89.372797                212              2.1538
30   1951     7  114.782797                233              2.4079
31   1951     8  114.782797                233              2.4079
32   1951     9   96.632797                218              2.2264
33   1951    10   70.012797                196              1.9602
34   1951    11   50.652797                180              1.7666
35   1951    12   74.852797                200              2.0086
36   1952     1   80.902797                205              2.0691
37   1952     2   91.792797                214              2.1780
38   1952     3  107.522797                227              2.3353
39   1952     4   93.002797                215              2.1901
40   1952     5   95.422797                217              2.2143
41   1952     6  137.772797                252              2.6378
42   1952     7  152.292797                264              2.7830
43   1952     8  166.812797                276              2.9282
44   1952     9  126.882797                243              2.5289
45   1952    10  105.102797                225              2.3111
46   1952    11   82.112797                206              2.0812
47   1952    12  108.732797                228              2.3474
48   1953     1  111.152797                230              2.3716
49   1953     2  111.152797                230              2.3716
50   1953     3  159.552797                270              2.8556
51   1953     4  158.342797                269              2.8435
52   1953     5  151.082797                263              2.7709
53   1953     6  168.022797                277              2.9403
54   1953     7  193.432797                298              3.1944
55   1953     8  203.112797                306              3.2912
56   1953     9  160.762797                271              2.8677
57   1953    10  129.302797                245              2.5531
58   1953    11   91.792797                214              2.1780
59   1953    12  117.202797                235              2.4321
60   1954     1  120.832797                238              2.4684
61   1954     2  101.472797                222              2.2748
62   1954     3  158.342797                269              2.8435
63   1954     4  148.662797                261              2.7467
64   1954     5  157.132797                268              2.8314
65   1954     6  193.432797                298              3.1944
66   1954     7  239.412797                336              3.6542
67   1954     8  228.522797                327              3.5453
68   1954     9  187.382797                293              3.1339
69   1954    10  151.082797                263              2.7709
70   1954    11  119.622797                237              2.4563
71   1954    12  151.082797                263              2.7709
72   1955     1  166.812797                276              2.9282
73   1955     2  155.922797                267              2.8193
74   1955     3  197.062797                301              3.2307
75   1955     4  199.482797                303              3.2549
76   1955     5  200.692797                304              3.2670
77   1955     6  255.142797                349              3.8115
78   1955     7  314.432797                398              4.4044
79   1955     8  293.862797                381              4.1987
80   1955     9  251.512797                346              3.7752
81   1955    10  205.532797                308              3.3154
82   1955    11  160.762797                271              2.8677
83   1955    12  210.372797                312              3.3638
84   1956     1  217.632797                318              3.4364
85   1956     2  209.162797                311              3.3517
86   1956     3  257.562797                351              3.8357
87   1956     4  252.722797                347              3.7873
88   1956     5  258.772797                352              3.8478
89   1956     6  326.532797                408              4.5254
90   1956     7  373.722797                447              4.9973
91   1956     8  364.042797                439              4.9005
92   1956     9  303.542797                389              4.2955
93   1956    10  244.252797                340              3.7026
94   1956    11  201.902797                305              3.2791
95   1956    12  244.252797                340              3.7026
96   1957     1  255.142797                349              3.8115
97   1957     2  238.202797                335              3.6421
98   1957     3  304.752797                390              4.3076
99   1957     4  295.072797                382              4.2108
100  1957     5  303.542797                389              4.2955
101  1957     6  384.612797                456              5.1062
102  1957     7  436.642797                499              5.6265
103  1957     8  439.062797                501              5.6507
104  1957     9  362.832797                438              4.8884
105  1957    10  293.862797                381              4.1987
106  1957    11  243.042797                339              3.6905
107  1957    12  280.552797                370              4.0656
108  1958     1  285.392797                374              4.1140
109  1958     2  258.772797                352              3.8478
110  1958     3  312.012797                396              4.3802
111  1958     4  295.072797                382              4.2108
112  1958     5  313.222797                397              4.3923
113  1958     6  400.342797                469              5.2635
114  1958     7  468.102797                525              5.9411
115  1958     8  485.042797                539              6.1105
116  1958     9  362.832797                438              4.8884
117  1958    10  308.382797                393              4.3439
118  1958    11  249.092797                344              3.7510
119  1958    12  281.762797                371              4.0777
120  1959     1  309.592797                394              4.3560
121  1959     2  287.812797                376              4.1382
122  1959     3  365.252797                440              4.9126
123  1959     4  353.152797                430              4.7916
124  1959     5  382.192797                454              5.0820
125  1959     6  445.112797                506              5.7112
126  1959     7  537.072797                582              6.6308
127  1959     8  550.382797                593              6.7639
128  1959     9  434.222797                497              5.6023
129  1959    10  366.462797                441              4.9247
130  1959    11  312.012797                396              4.3802
131  1959    12  364.042797                439              4.9005
132  1960     1  378.562797                451              5.0457
133  1960     2  347.102797                425              4.7311
134  1960     3  380.982797                453              5.0699
135  1960     4  431.802797                495              5.5781
136  1960     5  445.112797                506              5.7112
137  1960     6  521.342797                569              6.4735
138  1960     7  626.612797                656              7.5262
139  1960     8  607.252797                640              7.3326
140  1960     9  488.672797                542              6.1468
141  1960    10  431.802797                495              5.5781
142  1960    11  345.892797                424              4.7190
143  1960    12  396.712797                466              5.2272

In [ ]:
# Detect duplicates

Returns a boolean Series: True if the row is a duplicate of a previous row.

In [126]:
flights.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
dtype: bool

In [128]:
flights[flights.duplicated()]
flights

     year month  passengers  passengers_growth  passengers_per_100
0    1949     1    9.512797                146              1.3552
1    1949     2   16.772797                152              1.4278
2    1949     3   33.712797                166              1.5972
3    1949     4   30.082797                163              1.5609
4    1949     5   20.402797                155              1.4641
5    1949     6   37.342797                169              1.6335
6    1949     7   53.072797                182              1.7908
7    1949     8   53.072797                182              1.7908
8    1949     9   38.552797                170              1.6456
9    1949    10   17.982797                153              1.4399
10   1949    11   -0.167203                138              1.2584
11   1949    12   16.772797                152              1.4278
12   1950     1   13.142797                149              1.3915
13   1950     2   26.452797                160              1.5246
14   1950     3   44.602797                175              1.7061
15   1950     4   37.342797                169              1.6335
16   1950     5   25.242797                159              1.5125
17   1950     6   54.282797                183              1.8029
18   1950     7   79.692797                204              2.0570
19   1950     8   79.692797                204              2.0570
20   1950     9   65.172797                192              1.9118
21   1950    10   34.922797                167              1.6093
22   1950    11   11.932797                148              1.3794
23   1950    12   43.392797                174              1.6940
24   1951     1   49.442797                179              1.7545
25   1951     2   55.492797                184              1.8150
26   1951     3   89.372797                212              2.1538
27   1951     4   71.222797                197              1.9723
28   1951     5   82.112797                206              2.0812
29   1951     6   89.372797                212              2.1538
30   1951     7  114.782797                233              2.4079
31   1951     8  114.782797                233              2.4079
32   1951     9   96.632797                218              2.2264
33   1951    10   70.012797                196              1.9602
34   1951    11   50.652797                180              1.7666
35   1951    12   74.852797                200              2.0086
36   1952     1   80.902797                205              2.0691
37   1952     2   91.792797                214              2.1780
38   1952     3  107.522797                227              2.3353
39   1952     4   93.002797                215              2.1901
40   1952     5   95.422797                217              2.2143
41   1952     6  137.772797                252              2.6378
42   1952     7  152.292797                264              2.7830
43   1952     8  166.812797                276              2.9282
44   1952     9  126.882797                243              2.5289
45   1952    10  105.102797                225              2.3111
46   1952    11   82.112797                206              2.0812
47   1952    12  108.732797                228              2.3474
48   1953     1  111.152797                230              2.3716
49   1953     2  111.152797                230              2.3716
50   1953     3  159.552797                270              2.8556
51   1953     4  158.342797                269              2.8435
52   1953     5  151.082797                263              2.7709
53   1953     6  168.022797                277              2.9403
54   1953     7  193.432797                298              3.1944
55   1953     8  203.112797                306              3.2912
56   1953     9  160.762797                271              2.8677
57   1953    10  129.302797                245              2.5531
58   1953    11   91.792797                214              2.1780
59   1953    12  117.202797                235              2.4321
60   1954     1  120.832797                238              2.4684
61   1954     2  101.472797                222              2.2748
62   1954     3  158.342797                269              2.8435
63   1954     4  148.662797                261              2.7467
64   1954     5  157.132797                268              2.8314
65   1954     6  193.432797                298              3.1944
66   1954     7  239.412797                336              3.6542
67   1954     8  228.522797                327              3.5453
68   1954     9  187.382797                293              3.1339
69   1954    10  151.082797                263              2.7709
70   1954    11  119.622797                237              2.4563
71   1954    12  151.082797                263              2.7709
72   1955     1  166.812797                276              2.9282
73   1955     2  155.922797                267              2.8193
74   1955     3  197.062797                301              3.2307
75   1955     4  199.482797                303              3.2549
76   1955     5  200.692797                304              3.2670
77   1955     6  255.142797                349              3.8115
78   1955     7  314.432797                398              4.4044
79   1955     8  293.862797                381              4.1987
80   1955     9  251.512797                346              3.7752
81   1955    10  205.532797                308              3.3154
82   1955    11  160.762797                271              2.8677
83   1955    12  210.372797                312              3.3638
84   1956     1  217.632797                318              3.4364
85   1956     2  209.162797                311              3.3517
86   1956     3  257.562797                351              3.8357
87   1956     4  252.722797                347              3.7873
88   1956     5  258.772797                352              3.8478
89   1956     6  326.532797                408              4.5254
90   1956     7  373.722797                447              4.9973
91   1956     8  364.042797                439              4.9005
92   1956     9  303.542797                389              4.2955
93   1956    10  244.252797                340              3.7026
94   1956    11  201.902797                305              3.2791
95   1956    12  244.252797                340              3.7026
96   1957     1  255.142797                349              3.8115
97   1957     2  238.202797                335              3.6421
98   1957     3  304.752797                390              4.3076
99   1957     4  295.072797                382              4.2108
100  1957     5  303.542797                389              4.2955
101  1957     6  384.612797                456              5.1062
102  1957     7  436.642797                499              5.6265
103  1957     8  439.062797                501              5.6507
104  1957     9  362.832797                438              4.8884
105  1957    10  293.862797                381              4.1987
106  1957    11  243.042797                339              3.6905
107  1957    12  280.552797                370              4.0656
108  1958     1  285.392797                374              4.1140
109  1958     2  258.772797                352              3.8478
110  1958     3  312.012797                396              4.3802
111  1958     4  295.072797                382              4.2108
112  1958     5  313.222797                397              4.3923
113  1958     6  400.342797                469              5.2635
114  1958     7  468.102797                525              5.9411
115  1958     8  485.042797                539              6.1105
116  1958     9  362.832797                438              4.8884
117  1958    10  308.382797                393              4.3439
118  1958    11  249.092797                344              3.7510
119  1958    12  281.762797                371              4.0777
120  1959     1  309.592797                394              4.3560
121  1959     2  287.812797                376              4.1382
122  1959     3  365.252797                440              4.9126
123  1959     4  353.152797                430              4.7916
124  1959     5  382.192797                454              5.0820
125  1959     6  445.112797                506              5.7112
126  1959     7  537.072797                582              6.6308
127  1959     8  550.382797                593              6.7639
128  1959     9  434.222797                497              5.6023
129  1959    10  366.462797                441              4.9247
130  1959    11  312.012797                396              4.3802
131  1959    12  364.042797                439              4.9005
132  1960     1  378.562797                451              5.0457
133  1960     2  347.102797                425              4.7311
134  1960     3  380.982797                453              5.0699
135  1960     4  431.802797                495              5.5781
136  1960     5  445.112797                506              5.7112
137  1960     6  521.342797                569              6.4735
138  1960     7  626.612797                656              7.5262
139  1960     8  607.252797                640              7.3326
140  1960     9  488.672797                542              6.1468
141  1960    10  431.802797                495              5.5781
142  1960    11  345.892797                424              4.7190
143  1960    12  396.712797                466              5.2272

In [130]:
flights.drop_duplicates(inplace=True)
flights

     year month  passengers  passengers_growth  passengers_per_100
0    1949     1    9.512797                146              1.3552
1    1949     2   16.772797                152              1.4278
2    1949     3   33.712797                166              1.5972
3    1949     4   30.082797                163              1.5609
4    1949     5   20.402797                155              1.4641
5    1949     6   37.342797                169              1.6335
6    1949     7   53.072797                182              1.7908
7    1949     8   53.072797                182              1.7908
8    1949     9   38.552797                170              1.6456
9    1949    10   17.982797                153              1.4399
10   1949    11   -0.167203                138              1.2584
11   1949    12   16.772797                152              1.4278
12   1950     1   13.142797                149              1.3915
13   1950     2   26.452797                160              1.5246
14   1950     3   44.602797                175              1.7061
15   1950     4   37.342797                169              1.6335
16   1950     5   25.242797                159              1.5125
17   1950     6   54.282797                183              1.8029
18   1950     7   79.692797                204              2.0570
19   1950     8   79.692797                204              2.0570
20   1950     9   65.172797                192              1.9118
21   1950    10   34.922797                167              1.6093
22   1950    11   11.932797                148              1.3794
23   1950    12   43.392797                174              1.6940
24   1951     1   49.442797                179              1.7545
25   1951     2   55.492797                184              1.8150
26   1951     3   89.372797                212              2.1538
27   1951     4   71.222797                197              1.9723
28   1951     5   82.112797                206              2.0812
29   1951     6   89.372797                212              2.1538
30   1951     7  114.782797                233              2.4079
31   1951     8  114.782797                233              2.4079
32   1951     9   96.632797                218              2.2264
33   1951    10   70.012797                196              1.9602
34   1951    11   50.652797                180              1.7666
35   1951    12   74.852797                200              2.0086
36   1952     1   80.902797                205              2.0691
37   1952     2   91.792797                214              2.1780
38   1952     3  107.522797                227              2.3353
39   1952     4   93.002797                215              2.1901
40   1952     5   95.422797                217              2.2143
41   1952     6  137.772797                252              2.6378
42   1952     7  152.292797                264              2.7830
43   1952     8  166.812797                276              2.9282
44   1952     9  126.882797                243              2.5289
45   1952    10  105.102797                225              2.3111
46   1952    11   82.112797                206              2.0812
47   1952    12  108.732797                228              2.3474
48   1953     1  111.152797                230              2.3716
49   1953     2  111.152797                230              2.3716
50   1953     3  159.552797                270              2.8556
51   1953     4  158.342797                269              2.8435
52   1953     5  151.082797                263              2.7709
53   1953     6  168.022797                277              2.9403
54   1953     7  193.432797                298              3.1944
55   1953     8  203.112797                306              3.2912
56   1953     9  160.762797                271              2.8677
57   1953    10  129.302797                245              2.5531
58   1953    11   91.792797                214              2.1780
59   1953    12  117.202797                235              2.4321
60   1954     1  120.832797                238              2.4684
61   1954     2  101.472797                222              2.2748
62   1954     3  158.342797                269              2.8435
63   1954     4  148.662797                261              2.7467
64   1954     5  157.132797                268              2.8314
65   1954     6  193.432797                298              3.1944
66   1954     7  239.412797                336              3.6542
67   1954     8  228.522797                327              3.5453
68   1954     9  187.382797                293              3.1339
69   1954    10  151.082797                263              2.7709
70   1954    11  119.622797                237              2.4563
71   1954    12  151.082797                263              2.7709
72   1955     1  166.812797                276              2.9282
73   1955     2  155.922797                267              2.8193
74   1955     3  197.062797                301              3.2307
75   1955     4  199.482797                303              3.2549
76   1955     5  200.692797                304              3.2670
77   1955     6  255.142797                349              3.8115
78   1955     7  314.432797                398              4.4044
79   1955     8  293.862797                381              4.1987
80   1955     9  251.512797                346              3.7752
81   1955    10  205.532797                308              3.3154
82   1955    11  160.762797                271              2.8677
83   1955    12  210.372797                312              3.3638
84   1956     1  217.632797                318              3.4364
85   1956     2  209.162797                311              3.3517
86   1956     3  257.562797                351              3.8357
87   1956     4  252.722797                347              3.7873
88   1956     5  258.772797                352              3.8478
89   1956     6  326.532797                408              4.5254
90   1956     7  373.722797                447              4.9973
91   1956     8  364.042797                439              4.9005
92   1956     9  303.542797                389              4.2955
93   1956    10  244.252797                340              3.7026
94   1956    11  201.902797                305              3.2791
95   1956    12  244.252797                340              3.7026
96   1957     1  255.142797                349              3.8115
97   1957     2  238.202797                335              3.6421
98   1957     3  304.752797                390              4.3076
99   1957     4  295.072797                382              4.2108
100  1957     5  303.542797                389              4.2955
101  1957     6  384.612797                456              5.1062
102  1957     7  436.642797                499              5.6265
103  1957     8  439.062797                501              5.6507
104  1957     9  362.832797                438              4.8884
105  1957    10  293.862797                381              4.1987
106  1957    11  243.042797                339              3.6905
107  1957    12  280.552797                370              4.0656
108  1958     1  285.392797                374              4.1140
109  1958     2  258.772797                352              3.8478
110  1958     3  312.012797                396              4.3802
111  1958     4  295.072797                382              4.2108
112  1958     5  313.222797                397              4.3923
113  1958     6  400.342797                469              5.2635
114  1958     7  468.102797                525              5.9411
115  1958     8  485.042797                539              6.1105
116  1958     9  362.832797                438              4.8884
117  1958    10  308.382797                393              4.3439
118  1958    11  249.092797                344              3.7510
119  1958    12  281.762797                371              4.0777
120  1959     1  309.592797                394              4.3560
121  1959     2  287.812797                376              4.1382
122  1959     3  365.252797                440              4.9126
123  1959     4  353.152797                430              4.7916
124  1959     5  382.192797                454              5.0820
125  1959     6  445.112797                506              5.7112
126  1959     7  537.072797                582              6.6308
127  1959     8  550.382797                593              6.7639
128  1959     9  434.222797                497              5.6023
129  1959    10  366.462797                441              4.9247
130  1959    11  312.012797                396              4.3802
131  1959    12  364.042797                439              4.9005
132  1960     1  378.562797                451              5.0457
133  1960     2  347.102797                425              4.7311
134  1960     3  380.982797                453              5.0699
135  1960     4  431.802797                495              5.5781
136  1960     5  445.112797                506              5.7112
137  1960     6  521.342797                569              6.4735
138  1960     7  626.612797                656              7.5262
139  1960     8  607.252797                640              7.3326
140  1960     9  488.672797                542              6.1468
141  1960    10  431.802797                495              5.5781
142  1960    11  345.892797                424              4.7190
143  1960    12  396.712797                466              5.2272

In [ ]:
A pivot table is a way to summarize data in a table format.

You can aggregate values (like sum, mean, count) based on rows and columns.

In [132]:
# Create pivot table (year vs month)
pivot=flights.pivot_table(index="year", 
    columns="month", 
    values="passengers", 
    aggfunc="mean"  )
pivot

C:\Users\HP\AppData\Local\Temp\ipykernel_17076\735050048.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot=flights.pivot_table(index="year",

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
1949,9.512797,16.772797,33.712797,30.082797,20.402797,37.342797,53.072797,53.072797,38.552797,17.982797,-0.167203,16.772797
1950,13.142797,26.452797,44.602797,37.342797,25.242797,54.282797,79.692797,79.692797,65.172797,34.922797,11.932797,43.392797
1951,49.442797,55.492797,89.372797,71.222797,82.112797,89.372797,114.782797,114.782797,96.632797,70.012797,50.652797,74.852797
1952,80.902797,91.792797,107.522797,93.002797,95.422797,137.772797,152.292797,166.812797,126.882797,105.102797,82.112797,108.732797
1953,111.152797,111.152797,159.552797,158.342797,151.082797,168.022797,193.432797,203.112797,160.762797,129.302797,91.792797,117.202797
1954,120.832797,101.472797,158.342797,148.662797,157.132797,193.432797,239.412797,228.522797,187.382797,151.082797,119.622797,151.082797
1955,166.812797,155.922797,197.062797,199.482797,200.692797,255.142797,314.432797,293.862797,251.512797,205.532797,160.762797,210.372797
1956,217.632797,209.162797,257.562797,252.722797,258.772797,326.532797,373.722797,364.042797,303.542797,244.252797,201.902797,244.252797
1957,255.142797,238.202797,304.752797,295.072797,303.542797,384.612797,436.642797,439.062797,362.832797,293.862797,243.042797,280.552797
1958,285.392797,258.772797,312.012797,295.072797,313.222797,400.342797,468.102797,485.042797,362.832797,308.382797,249.092797,281.762797
1959,309.592797,287.812797,365.252797,353.152797,382.192797,445.112797,537.072797,550.382797,434.222797,366.462797,312.012797,364.042797
1960,378.562797,347.102797,380.982797,431.802797,445.112797,521.342797,626.612797,607.252797,488.672797,431.802797,345.892797,396.712797

In [ ]:
# Create pivot table (avg passengers)

In [141]:
month_map = {"Jan":1, "Feb":2, "Mar":3, "Apr":4,
             "May":5, "Jun":6, "Jul":7, "Aug":8,
             "Sep":9, "Oct":10, "Nov":11, "Dec":12}
flights["month"] = flights["month"].map(month_map)
flights

     year  month  passengers  passengers_growth  passengers_per_100
0    1949    NaN    9.512797                146              1.3552
1    1949    NaN   16.772797                152              1.4278
2    1949    NaN   33.712797                166              1.5972
3    1949    NaN   30.082797                163              1.5609
4    1949    NaN   20.402797                155              1.4641
5    1949    NaN   37.342797                169              1.6335
6    1949    NaN   53.072797                182              1.7908
7    1949    NaN   53.072797                182              1.7908
8    1949    NaN   38.552797                170              1.6456
9    1949    NaN   17.982797                153              1.4399
10   1949    NaN   -0.167203                138              1.2584
11   1949    NaN   16.772797                152              1.4278
12   1950    NaN   13.142797                149              1.3915
13   1950    NaN   26.452797                160              1.5246
14   1950    NaN   44.602797                175              1.7061
15   1950    NaN   37.342797                169              1.6335
16   1950    NaN   25.242797                159              1.5125
17   1950    NaN   54.282797                183              1.8029
18   1950    NaN   79.692797                204              2.0570
19   1950    NaN   79.692797                204              2.0570
20   1950    NaN   65.172797                192              1.9118
21   1950    NaN   34.922797                167              1.6093
22   1950    NaN   11.932797                148              1.3794
23   1950    NaN   43.392797                174              1.6940
24   1951    NaN   49.442797                179              1.7545
25   1951    NaN   55.492797                184              1.8150
26   1951    NaN   89.372797                212              2.1538
27   1951    NaN   71.222797                197              1.9723
28   1951    NaN   82.112797                206              2.0812
29   1951    NaN   89.372797                212              2.1538
30   1951    NaN  114.782797                233              2.4079
31   1951    NaN  114.782797                233              2.4079
32   1951    NaN   96.632797                218              2.2264
33   1951    NaN   70.012797                196              1.9602
34   1951    NaN   50.652797                180              1.7666
35   1951    NaN   74.852797                200              2.0086
36   1952    NaN   80.902797                205              2.0691
37   1952    NaN   91.792797                214              2.1780
38   1952    NaN  107.522797                227              2.3353
39   1952    NaN   93.002797                215              2.1901
40   1952    NaN   95.422797                217              2.2143
41   1952    NaN  137.772797                252              2.6378
42   1952    NaN  152.292797                264              2.7830
43   1952    NaN  166.812797                276              2.9282
44   1952    NaN  126.882797                243              2.5289
45   1952    NaN  105.102797                225              2.3111
46   1952    NaN   82.112797                206              2.0812
47   1952    NaN  108.732797                228              2.3474
48   1953    NaN  111.152797                230              2.3716
49   1953    NaN  111.152797                230              2.3716
50   1953    NaN  159.552797                270              2.8556
51   1953    NaN  158.342797                269              2.8435
52   1953    NaN  151.082797                263              2.7709
53   1953    NaN  168.022797                277              2.9403
54   1953    NaN  193.432797                298              3.1944
55   1953    NaN  203.112797                306              3.2912
56   1953    NaN  160.762797                271              2.8677
57   1953    NaN  129.302797                245              2.5531
58   1953    NaN   91.792797                214              2.1780
59   1953    NaN  117.202797                235              2.4321
60   1954    NaN  120.832797                238              2.4684
61   1954    NaN  101.472797                222              2.2748
62   1954    NaN  158.342797                269              2.8435
63   1954    NaN  148.662797                261              2.7467
64   1954    NaN  157.132797                268              2.8314
65   1954    NaN  193.432797                298              3.1944
66   1954    NaN  239.412797                336              3.6542
67   1954    NaN  228.522797                327              3.5453
68   1954    NaN  187.382797                293              3.1339
69   1954    NaN  151.082797                263              2.7709
70   1954    NaN  119.622797                237              2.4563
71   1954    NaN  151.082797                263              2.7709
72   1955    NaN  166.812797                276              2.9282
73   1955    NaN  155.922797                267              2.8193
74   1955    NaN  197.062797                301              3.2307
75   1955    NaN  199.482797                303              3.2549
76   1955    NaN  200.692797                304              3.2670
77   1955    NaN  255.142797                349              3.8115
78   1955    NaN  314.432797                398              4.4044
79   1955    NaN  293.862797                381              4.1987
80   1955    NaN  251.512797                346              3.7752
81   1955    NaN  205.532797                308              3.3154
82   1955    NaN  160.762797                271              2.8677
83   1955    NaN  210.372797                312              3.3638
84   1956    NaN  217.632797                318              3.4364
85   1956    NaN  209.162797                311              3.3517
86   1956    NaN  257.562797                351              3.8357
87   1956    NaN  252.722797                347              3.7873
88   1956    NaN  258.772797                352              3.8478
89   1956    NaN  326.532797                408              4.5254
90   1956    NaN  373.722797                447              4.9973
91   1956    NaN  364.042797                439              4.9005
92   1956    NaN  303.542797                389              4.2955
93   1956    NaN  244.252797                340              3.7026
94   1956    NaN  201.902797                305              3.2791
95   1956    NaN  244.252797                340              3.7026
96   1957    NaN  255.142797                349              3.8115
97   1957    NaN  238.202797                335              3.6421
98   1957    NaN  304.752797                390              4.3076
99   1957    NaN  295.072797                382              4.2108
100  1957    NaN  303.542797                389              4.2955
101  1957    NaN  384.612797                456              5.1062
102  1957    NaN  436.642797                499              5.6265
103  1957    NaN  439.062797                501              5.6507
104  1957    NaN  362.832797                438              4.8884
105  1957    NaN  293.862797                381              4.1987
106  1957    NaN  243.042797                339              3.6905
107  1957    NaN  280.552797                370              4.0656
108  1958    NaN  285.392797                374              4.1140
109  1958    NaN  258.772797                352              3.8478
110  1958    NaN  312.012797                396              4.3802
111  1958    NaN  295.072797                382              4.2108
112  1958    NaN  313.222797                397              4.3923
113  1958    NaN  400.342797                469              5.2635
114  1958    NaN  468.102797                525              5.9411
115  1958    NaN  485.042797                539              6.1105
116  1958    NaN  362.832797                438              4.8884
117  1958    NaN  308.382797                393              4.3439
118  1958    NaN  249.092797                344              3.7510
119  1958    NaN  281.762797                371              4.0777
120  1959    NaN  309.592797                394              4.3560
121  1959    NaN  287.812797                376              4.1382
122  1959    NaN  365.252797                440              4.9126
123  1959    NaN  353.152797                430              4.7916
124  1959    NaN  382.192797                454              5.0820
125  1959    NaN  445.112797                506              5.7112
126  1959    NaN  537.072797                582              6.6308
127  1959    NaN  550.382797                593              6.7639
128  1959    NaN  434.222797                497              5.6023
129  1959    NaN  366.462797                441              4.9247
130  1959    NaN  312.012797                396              4.3802
131  1959    NaN  364.042797                439              4.9005
132  1960    NaN  378.562797                451              5.0457
133  1960    NaN  347.102797                425              4.7311
134  1960    NaN  380.982797                453              5.0699
135  1960    NaN  431.802797                495              5.5781
136  1960    NaN  445.112797                506              5.7112
137  1960    NaN  521.342797                569              6.4735
138  1960    NaN  626.612797                656              7.5262
139  1960    NaN  607.252797                640              7.3326
140  1960    NaN  488.672797                542              6.1468
141  1960    NaN  431.802797                495              5.5781
142  1960    NaN  345.892797                424              4.7190
143  1960    NaN  396.712797                466              5.2272

In [140]:
pivot_avg = flights.pivot_table(
    index="year",        # rows
    columns="month",     # columns
    values="passengers", # column to aggregate
    aggfunc="mean"       # average passengers
)

In [136]:
pivot_avg

Empty DataFrame
Columns: []
Index: []

In [ ]:
# it shows frequencies or aggregated values for combinations of two (or more) categorical variables. 😎
What is a crosstab?
pd.crosstab() creates a table of counts (or sums) of two categorical variables.
Rows = one category, Columns = another category
Can also include aggregation (values + aggfunc)

import pandas as pd

pd.crosstab(flights["year"], flights["month"])

In [138]:
# Crosstab of year and month 

pd.crosstab(flights["year"],flights["month"])
flights

     year  month  passengers  passengers_growth  passengers_per_100
0    1949    NaN    9.512797                146              1.3552
1    1949    NaN   16.772797                152              1.4278
2    1949    NaN   33.712797                166              1.5972
3    1949    NaN   30.082797                163              1.5609
4    1949    NaN   20.402797                155              1.4641
5    1949    NaN   37.342797                169              1.6335
6    1949    NaN   53.072797                182              1.7908
7    1949    NaN   53.072797                182              1.7908
8    1949    NaN   38.552797                170              1.6456
9    1949    NaN   17.982797                153              1.4399
10   1949    NaN   -0.167203                138              1.2584
11   1949    NaN   16.772797                152              1.4278
12   1950    NaN   13.142797                149              1.3915
13   1950    NaN   26.452797                160              1.5246
14   1950    NaN   44.602797                175              1.7061
15   1950    NaN   37.342797                169              1.6335
16   1950    NaN   25.242797                159              1.5125
17   1950    NaN   54.282797                183              1.8029
18   1950    NaN   79.692797                204              2.0570
19   1950    NaN   79.692797                204              2.0570
20   1950    NaN   65.172797                192              1.9118
21   1950    NaN   34.922797                167              1.6093
22   1950    NaN   11.932797                148              1.3794
23   1950    NaN   43.392797                174              1.6940
24   1951    NaN   49.442797                179              1.7545
25   1951    NaN   55.492797                184              1.8150
26   1951    NaN   89.372797                212              2.1538
27   1951    NaN   71.222797                197              1.9723
28   1951    NaN   82.112797                206              2.0812
29   1951    NaN   89.372797                212              2.1538
30   1951    NaN  114.782797                233              2.4079
31   1951    NaN  114.782797                233              2.4079
32   1951    NaN   96.632797                218              2.2264
33   1951    NaN   70.012797                196              1.9602
34   1951    NaN   50.652797                180              1.7666
35   1951    NaN   74.852797                200              2.0086
36   1952    NaN   80.902797                205              2.0691
37   1952    NaN   91.792797                214              2.1780
38   1952    NaN  107.522797                227              2.3353
39   1952    NaN   93.002797                215              2.1901
40   1952    NaN   95.422797                217              2.2143
41   1952    NaN  137.772797                252              2.6378
42   1952    NaN  152.292797                264              2.7830
43   1952    NaN  166.812797                276              2.9282
44   1952    NaN  126.882797                243              2.5289
45   1952    NaN  105.102797                225              2.3111
46   1952    NaN   82.112797                206              2.0812
47   1952    NaN  108.732797                228              2.3474
48   1953    NaN  111.152797                230              2.3716
49   1953    NaN  111.152797                230              2.3716
50   1953    NaN  159.552797                270              2.8556
51   1953    NaN  158.342797                269              2.8435
52   1953    NaN  151.082797                263              2.7709
53   1953    NaN  168.022797                277              2.9403
54   1953    NaN  193.432797                298              3.1944
55   1953    NaN  203.112797                306              3.2912
56   1953    NaN  160.762797                271              2.8677
57   1953    NaN  129.302797                245              2.5531
58   1953    NaN   91.792797                214              2.1780
59   1953    NaN  117.202797                235              2.4321
60   1954    NaN  120.832797                238              2.4684
61   1954    NaN  101.472797                222              2.2748
62   1954    NaN  158.342797                269              2.8435
63   1954    NaN  148.662797                261              2.7467
64   1954    NaN  157.132797                268              2.8314
65   1954    NaN  193.432797                298              3.1944
66   1954    NaN  239.412797                336              3.6542
67   1954    NaN  228.522797                327              3.5453
68   1954    NaN  187.382797                293              3.1339
69   1954    NaN  151.082797                263              2.7709
70   1954    NaN  119.622797                237              2.4563
71   1954    NaN  151.082797                263              2.7709
72   1955    NaN  166.812797                276              2.9282
73   1955    NaN  155.922797                267              2.8193
74   1955    NaN  197.062797                301              3.2307
75   1955    NaN  199.482797                303              3.2549
76   1955    NaN  200.692797                304              3.2670
77   1955    NaN  255.142797                349              3.8115
78   1955    NaN  314.432797                398              4.4044
79   1955    NaN  293.862797                381              4.1987
80   1955    NaN  251.512797                346              3.7752
81   1955    NaN  205.532797                308              3.3154
82   1955    NaN  160.762797                271              2.8677
83   1955    NaN  210.372797                312              3.3638
84   1956    NaN  217.632797                318              3.4364
85   1956    NaN  209.162797                311              3.3517
86   1956    NaN  257.562797                351              3.8357
87   1956    NaN  252.722797                347              3.7873
88   1956    NaN  258.772797                352              3.8478
89   1956    NaN  326.532797                408              4.5254
90   1956    NaN  373.722797                447              4.9973
91   1956    NaN  364.042797                439              4.9005
92   1956    NaN  303.542797                389              4.2955
93   1956    NaN  244.252797                340              3.7026
94   1956    NaN  201.902797                305              3.2791
95   1956    NaN  244.252797                340              3.7026
96   1957    NaN  255.142797                349              3.8115
97   1957    NaN  238.202797                335              3.6421
98   1957    NaN  304.752797                390              4.3076
99   1957    NaN  295.072797                382              4.2108
100  1957    NaN  303.542797                389              4.2955
101  1957    NaN  384.612797                456              5.1062
102  1957    NaN  436.642797                499              5.6265
103  1957    NaN  439.062797                501              5.6507
104  1957    NaN  362.832797                438              4.8884
105  1957    NaN  293.862797                381              4.1987
106  1957    NaN  243.042797                339              3.6905
107  1957    NaN  280.552797                370              4.0656
108  1958    NaN  285.392797                374              4.1140
109  1958    NaN  258.772797                352              3.8478
110  1958    NaN  312.012797                396              4.3802
111  1958    NaN  295.072797                382              4.2108
112  1958    NaN  313.222797                397              4.3923
113  1958    NaN  400.342797                469              5.2635
114  1958    NaN  468.102797                525              5.9411
115  1958    NaN  485.042797                539              6.1105
116  1958    NaN  362.832797                438              4.8884
117  1958    NaN  308.382797                393              4.3439
118  1958    NaN  249.092797                344              3.7510
119  1958    NaN  281.762797                371              4.0777
120  1959    NaN  309.592797                394              4.3560
121  1959    NaN  287.812797                376              4.1382
122  1959    NaN  365.252797                440              4.9126
123  1959    NaN  353.152797                430              4.7916
124  1959    NaN  382.192797                454              5.0820
125  1959    NaN  445.112797                506              5.7112
126  1959    NaN  537.072797                582              6.6308
127  1959    NaN  550.382797                593              6.7639
128  1959    NaN  434.222797                497              5.6023
129  1959    NaN  366.462797                441              4.9247
130  1959    NaN  312.012797                396              4.3802
131  1959    NaN  364.042797                439              4.9005
132  1960    NaN  378.562797                451              5.0457
133  1960    NaN  347.102797                425              4.7311
134  1960    NaN  380.982797                453              5.0699
135  1960    NaN  431.802797                495              5.5781
136  1960    NaN  445.112797                506              5.7112
137  1960    NaN  521.342797                569              6.4735
138  1960    NaN  626.612797                656              7.5262
139  1960    NaN  607.252797                640              7.3326
140  1960    NaN  488.672797                542              6.1468
141  1960    NaN  431.802797                495              5.5781
142  1960    NaN  345.892797                424              4.7190
143  1960    NaN  396.712797                466              5.2272

In [142]:
month_map = {"Jan":1, "Feb":2, "Mar":3, "Apr":4,
             "May":5, "Jun":6, "Jul":7, "Aug":8,
             "Sep":9, "Oct":10, "Nov":11, "Dec":12}

# Apply mapping; missing or incorrect values become NaN
flights["month"] = flights["month"].map(month_map)

In [143]:
flights

     year  month  passengers  passengers_growth  passengers_per_100
0    1949    NaN    9.512797                146              1.3552
1    1949    NaN   16.772797                152              1.4278
2    1949    NaN   33.712797                166              1.5972
3    1949    NaN   30.082797                163              1.5609
4    1949    NaN   20.402797                155              1.4641
5    1949    NaN   37.342797                169              1.6335
6    1949    NaN   53.072797                182              1.7908
7    1949    NaN   53.072797                182              1.7908
8    1949    NaN   38.552797                170              1.6456
9    1949    NaN   17.982797                153              1.4399
10   1949    NaN   -0.167203                138              1.2584
11   1949    NaN   16.772797                152              1.4278
12   1950    NaN   13.142797                149              1.3915
13   1950    NaN   26.452797                160              1.5246
14   1950    NaN   44.602797                175              1.7061
15   1950    NaN   37.342797                169              1.6335
16   1950    NaN   25.242797                159              1.5125
17   1950    NaN   54.282797                183              1.8029
18   1950    NaN   79.692797                204              2.0570
19   1950    NaN   79.692797                204              2.0570
20   1950    NaN   65.172797                192              1.9118
21   1950    NaN   34.922797                167              1.6093
22   1950    NaN   11.932797                148              1.3794
23   1950    NaN   43.392797                174              1.6940
24   1951    NaN   49.442797                179              1.7545
25   1951    NaN   55.492797                184              1.8150
26   1951    NaN   89.372797                212              2.1538
27   1951    NaN   71.222797                197              1.9723
28   1951    NaN   82.112797                206              2.0812
29   1951    NaN   89.372797                212              2.1538
30   1951    NaN  114.782797                233              2.4079
31   1951    NaN  114.782797                233              2.4079
32   1951    NaN   96.632797                218              2.2264
33   1951    NaN   70.012797                196              1.9602
34   1951    NaN   50.652797                180              1.7666
35   1951    NaN   74.852797                200              2.0086
36   1952    NaN   80.902797                205              2.0691
37   1952    NaN   91.792797                214              2.1780
38   1952    NaN  107.522797                227              2.3353
39   1952    NaN   93.002797                215              2.1901
40   1952    NaN   95.422797                217              2.2143
41   1952    NaN  137.772797                252              2.6378
42   1952    NaN  152.292797                264              2.7830
43   1952    NaN  166.812797                276              2.9282
44   1952    NaN  126.882797                243              2.5289
45   1952    NaN  105.102797                225              2.3111
46   1952    NaN   82.112797                206              2.0812
47   1952    NaN  108.732797                228              2.3474
48   1953    NaN  111.152797                230              2.3716
49   1953    NaN  111.152797                230              2.3716
50   1953    NaN  159.552797                270              2.8556
51   1953    NaN  158.342797                269              2.8435
52   1953    NaN  151.082797                263              2.7709
53   1953    NaN  168.022797                277              2.9403
54   1953    NaN  193.432797                298              3.1944
55   1953    NaN  203.112797                306              3.2912
56   1953    NaN  160.762797                271              2.8677
57   1953    NaN  129.302797                245              2.5531
58   1953    NaN   91.792797                214              2.1780
59   1953    NaN  117.202797                235              2.4321
60   1954    NaN  120.832797                238              2.4684
61   1954    NaN  101.472797                222              2.2748
62   1954    NaN  158.342797                269              2.8435
63   1954    NaN  148.662797                261              2.7467
64   1954    NaN  157.132797                268              2.8314
65   1954    NaN  193.432797                298              3.1944
66   1954    NaN  239.412797                336              3.6542
67   1954    NaN  228.522797                327              3.5453
68   1954    NaN  187.382797                293              3.1339
69   1954    NaN  151.082797                263              2.7709
70   1954    NaN  119.622797                237              2.4563
71   1954    NaN  151.082797                263              2.7709
72   1955    NaN  166.812797                276              2.9282
73   1955    NaN  155.922797                267              2.8193
74   1955    NaN  197.062797                301              3.2307
75   1955    NaN  199.482797                303              3.2549
76   1955    NaN  200.692797                304              3.2670
77   1955    NaN  255.142797                349              3.8115
78   1955    NaN  314.432797                398              4.4044
79   1955    NaN  293.862797                381              4.1987
80   1955    NaN  251.512797                346              3.7752
81   1955    NaN  205.532797                308              3.3154
82   1955    NaN  160.762797                271              2.8677
83   1955    NaN  210.372797                312              3.3638
84   1956    NaN  217.632797                318              3.4364
85   1956    NaN  209.162797                311              3.3517
86   1956    NaN  257.562797                351              3.8357
87   1956    NaN  252.722797                347              3.7873
88   1956    NaN  258.772797                352              3.8478
89   1956    NaN  326.532797                408              4.5254
90   1956    NaN  373.722797                447              4.9973
91   1956    NaN  364.042797                439              4.9005
92   1956    NaN  303.542797                389              4.2955
93   1956    NaN  244.252797                340              3.7026
94   1956    NaN  201.902797                305              3.2791
95   1956    NaN  244.252797                340              3.7026
96   1957    NaN  255.142797                349              3.8115
97   1957    NaN  238.202797                335              3.6421
98   1957    NaN  304.752797                390              4.3076
99   1957    NaN  295.072797                382              4.2108
100  1957    NaN  303.542797                389              4.2955
101  1957    NaN  384.612797                456              5.1062
102  1957    NaN  436.642797                499              5.6265
103  1957    NaN  439.062797                501              5.6507
104  1957    NaN  362.832797                438              4.8884
105  1957    NaN  293.862797                381              4.1987
106  1957    NaN  243.042797                339              3.6905
107  1957    NaN  280.552797                370              4.0656
108  1958    NaN  285.392797                374              4.1140
109  1958    NaN  258.772797                352              3.8478
110  1958    NaN  312.012797                396              4.3802
111  1958    NaN  295.072797                382              4.2108
112  1958    NaN  313.222797                397              4.3923
113  1958    NaN  400.342797                469              5.2635
114  1958    NaN  468.102797                525              5.9411
115  1958    NaN  485.042797                539              6.1105
116  1958    NaN  362.832797                438              4.8884
117  1958    NaN  308.382797                393              4.3439
118  1958    NaN  249.092797                344              3.7510
119  1958    NaN  281.762797                371              4.0777
120  1959    NaN  309.592797                394              4.3560
121  1959    NaN  287.812797                376              4.1382
122  1959    NaN  365.252797                440              4.9126
123  1959    NaN  353.152797                430              4.7916
124  1959    NaN  382.192797                454              5.0820
125  1959    NaN  445.112797                506              5.7112
126  1959    NaN  537.072797                582              6.6308
127  1959    NaN  550.382797                593              6.7639
128  1959    NaN  434.222797                497              5.6023
129  1959    NaN  366.462797                441              4.9247
130  1959    NaN  312.012797                396              4.3802
131  1959    NaN  364.042797                439              4.9005
132  1960    NaN  378.562797                451              5.0457
133  1960    NaN  347.102797                425              4.7311
134  1960    NaN  380.982797                453              5.0699
135  1960    NaN  431.802797                495              5.5781
136  1960    NaN  445.112797                506              5.7112
137  1960    NaN  521.342797                569              6.4735
138  1960    NaN  626.612797                656              7.5262
139  1960    NaN  607.252797                640              7.3326
140  1960    NaN  488.672797                542              6.1468
141  1960    NaN  431.802797                495              5.5781
142  1960    NaN  345.892797                424              4.7190
143  1960    NaN  396.712797                466              5.2272

In [146]:
flights["month"] = flights["month"].fillna(month_map)

In [147]:
flights

     year  month  passengers  passengers_growth  passengers_per_100
0    1949    0.0    9.512797                146              1.3552
1    1949    0.0   16.772797                152              1.4278
2    1949    0.0   33.712797                166              1.5972
3    1949    0.0   30.082797                163              1.5609
4    1949    0.0   20.402797                155              1.4641
5    1949    0.0   37.342797                169              1.6335
6    1949    0.0   53.072797                182              1.7908
7    1949    0.0   53.072797                182              1.7908
8    1949    0.0   38.552797                170              1.6456
9    1949    0.0   17.982797                153              1.4399
10   1949    0.0   -0.167203                138              1.2584
11   1949    0.0   16.772797                152              1.4278
12   1950    0.0   13.142797                149              1.3915
13   1950    0.0   26.452797                160              1.5246
14   1950    0.0   44.602797                175              1.7061
15   1950    0.0   37.342797                169              1.6335
16   1950    0.0   25.242797                159              1.5125
17   1950    0.0   54.282797                183              1.8029
18   1950    0.0   79.692797                204              2.0570
19   1950    0.0   79.692797                204              2.0570
20   1950    0.0   65.172797                192              1.9118
21   1950    0.0   34.922797                167              1.6093
22   1950    0.0   11.932797                148              1.3794
23   1950    0.0   43.392797                174              1.6940
24   1951    0.0   49.442797                179              1.7545
25   1951    0.0   55.492797                184              1.8150
26   1951    0.0   89.372797                212              2.1538
27   1951    0.0   71.222797                197              1.9723
28   1951    0.0   82.112797                206              2.0812
29   1951    0.0   89.372797                212              2.1538
30   1951    0.0  114.782797                233              2.4079
31   1951    0.0  114.782797                233              2.4079
32   1951    0.0   96.632797                218              2.2264
33   1951    0.0   70.012797                196              1.9602
34   1951    0.0   50.652797                180              1.7666
35   1951    0.0   74.852797                200              2.0086
36   1952    0.0   80.902797                205              2.0691
37   1952    0.0   91.792797                214              2.1780
38   1952    0.0  107.522797                227              2.3353
39   1952    0.0   93.002797                215              2.1901
40   1952    0.0   95.422797                217              2.2143
41   1952    0.0  137.772797                252              2.6378
42   1952    0.0  152.292797                264              2.7830
43   1952    0.0  166.812797                276              2.9282
44   1952    0.0  126.882797                243              2.5289
45   1952    0.0  105.102797                225              2.3111
46   1952    0.0   82.112797                206              2.0812
47   1952    0.0  108.732797                228              2.3474
48   1953    0.0  111.152797                230              2.3716
49   1953    0.0  111.152797                230              2.3716
50   1953    0.0  159.552797                270              2.8556
51   1953    0.0  158.342797                269              2.8435
52   1953    0.0  151.082797                263              2.7709
53   1953    0.0  168.022797                277              2.9403
54   1953    0.0  193.432797                298              3.1944
55   1953    0.0  203.112797                306              3.2912
56   1953    0.0  160.762797                271              2.8677
57   1953    0.0  129.302797                245              2.5531
58   1953    0.0   91.792797                214              2.1780
59   1953    0.0  117.202797                235              2.4321
60   1954    0.0  120.832797                238              2.4684
61   1954    0.0  101.472797                222              2.2748
62   1954    0.0  158.342797                269              2.8435
63   1954    0.0  148.662797                261              2.7467
64   1954    0.0  157.132797                268              2.8314
65   1954    0.0  193.432797                298              3.1944
66   1954    0.0  239.412797                336              3.6542
67   1954    0.0  228.522797                327              3.5453
68   1954    0.0  187.382797                293              3.1339
69   1954    0.0  151.082797                263              2.7709
70   1954    0.0  119.622797                237              2.4563
71   1954    0.0  151.082797                263              2.7709
72   1955    0.0  166.812797                276              2.9282
73   1955    0.0  155.922797                267              2.8193
74   1955    0.0  197.062797                301              3.2307
75   1955    0.0  199.482797                303              3.2549
76   1955    0.0  200.692797                304              3.2670
77   1955    0.0  255.142797                349              3.8115
78   1955    0.0  314.432797                398              4.4044
79   1955    0.0  293.862797                381              4.1987
80   1955    0.0  251.512797                346              3.7752
81   1955    0.0  205.532797                308              3.3154
82   1955    0.0  160.762797                271              2.8677
83   1955    0.0  210.372797                312              3.3638
84   1956    0.0  217.632797                318              3.4364
85   1956    0.0  209.162797                311              3.3517
86   1956    0.0  257.562797                351              3.8357
87   1956    0.0  252.722797                347              3.7873
88   1956    0.0  258.772797                352              3.8478
89   1956    0.0  326.532797                408              4.5254
90   1956    0.0  373.722797                447              4.9973
91   1956    0.0  364.042797                439              4.9005
92   1956    0.0  303.542797                389              4.2955
93   1956    0.0  244.252797                340              3.7026
94   1956    0.0  201.902797                305              3.2791
95   1956    0.0  244.252797                340              3.7026
96   1957    0.0  255.142797                349              3.8115
97   1957    0.0  238.202797                335              3.6421
98   1957    0.0  304.752797                390              4.3076
99   1957    0.0  295.072797                382              4.2108
100  1957    0.0  303.542797                389              4.2955
101  1957    0.0  384.612797                456              5.1062
102  1957    0.0  436.642797                499              5.6265
103  1957    0.0  439.062797                501              5.6507
104  1957    0.0  362.832797                438              4.8884
105  1957    0.0  293.862797                381              4.1987
106  1957    0.0  243.042797                339              3.6905
107  1957    0.0  280.552797                370              4.0656
108  1958    0.0  285.392797                374              4.1140
109  1958    0.0  258.772797                352              3.8478
110  1958    0.0  312.012797                396              4.3802
111  1958    0.0  295.072797                382              4.2108
112  1958    0.0  313.222797                397              4.3923
113  1958    0.0  400.342797                469              5.2635
114  1958    0.0  468.102797                525              5.9411
115  1958    0.0  485.042797                539              6.1105
116  1958    0.0  362.832797                438              4.8884
117  1958    0.0  308.382797                393              4.3439
118  1958    0.0  249.092797                344              3.7510
119  1958    0.0  281.762797                371              4.0777
120  1959    0.0  309.592797                394              4.3560
121  1959    0.0  287.812797                376              4.1382
122  1959    0.0  365.252797                440              4.9126
123  1959    0.0  353.152797                430              4.7916
124  1959    0.0  382.192797                454              5.0820
125  1959    0.0  445.112797                506              5.7112
126  1959    0.0  537.072797                582              6.6308
127  1959    0.0  550.382797                593              6.7639
128  1959    0.0  434.222797                497              5.6023
129  1959    0.0  366.462797                441              4.9247
130  1959    0.0  312.012797                396              4.3802
131  1959    0.0  364.042797                439              4.9005
132  1960    0.0  378.562797                451              5.0457
133  1960    0.0  347.102797                425              4.7311
134  1960    0.0  380.982797                453              5.0699
135  1960    0.0  431.802797                495              5.5781
136  1960    0.0  445.112797                506              5.7112
137  1960    0.0  521.342797                569              6.4735
138  1960    0.0  626.612797                656              7.5262
139  1960    0.0  607.252797                640              7.3326
140  1960    0.0  488.672797                542              6.1468
141  1960    0.0  431.802797                495              5.5781
142  1960    0.0  345.892797                424              4.7190
143  1960    0.0  396.712797                466              5.2272

In [148]:
import pandas as pd 
import seaborn as sns
flights=sns.load_dataset("flights")
flights

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
5    1949   Jun         135
6    1949   Jul         148
7    1949   Aug         148
8    1949   Sep         136
9    1949   Oct         119
10   1949   Nov         104
11   1949   Dec         118
12   1950   Jan         115
13   1950   Feb         126
14   1950   Mar         141
15   1950   Apr         135
16   1950   May         125
17   1950   Jun         149
18   1950   Jul         170
19   1950   Aug         170
20   1950   Sep         158
21   1950   Oct         133
22   1950   Nov         114
23   1950   Dec         140
24   1951   Jan         145
25   1951   Feb         150
26   1951   Mar         178
27   1951   Apr         163
28   1951   May         172
29   1951   Jun         178
30   1951   Jul         199
31   1951   Aug         199
32   1951   Sep         184
33   1951   Oct         162
34   1951   Nov         146
35   1951   Dec         166
36   1952   Jan         171
37   1952   Feb         180
38   1952   Mar         193
39   1952   Apr         181
40   1952   May         183
41   1952   Jun         218
42   1952   Jul         230
43   1952   Aug         242
44   1952   Sep         209
45   1952   Oct         191
46   1952   Nov         172
47   1952   Dec         194
48   1953   Jan         196
49   1953   Feb         196
50   1953   Mar         236
51   1953   Apr         235
52   1953   May         229
53   1953   Jun         243
54   1953   Jul         264
55   1953   Aug         272
56   1953   Sep         237
57   1953   Oct         211
58   1953   Nov         180
59   1953   Dec         201
60   1954   Jan         204
61   1954   Feb         188
62   1954   Mar         235
63   1954   Apr         227
64   1954   May         234
65   1954   Jun         264
66   1954   Jul         302
67   1954   Aug         293
68   1954   Sep         259
69   1954   Oct         229
70   1954   Nov         203
71   1954   Dec         229
72   1955   Jan         242
73   1955   Feb         233
74   1955   Mar         267
75   1955   Apr         269
76   1955   May         270
77   1955   Jun         315
78   1955   Jul         364
79   1955   Aug         347
80   1955   Sep         312
81   1955   Oct         274
82   1955   Nov         237
83   1955   Dec         278
84   1956   Jan         284
85   1956   Feb         277
86   1956   Mar         317
87   1956   Apr         313
88   1956   May         318
89   1956   Jun         374
90   1956   Jul         413
91   1956   Aug         405
92   1956   Sep         355
93   1956   Oct         306
94   1956   Nov         271
95   1956   Dec         306
96   1957   Jan         315
97   1957   Feb         301
98   1957   Mar         356
99   1957   Apr         348
100  1957   May         355
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
104  1957   Sep         404
105  1957   Oct         347
106  1957   Nov         305
107  1957   Dec         336
108  1958   Jan         340
109  1958   Feb         318
110  1958   Mar         362
111  1958   Apr         348
112  1958   May         363
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
116  1958   Sep         404
117  1958   Oct         359
118  1958   Nov         310
119  1958   Dec         337
120  1959   Jan         360
121  1959   Feb         342
122  1959   Mar         406
123  1959   Apr         396
124  1959   May         420
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
129  1959   Oct         407
130  1959   Nov         362
131  1959   Dec         405
132  1960   Jan         417
133  1960   Feb         391
134  1960   Mar         419
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

In [150]:
pivot_agg=flights.pivot_table(
    index="year",        # rows
    columns="month",     # columns
    values="passengers", # data to aggregate
    aggfunc=["mean", "max"]
)
pivot_agg

C:\Users\HP\AppData\Local\Temp\ipykernel_17076\1448881790.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_agg=flights.pivot_table(
C:\Users\HP\AppData\Local\Temp\ipykernel_17076\1448881790.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_agg=flights.pivot_table(

        mean                                                                 \
month    Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct
year
1949   112.0  118.0  132.0  129.0  121.0  135.0  148.0  148.0  136.0  119.0
1950   115.0  126.0  141.0  135.0  125.0  149.0  170.0  170.0  158.0  133.0
1951   145.0  150.0  178.0  163.0  172.0  178.0  199.0  199.0  184.0  162.0
1952   171.0  180.0  193.0  181.0  183.0  218.0  230.0  242.0  209.0  191.0
1953   196.0  196.0  236.0  235.0  229.0  243.0  264.0  272.0  237.0  211.0
1954   204.0  188.0  235.0  227.0  234.0  264.0  302.0  293.0  259.0  229.0
1955   242.0  233.0  267.0  269.0  270.0  315.0  364.0  347.0  312.0  274.0
1956   284.0  277.0  317.0  313.0  318.0  374.0  413.0  405.0  355.0  306.0
1957   315.0  301.0  356.0  348.0  355.0  422.0  465.0  467.0  404.0  347.0
1958   340.0  318.0  362.0  348.0  363.0  435.0  491.0  505.0  404.0  359.0
1959   360.0  342.0  406.0  396.0  420.0  472.0  548.0  559.0  463.0  407.0
1960   417.0  391.0  419.0  461.0  472.0  535.0  622.0  606.0  508.0  461.0

       ...  max
month  ...  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year   ...
1949   ...  132  129  121  135  148  148  136  119  104  118
1950   ...  141  135  125  149  170  170  158  133  114  140
1951   ...  178  163  172  178  199  199  184  162  146  166
1952   ...  193  181  183  218  230  242  209  191  172  194
1953   ...  236  235  229  243  264  272  237  211  180  201
1954   ...  235  227  234  264  302  293  259  229  203  229
1955   ...  267  269  270  315  364  347  312  274  237  278
1956   ...  317  313  318  374  413  405  355  306  271  306
1957   ...  356  348  355  422  465  467  404  347  305  336
1958   ...  362  348  363  435  491  505  404  359  310  337
1959   ...  406  396  420  472  548  559  463  407  362  405
1960   ...  419  461  472  535  622  606  508  461  390  432

[12 rows x 24 columns]

In [151]:
flights.rename(columns={
    "year": "Year",
    "month": "Month",
    "passengers": "Passengers"
}, inplace=True)

In [152]:
flights

     Year Month  Passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
5    1949   Jun         135
6    1949   Jul         148
7    1949   Aug         148
8    1949   Sep         136
9    1949   Oct         119
10   1949   Nov         104
11   1949   Dec         118
12   1950   Jan         115
13   1950   Feb         126
14   1950   Mar         141
15   1950   Apr         135
16   1950   May         125
17   1950   Jun         149
18   1950   Jul         170
19   1950   Aug         170
20   1950   Sep         158
21   1950   Oct         133
22   1950   Nov         114
23   1950   Dec         140
24   1951   Jan         145
25   1951   Feb         150
26   1951   Mar         178
27   1951   Apr         163
28   1951   May         172
29   1951   Jun         178
30   1951   Jul         199
31   1951   Aug         199
32   1951   Sep         184
33   1951   Oct         162
34   1951   Nov         146
35   1951   Dec         166
36   1952   Jan         171
37   1952   Feb         180
38   1952   Mar         193
39   1952   Apr         181
40   1952   May         183
41   1952   Jun         218
42   1952   Jul         230
43   1952   Aug         242
44   1952   Sep         209
45   1952   Oct         191
46   1952   Nov         172
47   1952   Dec         194
48   1953   Jan         196
49   1953   Feb         196
50   1953   Mar         236
51   1953   Apr         235
52   1953   May         229
53   1953   Jun         243
54   1953   Jul         264
55   1953   Aug         272
56   1953   Sep         237
57   1953   Oct         211
58   1953   Nov         180
59   1953   Dec         201
60   1954   Jan         204
61   1954   Feb         188
62   1954   Mar         235
63   1954   Apr         227
64   1954   May         234
65   1954   Jun         264
66   1954   Jul         302
67   1954   Aug         293
68   1954   Sep         259
69   1954   Oct         229
70   1954   Nov         203
71   1954   Dec         229
72   1955   Jan         242
73   1955   Feb         233
74   1955   Mar         267
75   1955   Apr         269
76   1955   May         270
77   1955   Jun         315
78   1955   Jul         364
79   1955   Aug         347
80   1955   Sep         312
81   1955   Oct         274
82   1955   Nov         237
83   1955   Dec         278
84   1956   Jan         284
85   1956   Feb         277
86   1956   Mar         317
87   1956   Apr         313
88   1956   May         318
89   1956   Jun         374
90   1956   Jul         413
91   1956   Aug         405
92   1956   Sep         355
93   1956   Oct         306
94   1956   Nov         271
95   1956   Dec         306
96   1957   Jan         315
97   1957   Feb         301
98   1957   Mar         356
99   1957   Apr         348
100  1957   May         355
101  1957   Jun         422
102  1957   Jul         465
103  1957   Aug         467
104  1957   Sep         404
105  1957   Oct         347
106  1957   Nov         305
107  1957   Dec         336
108  1958   Jan         340
109  1958   Feb         318
110  1958   Mar         362
111  1958   Apr         348
112  1958   May         363
113  1958   Jun         435
114  1958   Jul         491
115  1958   Aug         505
116  1958   Sep         404
117  1958   Oct         359
118  1958   Nov         310
119  1958   Dec         337
120  1959   Jan         360
121  1959   Feb         342
122  1959   Mar         406
123  1959   Apr         396
124  1959   May         420
125  1959   Jun         472
126  1959   Jul         548
127  1959   Aug         559
128  1959   Sep         463
129  1959   Oct         407
130  1959   Nov         362
131  1959   Dec         405
132  1960   Jan         417
133  1960   Feb         391
134  1960   Mar         419
135  1960   Apr         461
136  1960   May         472
137  1960   Jun         535
138  1960   Jul         622
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

In [155]:
flights=flights[["Month", "Year", "Passengers"]]
flights

    Month  Year  Passengers
0     Jan  1949         112
1     Feb  1949         118
2     Mar  1949         132
3     Apr  1949         129
4     May  1949         121
5     Jun  1949         135
6     Jul  1949         148
7     Aug  1949         148
8     Sep  1949         136
9     Oct  1949         119
10    Nov  1949         104
11    Dec  1949         118
12    Jan  1950         115
13    Feb  1950         126
14    Mar  1950         141
15    Apr  1950         135
16    May  1950         125
17    Jun  1950         149
18    Jul  1950         170
19    Aug  1950         170
20    Sep  1950         158
21    Oct  1950         133
22    Nov  1950         114
23    Dec  1950         140
24    Jan  1951         145
25    Feb  1951         150
26    Mar  1951         178
27    Apr  1951         163
28    May  1951         172
29    Jun  1951         178
30    Jul  1951         199
31    Aug  1951         199
32    Sep  1951         184
33    Oct  1951         162
34    Nov  1951         146
35    Dec  1951         166
36    Jan  1952         171
37    Feb  1952         180
38    Mar  1952         193
39    Apr  1952         181
40    May  1952         183
41    Jun  1952         218
42    Jul  1952         230
43    Aug  1952         242
44    Sep  1952         209
45    Oct  1952         191
46    Nov  1952         172
47    Dec  1952         194
48    Jan  1953         196
49    Feb  1953         196
50    Mar  1953         236
51    Apr  1953         235
52    May  1953         229
53    Jun  1953         243
54    Jul  1953         264
55    Aug  1953         272
56    Sep  1953         237
57    Oct  1953         211
58    Nov  1953         180
59    Dec  1953         201
60    Jan  1954         204
61    Feb  1954         188
62    Mar  1954         235
63    Apr  1954         227
64    May  1954         234
65    Jun  1954         264
66    Jul  1954         302
67    Aug  1954         293
68    Sep  1954         259
69    Oct  1954         229
70    Nov  1954         203
71    Dec  1954         229
72    Jan  1955         242
73    Feb  1955         233
74    Mar  1955         267
75    Apr  1955         269
76    May  1955         270
77    Jun  1955         315
78    Jul  1955         364
79    Aug  1955         347
80    Sep  1955         312
81    Oct  1955         274
82    Nov  1955         237
83    Dec  1955         278
84    Jan  1956         284
85    Feb  1956         277
86    Mar  1956         317
87    Apr  1956         313
88    May  1956         318
89    Jun  1956         374
90    Jul  1956         413
91    Aug  1956         405
92    Sep  1956         355
93    Oct  1956         306
94    Nov  1956         271
95    Dec  1956         306
96    Jan  1957         315
97    Feb  1957         301
98    Mar  1957         356
99    Apr  1957         348
100   May  1957         355
101   Jun  1957         422
102   Jul  1957         465
103   Aug  1957         467
104   Sep  1957         404
105   Oct  1957         347
106   Nov  1957         305
107   Dec  1957         336
108   Jan  1958         340
109   Feb  1958         318
110   Mar  1958         362
111   Apr  1958         348
112   May  1958         363
113   Jun  1958         435
114   Jul  1958         491
115   Aug  1958         505
116   Sep  1958         404
117   Oct  1958         359
118   Nov  1958         310
119   Dec  1958         337
120   Jan  1959         360
121   Feb  1959         342
122   Mar  1959         406
123   Apr  1959         396
124   May  1959         420
125   Jun  1959         472
126   Jul  1959         548
127   Aug  1959         559
128   Sep  1959         463
129   Oct  1959         407
130   Nov  1959         362
131   Dec  1959         405
132   Jan  1960         417
133   Feb  1960         391
134   Mar  1960         419
135   Apr  1960         461
136   May  1960         472
137   Jun  1960         535
138   Jul  1960         622
139   Aug  1960         606
140   Sep  1960         508
141   Oct  1960         461
142   Nov  1960         390
143   Dec  1960         432

In [158]:
# Change column order
flights = flights.reindex(columns=["Month", "Year", "Passengers"])
flights

    Month  Year  Passengers
0     Jan  1949         112
1     Feb  1949         118
2     Mar  1949         132
3     Apr  1949         129
4     May  1949         121
5     Jun  1949         135
6     Jul  1949         148
7     Aug  1949         148
8     Sep  1949         136
9     Oct  1949         119
10    Nov  1949         104
11    Dec  1949         118
12    Jan  1950         115
13    Feb  1950         126
14    Mar  1950         141
15    Apr  1950         135
16    May  1950         125
17    Jun  1950         149
18    Jul  1950         170
19    Aug  1950         170
20    Sep  1950         158
21    Oct  1950         133
22    Nov  1950         114
23    Dec  1950         140
24    Jan  1951         145
25    Feb  1951         150
26    Mar  1951         178
27    Apr  1951         163
28    May  1951         172
29    Jun  1951         178
30    Jul  1951         199
31    Aug  1951         199
32    Sep  1951         184
33    Oct  1951         162
34    Nov  1951         146
35    Dec  1951         166
36    Jan  1952         171
37    Feb  1952         180
38    Mar  1952         193
39    Apr  1952         181
40    May  1952         183
41    Jun  1952         218
42    Jul  1952         230
43    Aug  1952         242
44    Sep  1952         209
45    Oct  1952         191
46    Nov  1952         172
47    Dec  1952         194
48    Jan  1953         196
49    Feb  1953         196
50    Mar  1953         236
51    Apr  1953         235
52    May  1953         229
53    Jun  1953         243
54    Jul  1953         264
55    Aug  1953         272
56    Sep  1953         237
57    Oct  1953         211
58    Nov  1953         180
59    Dec  1953         201
60    Jan  1954         204
61    Feb  1954         188
62    Mar  1954         235
63    Apr  1954         227
64    May  1954         234
65    Jun  1954         264
66    Jul  1954         302
67    Aug  1954         293
68    Sep  1954         259
69    Oct  1954         229
70    Nov  1954         203
71    Dec  1954         229
72    Jan  1955         242
73    Feb  1955         233
74    Mar  1955         267
75    Apr  1955         269
76    May  1955         270
77    Jun  1955         315
78    Jul  1955         364
79    Aug  1955         347
80    Sep  1955         312
81    Oct  1955         274
82    Nov  1955         237
83    Dec  1955         278
84    Jan  1956         284
85    Feb  1956         277
86    Mar  1956         317
87    Apr  1956         313
88    May  1956         318
89    Jun  1956         374
90    Jul  1956         413
91    Aug  1956         405
92    Sep  1956         355
93    Oct  1956         306
94    Nov  1956         271
95    Dec  1956         306
96    Jan  1957         315
97    Feb  1957         301
98    Mar  1957         356
99    Apr  1957         348
100   May  1957         355
101   Jun  1957         422
102   Jul  1957         465
103   Aug  1957         467
104   Sep  1957         404
105   Oct  1957         347
106   Nov  1957         305
107   Dec  1957         336
108   Jan  1958         340
109   Feb  1958         318
110   Mar  1958         362
111   Apr  1958         348
112   May  1958         363
113   Jun  1958         435
114   Jul  1958         491
115   Aug  1958         505
116   Sep  1958         404
117   Oct  1958         359
118   Nov  1958         310
119   Dec  1958         337
120   Jan  1959         360
121   Feb  1959         342
122   Mar  1959         406
123   Apr  1959         396
124   May  1959         420
125   Jun  1959         472
126   Jul  1959         548
127   Aug  1959         559
128   Sep  1959         463
129   Oct  1959         407
130   Nov  1959         362
131   Dec  1959         405
132   Jan  1960         417
133   Feb  1960         391
134   Mar  1960         419
135   Apr  1960         461
136   May  1960         472
137   Jun  1960         535
138   Jul  1960         622
139   Aug  1960         606
140   Sep  1960         508
141   Oct  1960         461
142   Nov  1960         390
143   Dec  1960         432

In [164]:
# filter rows based on a list of values.

flights["Month"].isin(["Jan","Feb","Mar","Oct","Nov"])

0       True
1       True
2       True
3      False
4      False
5      False
6      False
7      False
8      False
9       True
10      True
11     False
12      True
13      True
14      True
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22      True
23     False
24      True
25      True
26      True
27     False
28     False
29     False
30     False
31     False
32     False
33      True
34      True
35     False
36      True
37      True
38      True
39     False
40     False
41     False
42     False
43     False
44     False
45      True
46      True
47     False
48      True
49      True
50      True
51     False
52     False
53     False
54     False
55     False
56     False
57      True
58      True
59     False
60      True
61      True
62      True
63     False
64     False
65     False
66     False
67     False
68     False
69      True
70      True
71     False
72      True
73      True
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81      True
82      True
83     False
84      True
85      True
86      True
87     False
88     False
89     False
90     False
91     False
92     False
93      True
94      True
95     False
96      True
97      True
98      True
99     False
100    False
101    False
102    False
103    False
104    False
105     True
106     True
107    False
108     True
109     True
110     True
111    False
112    False
113    False
114    False
115    False
116    False
117     True
118     True
119    False
120     True
121     True
122     True
123    False
124    False
125    False
126    False
127    False
128    False
129     True
130     True
131    False
132     True
133     True
134     True
135    False
136    False
137    False
138    False
139    False
140    False
141     True
142     True
143    False
Name: Month, dtype: bool

In [172]:
# Use between() for year range
flights[flights["Year"].between(1949,1960,inclusive="neither")]

    Month  Year  Passengers
12    Jan  1950         115
13    Feb  1950         126
14    Mar  1950         141
15    Apr  1950         135
16    May  1950         125
17    Jun  1950         149
18    Jul  1950         170
19    Aug  1950         170
20    Sep  1950         158
21    Oct  1950         133
22    Nov  1950         114
23    Dec  1950         140
24    Jan  1951         145
25    Feb  1951         150
26    Mar  1951         178
27    Apr  1951         163
28    May  1951         172
29    Jun  1951         178
30    Jul  1951         199
31    Aug  1951         199
32    Sep  1951         184
33    Oct  1951         162
34    Nov  1951         146
35    Dec  1951         166
36    Jan  1952         171
37    Feb  1952         180
38    Mar  1952         193
39    Apr  1952         181
40    May  1952         183
41    Jun  1952         218
42    Jul  1952         230
43    Aug  1952         242
44    Sep  1952         209
45    Oct  1952         191
46    Nov  1952         172
47    Dec  1952         194
48    Jan  1953         196
49    Feb  1953         196
50    Mar  1953         236
51    Apr  1953         235
52    May  1953         229
53    Jun  1953         243
54    Jul  1953         264
55    Aug  1953         272
56    Sep  1953         237
57    Oct  1953         211
58    Nov  1953         180
59    Dec  1953         201
60    Jan  1954         204
61    Feb  1954         188
62    Mar  1954         235
63    Apr  1954         227
64    May  1954         234
65    Jun  1954         264
66    Jul  1954         302
67    Aug  1954         293
68    Sep  1954         259
69    Oct  1954         229
70    Nov  1954         203
71    Dec  1954         229
72    Jan  1955         242
73    Feb  1955         233
74    Mar  1955         267
75    Apr  1955         269
76    May  1955         270
77    Jun  1955         315
78    Jul  1955         364
79    Aug  1955         347
80    Sep  1955         312
81    Oct  1955         274
82    Nov  1955         237
83    Dec  1955         278
84    Jan  1956         284
85    Feb  1956         277
86    Mar  1956         317
87    Apr  1956         313
88    May  1956         318
89    Jun  1956         374
90    Jul  1956         413
91    Aug  1956         405
92    Sep  1956         355
93    Oct  1956         306
94    Nov  1956         271
95    Dec  1956         306
96    Jan  1957         315
97    Feb  1957         301
98    Mar  1957         356
99    Apr  1957         348
100   May  1957         355
101   Jun  1957         422
102   Jul  1957         465
103   Aug  1957         467
104   Sep  1957         404
105   Oct  1957         347
106   Nov  1957         305
107   Dec  1957         336
108   Jan  1958         340
109   Feb  1958         318
110   Mar  1958         362
111   Apr  1958         348
112   May  1958         363
113   Jun  1958         435
114   Jul  1958         491
115   Aug  1958         505
116   Sep  1958         404
117   Oct  1958         359
118   Nov  1958         310
119   Dec  1958         337
120   Jan  1959         360
121   Feb  1959         342
122   Mar  1959         406
123   Apr  1959         396
124   May  1959         420
125   Jun  1959         472
126   Jul  1959         548
127   Aug  1959         559
128   Sep  1959         463
129   Oct  1959         407
130   Nov  1959         362
131   Dec  1959         405

In [176]:
# Which year had highest passengers?

flights.groupby("Year")["Passengers"].sum().sort_values(ascending=False).head(1)

Year
1960    5714
Name: Passengers, dtype: int64

In [179]:
# Which year had lowest passengers?

flights.groupby("Year")["Passengers"].sum().sort_values().head(1)

Year
1949    1520
Name: Passengers, dtype: int64

In [181]:
# Which month has lowest average passengers?

flights.groupby("Year")["Passengers"].mean().sort_values().head(1)

Year
1949    126.666667
Name: Passengers, dtype: float64

In [183]:
# Find growth from 1949 to 1960
flights.groupby(flights["Year"].between(1949,1960))["Passengers"].sum().sort_values(ascending=False).head(1)

Year
True    40363
Name: Passengers, dtype: int64