In [ ]:
# Relational Database 
# Structured Database
# Easy to Read manipulate,change,modify and explain as well
# eg.attendance sheet, marksheet
# c,c++
module = ? 
# CSV - COMMA SEPRATED VALUE
# TSV - TAB SEPRATED VALUE
SPACE , TAB DIFFERENCE ?

TAB PRINTS ASCII CHARACTERS THAT ARE INVISIBLE OR NON PRINTABLE

common name for those who seprates each value from one another known as DELIMITER or SEPRATOR

which other DELIMITER are there

space .(period) and special symbols - @,#,$.%,&

In [ ]:
# what is library - A function that is created standalone and can be used by many people accorss globe without writing it explicitly.

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
products=pd.read_csv(r"C:\Users\HP\Downloads\products-100.csv")
products

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [3]:
pd.set_option('display.max_rows',None)
products

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
5,6,Radio,Character prove growth contain serious customer.,"Benjamin, Nelson and Hancock",Skincare,426,USD,549,1150028980156,CornflowerBlue,30x40 cm,pre_order,60
6,7,Ultra Projector Oven Thermostat Prime Advanced,Pattern possible look necessary indicate work ...,"Mccoy, Waters and Rose",Laptops & Computers,68,USD,870,5029747624534,Purple,S,discontinued,86
7,8,Webcam Stove Grill,Deep area join carry age.,Morrow and Sons,Automotive,159,USD,584,9883725074294,MediumOrchid,8x10 in,pre_order,50
8,9,Eco Radio,Know father for act let.,"Edwards, Odonnell and Conley",Skincare,454,USD,499,1773215338624,DimGray,Medium,pre_order,88
9,10,Ultra Powerbank Brush Charger Max,Meeting add economic task outside.,"Brennan, Archer and Rosales",Fitness Equipment,845,USD,564,4877111475333,Silver,Extra Large,discontinued,88
10,11,Wireless Dock,Whole bill sound whether will.,Russo-West,Health & Wellness,257,USD,168,9680811891595,Wheat,Extra Large,pre_order,30
11,12,Fast Camera Router Fan Smart,Various above trouble itself crime form.,Vazquez and Sons,Cleaning Supplies,221,USD,672,8567222480604,MidnightBlue,Medium,pre_order,32
12,13,Heater Radio,Ten do evidence billion perhaps read bank enter.,Delgado-Blackwell,Cycling,689,USD,156,5686660235911,Orange,L,pre_order,57
13,14,Smart Trimmer Webcam Heater,Example available better.,Contreras PLC,Automotive,279,USD,818,1941032767914,Gainsboro,XXL,pre_order,66
14,15,Webcam Dock Heater,State yet soon traditional your deal.,"Juarez, Powell and Travis",Cleaning Supplies,101,USD,159,1438856474369,Sienna,30x40 cm,pre_order,88
15,16,Automatic Watch Lite Sense,As east entire positive source their.,"Reid, Chase and Ballard",Team Sports,316,USD,329,3500722785805,Tan,5x7 in,limited_stock,44
16,17,Eco Iron Monitor Air,Color single indeed yard event popular food boy.,Barker-Murphy,Automotive,982,USD,47,7887280730963,OliveDrab,XL,out_of_stock,79
17,18,Digital Tablet Router Printer Lite,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD,732,4170125892616,LemonChiffon,10x10 cm,backorder,87
18,19,Eco Freezer Powerbank Watch,Of price visit interesting enter three set.,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,USD,618,6340907128242,Cyan,S,limited_stock,21
19,20,Cooler Fan,Fall billion city share.,Bray LLC,Smartphones,529,USD,844,267078141619,Bisque,XS,backorder,22
20,21,Portable Camera Plus Air Ultra,Reality hair explain up bad.,Wang-Valenzuela,Women's Clothing,197,USD,163,963840013930,Magenta,L,in_stock,96
21,22,Wireless Powerbank 360 Advanced Ultra,Deal head decade age outside military culture.,Carney Ltd,Bedding & Bath,677,USD,418,3918763032312,Beige,M,out_of_stock,90
22,23,Rechargeable Lamp Speakerphone Headphones,Effort own safe main walk quickly.,"Gallegos, Osborne and Carpenter",Skincare,664,USD,577,1824359393441,DarkBlue,L,pre_order,26
23,24,Mini Scooter Microphone,Maybe around expect own whether pay.,"Douglas, Thornton and Soto",Grooming Tools,784,USD,510,9839666739792,DimGray,L,backorder,55
24,25,Rechargeable Webcam Stove Grill,Movement you Mr decide history effect.,Horn-Pope,Health & Wellness,900,USD,623,6501687247749,PaleGreen,5x7 in,out_of_stock,47
25,26,Mini Iron Drone Wireless Pro,From Congress low.,Khan-Parrish,Cycling,909,USD,797,9496081864722,CadetBlue,XXL,limited_stock,93
26,27,Portable Freezer Phone Automatic Smart,Live fish audience piece his ago true.,Burton PLC,Automotive,350,USD,756,3486711401836,Snow,XL,pre_order,61
27,28,Wireless Webcam Stove Grill,Pull at improve health also animal forward per...,Henry Group,Clothing & Apparel,858,USD,912,7097613907430,LightSalmon,50x70 cm,limited_stock,43
28,29,Clock Brush,Other another must explain send somebody consi...,Larson-Spence,Furniture,985,USD,180,8301096575048,SaddleBrown,Extra Large,in_stock,40
29,30,Keyboard Toaster Monitor,My head prove exist change.,Bonilla-Spears,Kids' Clothing,576,USD,988,6639325474032,DarkSlateGray,L,pre_order,40
30,31,Silent Printer Fan Shaver,Region week yet weight.,Love LLC,Sports & Outdoors,102,USD,669,5564792899662,MediumSpringGreen,L,limited_stock,14
31,32,Wireless Scooter Clean Mini,Green main imagine way suffer wall.,Terry-Oliver,Fragrances,283,USD,343,9921752342730,MintCream,S,pre_order,84
32,33,Advanced Microphone Cooler Eco,Most other newspaper beyond real.,"Morales, Weaver and Fernandez",Smartphones,904,USD,532,7107438924403,LightCyan,Extra Large,limited_stock,86
33,34,Automatic Brush Fast Eco,Record response relationship.,Newman Ltd,Kids' Clothing,407,USD,285,2327483415120,SeaGreen,8x10 in,out_of_stock,65
34,35,Premium Bicycle Microphone,Congress how list third rise.,"Novak, Archer and Walton",Shoes & Footwear,480,USD,364,6209821998907,AliceBlue,Extra Large,discontinued,78
35,36,Smart Phone Scooter Clean,Reality kid create thought window.,Marshall-Dougherty,Women's Clothing,635,USD,727,7883295446066,MediumVioletRed,10x10 cm,backorder,74
36,37,Bicycle,Garden mother before ten different increase.,Hays-Cunningham,Smartphones,234,USD,394,7670612815694,White,10x10 cm,backorder,48
37,38,Ultra Dock Trimmer Automatic Edge,Do customer stage act send.,Barnes-Glass,Kids' Clothing,640,USD,780,2837107354495,LightBlue,5x7 in,discontinued,96
38,39,Wireless Tablet Router Printer Wireless Premiu...,North meeting short summer situation positive ...,Meyers-Hess,Sports & Outdoors,781,USD,947,8247903213713,BlanchedAlmond,XL,out_of_stock,69
39,40,Clean Printer Advanced Premium Sense,Bag away always often join seat direction.,Williamson PLC,Haircare,913,USD,820,5234087663802,Moccasin,Small,discontinued,77
40,41,Silent Dock Fast,Speak not hospital bit part.,"May, Hendrix and Robbins",Fishing & Hunting,100,USD,802,938364240247,CadetBlue,M,limited_stock,12
41,42,Ultra Speakerphone Oven Go Smart X,Value bill yeah tell phone.,"Zimmerman, Barr and Davis",Office Supplies,999,USD,853,450118214736,MediumOrchid,12x18 in,pre_order,23
42,43,Rechargeable Projector Pro,Bank everything ago girl.,"Levine, Martin and Mccann",Home Decor,935,USD,55,655296358115,SlateBlue,XL,limited_stock,52
43,44,Eco Vacuum,Bit name seat sea.,Werner PLC,Health & Wellness,259,USD,668,8611986118980,LightCoral,5x7 in,in_stock,45
44,45,Smart Grill Tablet Fridge Go Smart Smart,By result ago born become.,"Huff, Cameron and Stephenson",Fitness Equipment,488,USD,966,9005775281402,Cornsilk,10x10 cm,out_of_stock,62
45,46,Digital Stove Silent Pro,Suffer range between step mention peace prepare.,"Suarez, Riddle and Sanders",Health & Wellness,161,USD,349,5367012957872,OrangeRed,Extra Large,limited_stock,9
46,47,Portable Powerbank X Air,Present court note medical bed red movie.,Hanson-Schultz,Camping & Hiking,599,USD,263,6854117854742,Moccasin,Large,discontinued,17
47,48,Clock,Onto story what job require.,"Malone, Jacobson and Hudson",Team Sports,731,USD,664,1382809012286,FloralWhite,S,limited_stock,55
48,49,Radio Treadmill,Through choose record prove happen.,Barron-Little,Office Supplies,511,USD,395,5461960384619,Violet,XL,discontinued,14
49,50,Ultra Cooler Treadmill Touch Pro Ultra,Certainly simple light safe child PM candidate.,Bonilla-Oconnell,Fragrances,214,USD,574,3625664059934,NavajoWhite,XXL,pre_order,33
50,51,Mini Fridge Camera,Little determine at huge month.,Decker and Sons,Fitness Equipment,777,USD,832,4894233116968,PaleGoldenRod,Extra Large,in_stock,16
51,52,Rechargeable Tablet Plus Portable Mini,Expect question how sound.,Mooney-Gonzales,Fragrances,820,USD,535,8183922928019,Cyan,100x200 mm,in_stock,19
52,53,Tablet,Many deal community public beyond safe anyone.,"Blake, Weiss and Montgomery",Beauty & Personal Care,408,USD,922,8183313115592,Chocolate,Medium,backorder,34
53,54,Wireless Light Toaster Lite Touch Eco,Oil guy table industry hand which.,Singleton PLC,Bedding & Bath,791,USD,827,3057639268476,Fuchsia,50x70 cm,in_stock,64
54,55,Scooter,Small approach possible choose according.,Rivas Group,Cameras & Accessories,370,USD,601,1974896712011,DarkOrchid,L,backorder,46
55,56,Advanced Camera Heater Webcam X Ultra Prime,Audience bit past central film each.,Cervantes Ltd,Office Supplies,224,USD,372,983367163970,Peru,50x70 cm,discontinued,56
56,57,Ultra Keyboard Compact Eco,Bit responsibility cover him mean call civil.,Pace-Hodges,Books & Stationery,514,USD,491,8481605893389,LightGray,8x10 in,backorder,19
57,58,Portable Scale Speaker Powerbank Clean,Throughout special new you view season within.,Morris LLC,Women's Clothing,689,USD,332,5175038823985,PowderBlue,Small,backorder,94
58,59,Oven Speaker Fan,Hot behavior traditional.,Schwartz Ltd,Men's Clothing,489,USD,423,2567562782853,GoldenRod,Small,pre_order,99
59,60,Automatic Speaker Router Lamp Prime,Word score education thousand high treatment.,"Sexton, Dickerson and Blair",Grooming Tools,621,USD,667,6744198567221,FireBrick,5x7 in,in_stock,61
60,61,Smart Webcam Projector Lock,Subject agree you off.,Stokes Inc,Men's Clothing,440,USD,973,4811928042234,SteelBlue,Medium,in_stock,3
61,62,Fast Fan,Avoid very final food scene possible.,Ali-Oliver,Cleaning Supplies,982,USD,804,3388615003133,DarkOrchid,100x200 mm,backorder,70
62,63,Automatic Cooler Edge,Career for much exist.,"Odonnell, Boyle and Oconnor",Beauty & Personal Care,124,USD,513,6261793125392,LimeGreen,50x70 cm,pre_order,83
63,64,Advanced Freezer Advanced Advanced,Chance material himself soldier.,Gill LLC,Office Supplies,489,USD,561,6474143371206,Tomato,S,pre_order,48
64,65,Silent Trimmer Shaver Fast,Task point seat better.,Munoz Group,Smartphones,130,USD,876,4089415274929,DarkSlateGray,5x7 in,in_stock,76
65,66,Treadmill,Vote only run modern.,"Frost, Christensen and Burnett",Women's Clothing,731,USD,744,4598541150958,Cyan,5x7 in,out_of_stock,70
66,67,Mini Charger Lock Oven Sense Sense,Major tell him share allow.,"Burton, Gross and Giles",Haircare,750,USD,623,9282813513019,Olive,12x18 in,in_stock,81
67,68,Thermostat Trimmer,Drug interview hotel decide pattern.,"Hester, Love and Lynch","Accessories (Bags, Hats, Belts)",206,USD,677,8282848236311,MidnightBlue,8x10 in,discontinued,6
68,69,Clean Iron Premium Air Wireless,Around tough popular present sign herself patt...,"Shepherd, Greene and House",Beauty & Personal Care,293,USD,700,7935749142557,GhostWhite,XXL,out_of_stock,5
69,70,Compact Mouse Mouse Router Mini,Occur miss son Democrat happy.,Barry PLC,Smartwatches,5,USD,247,252926529077,PapayaWhip,10x10 cm,limited_stock,79
70,71,Premium Lock Mini Advanced,Three character traditional maybe.,"Elliott, Mcfarland and Duran",Automotive,12,USD,439,3997003361528,Plum,XS,pre_order,40
71,72,Silent Webcam Webcam Treadmill Sense Portable ...,Leg my mother father.,George-Day,Makeup,148,USD,650,6908065460286,Aqua,M,backorder,29
72,73,Compact Thermostat Oven,Focus that consumer amount half.,Hull Inc,Home & Kitchen,685,USD,747,7695934105636,SaddleBrown,30x40 cm,in_stock,36
73,74,Wireless Watch Tablet Printer Automatic Eco Sense,Might poor animal must protect blue forward.,Fleming Inc,Smartwatches,59,USD,169,1089969929675,Sienna,Large,out_of_stock,31
74,75,Automatic Blender,Smile human machine section bank.,Mahoney-Bryan,Home Decor,630,USD,438,310774792552,LightGoldenRodYellow,8x10 in,backorder,4
75,76,Rechargeable Webcam Dock Heater,Organization address section collection church...,Kennedy-Gordon,Cycling,800,USD,151,1340784358003,Brown,XXL,in_stock,66
76,77,Clean Toaster Oven Air Touch,Heavy threat beautiful material assume piece.,Olsen-Sawyer,Kids' Clothing,365,USD,71,7806787405877,LimeGreen,Medium,pre_order,40
77,78,Brush,Control daughter effect investment piece train...,"Lowe, Mosley and Rivera",Bedding & Bath,273,USD,623,168419438521,RoyalBlue,S,in_stock,42
78,79,Portable Kettle,Apply out industry must tell.,Sampson-Leon,Home & Kitchen,50,USD,413,445370808496,MediumAquaMarine,L,pre_order,25
79,80,Rechargeable Brush Compact,Early century every amount than past.,Castro-Mccarty,Automotive,748,USD,326,6855062072649,Sienna,S,out_of_stock,81
80,81,Fast Heater Cooker Compact Silent,Strategy fund mind rather change.,"Decker, Montes and Logan",Makeup,367,USD,19,3868467036959,Orchid,8x10 in,in_stock,15
81,82,Mini Drone X Portable,Shoulder cost especially.,Whitney Group,Books & Stationery,352,USD,123,9437200314292,BlueViolet,Medium,backorder,12
82,83,Heater Keyboard,Remember here kind enjoy source room reflect be.,Brooks and Sons,Office Supplies,103,USD,208,5328785590239,Chocolate,Extra Large,backorder,72
83,84,Wireless Fan Thermostat Max Automatic Max,Design price for especially section college ov...,Kaiser-Banks,Books & Stationery,423,USD,759,1396411470228,MidnightBlue,5x7 in,in_stock,81
84,85,Fast Keyboard,Success other institution fear.,Lewis Ltd,Camping & Hiking,998,USD,10,3163238295239,Cyan,50x70 cm,limited_stock,64
85,86,Ultra Mixer Toaster Toaster Smart,Much guess have pattern southern true hair miss.,Galloway and Sons,Women's Clothing,342,USD,221,4862330962177,Tomato,S,pre_order,88
86,87,Silent Speakerphone Scanner Monitor,Quality yet significant lawyer face field yet ...,Cowan Inc,Fragrances,593,USD,580,1710131812265,Navy,XXL,discontinued,20
87,88,Silent Scanner Monitor Treadmill,Do interesting suggest agreement range admit r...,"Nichols, Howe and Miller",Health & Wellness,30,USD,728,1287056757693,Wheat,10x10 cm,pre_order,60
88,89,Fast Vacuum Cooler,Explain six firm recent rock skin.,Blair-Russell,Sports & Outdoors,307,USD,320,4874329354658,LightSalmon,L,limited_stock,5
89,90,Digital Trimmer,Ago floor nice member wait.,Christian-Tanner,Laptops & Computers,541,USD,488,4147810179628,SteelBlue,M,pre_order,31
90,91,Automatic Trimmer Sense,Much table ground information news senior.,Harrington-Valentine,Kitchen Appliances,405,USD,950,524638185,SlateGray,8x10 in,in_stock,85
91,92,Portable Scooter Wireless Digital,Thousand various evidence.,Bauer Inc,Cameras & Accessories,519,USD,495,4564280934296,DeepSkyBlue,Large,in_stock,36
92,93,Fridge Cooker,Try better loss pretty special.,Jackson Group,Furniture,393,USD,499,1861389468671,Black,Small,in_stock,80
93,94,Scanner,Draw material quickly most.,"Wang, Ayala and Bowen",Cleaning Supplies,472,USD,63,7794860625802,ForestGreen,12x18 in,backorder,8
94,95,Ultra Radio Radio,Shoulder red boy away if.,Maldonado-Ritter,Haircare,382,USD,639,3611080124547,Aquamarine,12x18 in,pre_order,48
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [5]:
print("hello \n world")

hello
 world

In [6]:
print("hello \t world")

hello 	 world

In [4]:
# import pandas
# p=pandas.read_excel(r"C:\Users\HP\Downloads\Project-Management-Sample-Data.xlsx")
# p

In [ ]:
pd.set_option('display.max_rows',None)
products

In [ ]:
# columns, rows , table, banned

In [ ]:
# columns becomes features and variables

In [ ]:
# rows becomes - data point,entry,data

In [ ]:
# table become dataframe

In [19]:
# getting data from library
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.00,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.00,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.00,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.00,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.00,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.00,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.00,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.00,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.00,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.00,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.00,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.00,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.00,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.00,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.00,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.00,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
25,1,3,female,38.00,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
30,0,1,male,40.00,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
33,0,2,male,66.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
34,0,1,male,28.00,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
35,0,1,male,42.00,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
37,0,3,male,21.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
38,0,3,female,18.00,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
40,0,3,female,40.00,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.00,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.00,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
46,0,3,male,NaN,1,0,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
48,0,3,male,NaN,2,0,21.6792,C,Third,man,True,NaN,Cherbourg,no,False
49,0,3,female,18.00,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False
50,0,3,male,7.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
51,0,3,male,21.00,0,0,7.8000,S,Third,man,True,NaN,Southampton,no,True
52,1,1,female,49.00,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
53,1,2,female,29.00,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
54,0,1,male,65.00,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
56,1,2,female,21.00,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
57,0,3,male,28.50,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
58,1,2,female,5.00,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
59,0,3,male,11.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
60,0,3,male,22.00,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
61,1,1,female,38.00,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
62,0,1,male,45.00,1,0,83.4750,S,First,man,True,C,Southampton,no,False
63,0,3,male,4.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
64,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
65,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
66,1,2,female,29.00,0,0,10.5000,S,Second,woman,False,F,Southampton,yes,True
67,0,3,male,19.00,0,0,8.1583,S,Third,man,True,NaN,Southampton,no,True
68,1,3,female,17.00,4,2,7.9250,S,Third,woman,False,NaN,Southampton,yes,False
69,0,3,male,26.00,2,0,8.6625,S,Third,man,True,NaN,Southampton,no,False
70,0,2,male,32.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
71,0,3,female,16.00,5,2,46.9000,S,Third,woman,False,NaN,Southampton,no,False
72,0,2,male,21.00,0,0,73.5000,S,Second,man,True,NaN,Southampton,no,True
73,0,3,male,26.00,1,0,14.4542,C,Third,man,True,NaN,Cherbourg,no,False
74,1,3,male,32.00,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
75,0,3,male,25.00,0,0,7.6500,S,Third,man,True,F,Southampton,no,True
76,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
77,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
79,1,3,female,30.00,0,0,12.4750,S,Third,woman,False,NaN,Southampton,yes,True
80,0,3,male,22.00,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
81,1,3,male,29.00,0,0,9.5000,S,Third,man,True,NaN,Southampton,yes,True
82,1,3,female,NaN,0,0,7.7875,Q,Third,woman,False,NaN,Queenstown,yes,True
83,0,1,male,28.00,0,0,47.1000,S,First,man,True,NaN,Southampton,no,True
84,1,2,female,17.00,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
85,1,3,female,33.00,3,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False
86,0,3,male,16.00,1,3,34.3750,S,Third,man,True,NaN,Southampton,no,False
87,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
89,0,3,male,24.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
90,0,3,male,29.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
91,0,3,male,20.00,0,0,7.8542,S,Third,man,True,NaN,Southampton,no,True
92,0,1,male,46.00,1,0,61.1750,S,First,man,True,E,Southampton,no,False
93,0,3,male,26.00,1,2,20.5750,S,Third,man,True,NaN,Southampton,no,False
94,0,3,male,59.00,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
96,0,1,male,71.00,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
97,1,1,male,23.00,0,1,63.3583,C,First,man,True,D,Cherbourg,yes,False
98,1,2,female,34.00,0,1,23.0000,S,Second,woman,False,NaN,Southampton,yes,False
99,0,2,male,34.00,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False
100,0,3,female,28.00,0,0,7.8958,S,Third,woman,False,NaN,Southampton,no,True
101,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
102,0,1,male,21.00,0,1,77.2875,S,First,man,True,D,Southampton,no,False
103,0,3,male,33.00,0,0,8.6542,S,Third,man,True,NaN,Southampton,no,True
104,0,3,male,37.00,2,0,7.9250,S,Third,man,True,NaN,Southampton,no,False
105,0,3,male,28.00,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
106,1,3,female,21.00,0,0,7.6500,S,Third,woman,False,NaN,Southampton,yes,True
107,1,3,male,NaN,0,0,7.7750,S,Third,man,True,NaN,Southampton,yes,True
108,0,3,male,38.00,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
109,1,3,female,NaN,1,0,24.1500,Q,Third,woman,False,NaN,Queenstown,yes,False
110,0,1,male,47.00,0,0,52.0000,S,First,man,True,C,Southampton,no,True
111,0,3,female,14.50,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,no,False
112,0,3,male,22.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
113,0,3,female,20.00,1,0,9.8250,S,Third,woman,False,NaN,Southampton,no,False
114,0,3,female,17.00,0,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,True
115,0,3,male,21.00,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
116,0,3,male,70.50,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
117,0,2,male,29.00,1,0,21.0000,S,Second,man,True,NaN,Southampton,no,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
120,0,2,male,21.00,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False
121,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
122,0,2,male,32.50,1,0,30.0708,C,Second,man,True,NaN,Cherbourg,no,False
123,1,2,female,32.50,0,0,13.0000,S,Second,woman,False,E,Southampton,yes,True
124,0,1,male,54.00,0,1,77.2875,S,First,man,True,D,Southampton,no,False
125,1,3,male,12.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
126,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
127,1,3,male,24.00,0,0,7.1417,S,Third,man,True,NaN,Southampton,yes,True
128,1,3,female,NaN,1,1,22.3583,C,Third,woman,False,F,Cherbourg,yes,False
129,0,3,male,45.00,0,0,6.9750,S,Third,man,True,NaN,Southampton,no,True
130,0,3,male,33.00,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
131,0,3,male,20.00,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
132,0,3,female,47.00,1,0,14.5000,S,Third,woman,False,NaN,Southampton,no,False
133,1,2,female,29.00,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
134,0,2,male,25.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
135,0,2,male,23.00,0,0,15.0458,C,Second,man,True,NaN,Cherbourg,no,True
136,1,1,female,19.00,0,2,26.2833,S,First,woman,False,D,Southampton,yes,False
137,0,1,male,37.00,1,0,53.1000,S,First,man,True,C,Southampton,no,False
138,0,3,male,16.00,0,0,9.2167,S,Third,man,True,NaN,Southampton,no,True
139,0,1,male,24.00,0,0,79.2000,C,First,man,True,B,Cherbourg,no,True
140,0,3,female,NaN,0,2,15.2458,C,Third,woman,False,NaN,Cherbourg,no,False
141,1,3,female,22.00,0,0,7.7500,S,Third,woman,False,NaN,Southampton,yes,True
142,1,3,female,24.00,1,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False
143,0,3,male,19.00,0,0,6.7500,Q,Third,man,True,NaN,Queenstown,no,True
144,0,2,male,18.00,0,0,11.5000,S,Second,man,True,NaN,Southampton,no,True
145,0,2,male,19.00,1,1,36.7500,S,Second,man,True,NaN,Southampton,no,False
146,1,3,male,27.00,0,0,7.7958,S,Third,man,True,NaN,Southampton,yes,True
147,0,3,female,9.00,2,2,34.3750,S,Third,child,False,NaN,Southampton,no,False
148,0,2,male,36.50,0,2,26.0000,S,Second,man,True,F,Southampton,no,False
149,0,2,male,42.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
150,0,2,male,51.00,0,0,12.5250,S,Second,man,True,NaN,Southampton,no,True
151,1,1,female,22.00,1,0,66.6000,S,First,woman,False,C,Southampton,yes,False
152,0,3,male,55.50,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
153,0,3,male,40.50,0,2,14.5000,S,Third,man,True,NaN,Southampton,no,False
154,0,3,male,NaN,0,0,7.3125,S,Third,man,True,NaN,Southampton,no,True
155,0,1,male,51.00,0,1,61.3792,C,First,man,True,NaN,Cherbourg,no,False
156,1,3,female,16.00,0,0,7.7333,Q,Third,woman,False,NaN,Queenstown,yes,True
157,0,3,male,30.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
158,0,3,male,NaN,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
159,0,3,male,NaN,8,2,69.5500,S,Third,man,True,NaN,Southampton,no,False
160,0,3,male,44.00,0,1,16.1000,S,Third,man,True,NaN,Southampton,no,False
161,1,2,female,40.00,0,0,15.7500,S,Second,woman,False,NaN,Southampton,yes,True
162,0,3,male,26.00,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
163,0,3,male,17.00,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
165,1,3,male,9.00,0,2,20.5250,S,Third,child,False,NaN,Southampton,yes,False
166,1,1,female,NaN,0,1,55.0000,S,First,woman,False,E,Southampton,yes,False
167,0,3,female,45.00,1,4,27.9000,S,Third,woman,False,NaN,Southampton,no,False
168,0,1,male,NaN,0,0,25.9250,S,First,man,True,NaN,Southampton,no,True
169,0,3,male,28.00,0,0,56.4958,S,Third,man,True,NaN,Southampton,no,True
170,0,1,male,61.00,0,0,33.5000,S,First,man,True,B,Southampton,no,True
171,0,3,male,4.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
173,0,3,male,21.00,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
174,0,1,male,56.00,0,0,30.6958,C,First,man,True,A,Cherbourg,no,True
175,0,3,male,18.00,1,1,7.8542,S,Third,man,True,NaN,Southampton,no,False
176,0,3,male,NaN,3,1,25.4667,S,Third,man,True,NaN,Southampton,no,False
177,0,1,female,50.00,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
178,0,2,male,30.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
179,0,3,male,36.00,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
180,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
181,0,2,male,NaN,0,0,15.0500,C,Second,man,True,NaN,Cherbourg,no,True
182,0,3,male,9.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,no,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
185,0,1,male,NaN,0,0,50.0000,S,First,man,True,A,Southampton,no,True
186,1,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False
187,1,1,male,45.00,0,0,26.5500,S,First,man,True,NaN,Southampton,yes,True
188,0,3,male,40.00,1,1,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
189,0,3,male,36.00,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
190,1,2,female,32.00,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
191,0,2,male,19.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
192,1,3,female,19.00,1,0,7.8542,S,Third,woman,False,NaN,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
194,1,1,female,44.00,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes,True
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
196,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
197,0,3,male,42.00,0,1,8.4042,S,Third,man,True,NaN,Southampton,no,False
198,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
199,0,2,female,24.00,0,0,13.0000,S,Second,woman,False,NaN,Southampton,no,True
200,0,3,male,28.00,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
201,0,3,male,NaN,8,2,69.5500,S,Third,man,True,NaN,Southampton,no,False
202,0,3,male,34.00,0,0,6.4958,S,Third,man,True,NaN,Southampton,no,True
203,0,3,male,45.50,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
204,1,3,male,18.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,yes,True
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
206,0,3,male,32.00,1,0,15.8500,S,Third,man,True,NaN,Southampton,no,False
207,1,3,male,26.00,0,0,18.7875,C,Third,man,True,NaN,Cherbourg,yes,True
208,1,3,female,16.00,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
209,1,1,male,40.00,0,0,31.0000,C,First,man,True,A,Cherbourg,yes,True
210,0,3,male,24.00,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
211,1,2,female,35.00,0,0,21.0000,S,Second,woman,False,NaN,Southampton,yes,True
212,0,3,male,22.00,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
213,0,2,male,30.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
214,0,3,male,NaN,1,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,False
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
216,1,3,female,27.00,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
217,0,2,male,42.00,1,0,27.0000,S,Second,man,True,NaN,Southampton,no,False
218,1,1,female,32.00,0,0,76.2917,C,First,woman,False,D,Cherbourg,yes,True
219,0,2,male,30.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
220,1,3,male,16.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,yes,True
221,0,2,male,27.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
222,0,3,male,51.00,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
223,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
224,1,1,male,38.00,1,0,90.0000,S,First,man,True,C,Southampton,yes,False
225,0,3,male,22.00,0,0,9.3500,S,Third,man,True,NaN,Southampton,no,True
226,1,2,male,19.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True
227,0,3,male,20.50,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
228,0,2,male,18.00,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
229,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
230,1,1,female,35.00,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
231,0,3,male,29.00,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
232,0,2,male,59.00,0,0,13.5000,S,Second,man,True,NaN,Southampton,no,True
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
234,0,2,male,24.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
235,0,3,female,NaN,0,0,7.5500,S,Third,woman,False,NaN,Southampton,no,True
236,0,2,male,44.00,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False
237,1,2,female,8.00,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False
238,0,2,male,19.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
239,0,2,male,33.00,0,0,12.2750,S,Second,man,True,NaN,Southampton,no,True
240,0,3,female,NaN,1,0,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
241,1,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False
242,0,2,male,29.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
243,0,3,male,22.00,0,0,7.1250,S,Third,man,True,NaN,Southampton,no,True
244,0,3,male,30.00,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
245,0,1,male,44.00,2,0,90.0000,Q,First,man,True,C,Queenstown,no,False
246,0,3,female,25.00,0,0,7.7750,S,Third,woman,False,NaN,Southampton,no,True
247,1,2,female,24.00,0,2,14.5000,S,Second,woman,False,NaN,Southampton,yes,False
248,1,1,male,37.00,1,1,52.5542,S,First,man,True,D,Southampton,yes,False
249,0,2,male,54.00,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False
250,0,3,male,NaN,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
251,0,3,female,29.00,1,1,10.4625,S,Third,woman,False,G,Southampton,no,False
252,0,1,male,62.00,0,0,26.5500,S,First,man,True,C,Southampton,no,True
253,0,3,male,30.00,1,0,16.1000,S,Third,man,True,NaN,Southampton,no,False
254,0,3,female,41.00,0,2,20.2125,S,Third,woman,False,NaN,Southampton,no,False
255,1,3,female,29.00,0,2,15.2458,C,Third,woman,False,NaN,Cherbourg,yes,False
256,1,1,female,NaN,0,0,79.2000,C,First,woman,False,NaN,Cherbourg,yes,True
257,1,1,female,30.00,0,0,86.5000,S,First,woman,False,B,Southampton,yes,True
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
259,1,2,female,50.00,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
260,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
262,0,1,male,52.00,1,1,79.6500,S,First,man,True,E,Southampton,no,False
263,0,1,male,40.00,0,0,0.0000,S,First,man,True,B,Southampton,no,True
264,0,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
265,0,2,male,36.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
266,0,3,male,16.00,4,1,39.6875,S,Third,man,True,NaN,Southampton,no,False
267,1,3,male,25.00,1,0,7.7750,S,Third,man,True,NaN,Southampton,yes,False
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
270,0,1,male,NaN,0,0,31.0000,S,First,man,True,NaN,Southampton,no,True
271,1,3,male,25.00,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
272,1,2,female,41.00,0,1,19.5000,S,Second,woman,False,NaN,Southampton,yes,False

In [ ]:
dataframe

In [ ]:
# pandas data types or subtypes

In [ ]:
# 1. Series - Series in pandas works / looks similar to list in python . 
# It is used to store a one dimensional data and multiple rows

In [16]:
import pandas as pd
list1=[1,2,3,4,5,6]
s1=pd.Series(list1)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [17]:
s1.sum()

np.int64(21)

In [5]:
list2=["apple","mango","watermelon","cherry","banana"]
s2=pd.Series(list2)
s2

0    apple
dtype: object

In [8]:
list2=["apple","mango","watermelon","cherry","banana"]
s2=pd.Series(list2[4])
s2

0    banana
dtype: object

In [ ]:
# series and df aslo has indexes like list has but they are known as lables.
# labels are customisable.

In [9]:
list3=["lion","tiger","bat","eagle"]
s3=pd.Series(list3)
s3

0     lion
1    tiger
2      bat
3    eagle
dtype: object

In [11]:
list3=["lion","tiger","bat","eagle"]
s3=pd.Series(list3,index=["A","B","C","D"])
s3

A     lion
B    tiger
C      bat
D    eagle
dtype: object

In [12]:
s3[1:3]

B    tiger
C      bat
dtype: object

In [18]:
# 2.Data Frames - It is used to store 2 dimensionla data / 2D Data 
# It has rows and columns 
# It also has lablels like series
# It is combinations of multiple series
# every columns inside a dataframe is series in nature

In [ ]:
# creating a dataframe from dictionary 
# Each key becomes column and values becomes rows

In [23]:
details={
    "Name":["Vaishnavi","Sakshi","Tushar","Vivek","Yogesh"],
    "Age":[21,23,34,45,6],
    "City":["Soalpur","Pune","Nashik","Mumbai","Nagpur"]
}
d1=pd.DataFrame(details)
d1

        Name  Age     City
0  Vaishnavi   21  Soalpur
1     Sakshi   23     Pune
2     Tushar   34   Nashik
3      Vivek   45   Mumbai
4     Yogesh    6   Nagpur

In [ ]:
# dataframe from list

In [30]:
info=[
    ["Apple","Iphone","17 Pro","256GB"],
    ["Samsung","Galaxy 5","26 Ultra","521GB"]
    ]
type(info)

list

In [34]:
smartphones=pd.DataFrame(info,columns=["company","model","series name","storage"])
smartphones

   company     model series name storage
0    Apple    Iphone      17 Pro   256GB
1  Samsung  Galaxy 5    26 Ultra   521GB

In [35]:
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [36]:
titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [37]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [38]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
# describe works on numerical columns

In [39]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
# std - how much each data point away from the mean.

In [ ]:
400+45=445+445=900
446->14.45

In [ ]:
total rows=891
891-1=890
890/2=445
446-14.45

In [40]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [42]:
# titanic.dtypes datatypes of columns

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [43]:
titanic["survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [44]:
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [45]:
type(titanic)

pandas.core.frame.DataFrame

In [48]:
titanic[["survived",'age']]

     survived   age
0           0  22.0
1           1  38.0
2           1  26.0
3           1  35.0
4           0  35.0
..        ...   ...
886         0  27.0
887         1  19.0
888         0   NaN
889         1  26.0
890         0  32.0

[891 rows x 2 columns]

In [ ]:
# Create a Series with values [10, 20, 30, 40]

In [1]:
import pandas as pd
s1=[10, 20, 30, 40]
s=pd.Series(s1)
s

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# Create a Series with custom index like a, b, c, d

In [4]:
s2=pd.Series(s1,index=["a","b","c","d"])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
# Create a DataFrame with:

Name: Vaishnavi, Rahul
Marks: 90, 75

In [6]:
d1={
    "Name":["vaishnavi","rahuk"],
    "age":[23,45]
}
d=pd.DataFrame(d1)
d

        Name  age
0  vaishnavi   23
1      rahuk   45

In [ ]:
# Print only the Marks column

In [7]:
d1["age"]

[23, 45]

In [12]:
d.shape

(2, 2)

In [4]:
d1.max("age")

NameError: name 'd1' is not defined

In [5]:
titanic

NameError: name 'titanic' is not defined

In [6]:
titanic.describe()

NameError: name 'titanic' is not defined

In [8]:
import pandas as pd
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [9]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [13]:
titanic.sample() # random sampling
titanic.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
731,0,3,male,11.0,0,0,18.7875,C,Third,child,False,NaN,Cherbourg,no,True
798,0,3,male,30.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
495,0,3,male,NaN,0,0,14.4583,C,Third,man,True,NaN,Cherbourg,no,True
729,0,3,female,25.0,1,0,7.9250,S,Third,woman,False,NaN,Southampton,no,False
164,0,3,male,1.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False

In [ ]:
# index based slicing of dataframe using iloc - index location

In [17]:
titanic.iloc[5]
titanic.iloc[0:5] # start index and stop index

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [19]:
titanic.iloc[100:111]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
100,0,3,female,28.0,0,0,7.8958,S,Third,woman,False,NaN,Southampton,no,True
101,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
102,0,1,male,21.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False
103,0,3,male,33.0,0,0,8.6542,S,Third,man,True,NaN,Southampton,no,True
104,0,3,male,37.0,2,0,7.9250,S,Third,man,True,NaN,Southampton,no,False
105,0,3,male,28.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
106,1,3,female,21.0,0,0,7.6500,S,Third,woman,False,NaN,Southampton,yes,True
107,1,3,male,NaN,0,0,7.7750,S,Third,man,True,NaN,Southampton,yes,True
108,0,3,male,38.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
109,1,3,female,NaN,1,0,24.1500,Q,Third,woman,False,NaN,Queenstown,yes,False
110,0,1,male,47.0,0,0,52.0000,S,First,man,True,C,Southampton,no,True

In [22]:
titanic.iloc[0:5,0:4]  #rows:columns

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [25]:
titanic.iloc[3:7]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

In [26]:
titanic.iloc[450:461,3:7]

      age  sibsp  parch     fare
450  36.0      1      2  27.7500
451   NaN      1      0  19.9667
452  30.0      0      0  27.7500
453  49.0      1      0  89.1042
454   NaN      0      0   8.0500
455  29.0      0      0   7.8958
456  65.0      0      0  26.5500
457   NaN      1      0  51.8625
458  50.0      0      0  10.5000
459   NaN      0      0   7.7500
460  48.0      0      0  26.5500

In [31]:
titanic.iloc[20:31,3]
# titanic.iloc[20:31,"age"] # it gives me error

20    35.0
21    34.0
22    15.0
23    28.0
24     8.0
25    38.0
26     NaN
27    19.0
28     NaN
29     NaN
30    40.0
Name: age, dtype: float64

In [ ]:
# loc = label based indexing

In [32]:
titanic.loc[0:5] # stop label/index is inclusive

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [33]:
titanic.loc[110:120]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
110,0,1,male,47.0,0,0,52.0000,S,First,man,True,C,Southampton,no,True
111,0,3,female,14.5,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,no,False
112,0,3,male,22.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
113,0,3,female,20.0,1,0,9.8250,S,Third,woman,False,NaN,Southampton,no,False
114,0,3,female,17.0,0,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,True
115,0,3,male,21.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
117,0,2,male,29.0,1,0,21.0000,S,Second,man,True,NaN,Southampton,no,False
118,0,1,male,24.0,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
120,0,2,male,21.0,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False

In [34]:
titanic.loc[110:120,"age"] # it returns a series so there is no label for the index.

110    47.0
111    14.5
112    22.0
113    20.0
114    17.0
115    21.0
116    70.5
117    29.0
118    24.0
119     2.0
120    21.0
Name: age, dtype: float64

In [35]:
titanic.loc[550:560,["age","fare","survived"]]

      age      fare  survived
550  17.0  110.8833         1
551  27.0   26.0000         0
552   NaN    7.8292         0
553  22.0    7.2250         1
554  22.0    7.7750         1
555  62.0   26.5500         0
556  48.0   39.6000         1
557   NaN  227.5250         0
558  39.0   79.6500         1
559  36.0   17.4000         1
560   NaN    7.7500         0

In [ ]:
# filtering using loc

In [40]:
titanic.loc[titanic["age"]>70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [43]:
titanic.iloc[titanic[:,3]>70]  #iloc does not support boolean filtering

InvalidIndexError: (slice(None, None, None), 3)

In [ ]:
# differences 

# iloc takes only integer value for slicing whereas loc takes both lables  and cols names 
# in iloc stop index is excluded , unlike loc where stop label is inclusive 
# loc supports boolean filtering / conditional filtering , iloc does not

In [47]:
titanic.loc[titanic['who']=="child"]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [52]:
titanic.loc[titanic['pclass']==3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [50]:
titanic.loc[titanic["embark_town"]=="Cherbourg"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
# MULTIPLE FILTERING - 
child survivours

In [58]:
tdf=titanic.loc[
    (titanic["who"]=="child") & (titanic["survived"]==1),
    ["class","sex","age"]
    ]
tdf

      class     sex    age
9    Second  female  14.00
10    Third  female   4.00
22    Third  female  15.00
39    Third  female  14.00
43   Second  female   3.00
58   Second  female   5.00
78   Second    male   0.83
125   Third    male  12.00
165   Third    male   9.00
172   Third  female   1.00
183  Second    male   1.00
184   Third  female   4.00
193  Second    male   3.00
233   Third  female   5.00
237  Second  female   8.00
261   Third    male   3.00
305   First    male   0.92
340  Second    male   2.00
348   Third    male   3.00
381   Third  female   1.00
407  Second    male   3.00
435   First  female  14.00
445   First    male   4.00
446  Second  female  13.00
448   Third  female   5.00
469   Third  female   0.75
479   Third  female   2.00
489   Third    male   9.00
530  Second  female   2.00
535  Second  female   7.00
549  Second    male   8.00
618  Second  female   4.00
644   Third  female   0.75
689   First  female  15.00
691   Third  female   4.00
720  Second  female   6.00
750  Second  female   4.00
751   Third    male   6.00
755  Second    male   0.67
777   Third  female   5.00
780   Third  female  13.00
788   Third    male   1.00
802   First    male  11.00
803   Third    male   0.42
827  Second    male   1.00
830   Third  female  15.00
831  Second    male   0.83
869   Third    male   4.00
875   Third  female  15.00

In [ ]:
# normal filtering

In [ ]:
# get details of people who survived and are adult male

In [61]:
titanic.loc[
    (titanic["survived"]==1) & (titanic["adult_male"]==True)
]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,1,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
# basic filtering

In [62]:
titanic[titanic["age"]>70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [63]:
titanic[
    (titanic["survived"]==1) & (titanic["adult_male"]==True)
]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,1,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [66]:
# passengers who are female 
titanic[titanic["sex"]=="female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [67]:
titanic[titanic["survived"]==1].count()

survived       342
pclass         342
sex            342
age            290
sibsp          342
parch          342
fare           342
embarked       340
class          342
who            342
adult_male     342
deck           136
embark_town    340
alive          342
alone          342
dtype: int64

In [70]:
titanic[
    (titanic["survived"]==1) & (titanic["fare"]>500)
]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True

In [74]:
titanic[
    (titanic["age"].between(20,40))
]

titanic[
    (titanic["age"].between(0,1))
]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False

In [ ]:
# get people from south ampton and cherbourg

In [78]:
titanic[titanic["embarked"].isin(['c','s'])]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [81]:
titanic[titanic["embarked"].isin(['C','S'])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [82]:
titanic[titanic["who"].isin(['woman','child'])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [83]:
titanic["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [84]:
titanic["survived"].unique()

array([0, 1])

In [85]:
titanic["fare"].value_counts()

fare
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
13.8583     1
50.4958     1
5.0000      1
9.8458      1
10.5167     1
Name: count, Length: 248, dtype: int64

In [86]:
titanic["class"].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [87]:
titanic["class"].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [88]:
titanic["deck"].value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [89]:
titanic["deck"].unique()

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [90]:
titanic["who"].unique()

array(['man', 'woman', 'child'], dtype=object)

In [91]:
titanic["embark_town"].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [92]:
titanic["age"].mean()

np.float64(29.69911764705882)

In [93]:
titanic["age"].min()

0.42

In [94]:
titanic["age"].max()

80.0

In [95]:
titanic["age"].median()

28.0

In [96]:
titanic["age"].std()

14.526497332334044

In [99]:
titanic["age"].idxmax() # use idxmax to get label to max value

630

In [100]:
titanic.loc[630]

survived                 1
pclass                   1
sex                   male
age                   80.0
sibsp                    0
parch                    0
fare                  30.0
embarked                 S
class                First
who                    man
adult_male            True
deck                     A
embark_town    Southampton
alive                  yes
alone                 True
Name: 630, dtype: object

In [101]:
titanic["age"].idxmin()

803

In [102]:
titanic.loc[803]

survived               1
pclass                 3
sex                 male
age                 0.42
sibsp                  0
parch                  1
fare              8.5167
embarked               C
class              Third
who                child
adult_male         False
deck                 NaN
embark_town    Cherbourg
alive                yes
alone              False
Name: 803, dtype: object

In [ ]:
# how to load csv data ?

In [3]:
import pandas as pd
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# dirty dataset

In [ ]:
# checking null/blank using isnull

In [7]:
titanic.isnull().sum()  # false = not a empty data # True - empty data - it gives boolean result .

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# missing values can be harmful for analysis of our data befor moving forward , remove or replace missing values so that we get clean dataset 
# generally we removed columns thta has more missing values replacing those values will create near synthetic data.

In [ ]:
# to remove missing values we need percentage 
# titanic.isnull.mean()*100

In [9]:
titanic.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [ ]:
# the column which has more than 50 percent of missing values should be removed rest other columns must be filled with mean/median/mode 
# according to the variablke nature.

In [10]:
titanic.isnull().median()*100

survived         0.0
pclass           0.0
sex              0.0
age              0.0
sibsp            0.0
parch            0.0
fare             0.0
embarked         0.0
class            0.0
who              0.0
adult_male       0.0
deck           100.0
embark_town      0.0
alive            0.0
alone            0.0
dtype: float64

In [11]:
titanic.isnull().std()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            39.921043
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        4.735131
class           0.000000
who             0.000000
adult_male      0.000000
deck           41.967044
embark_town     4.735131
alive           0.000000
alone           0.000000
dtype: float64

In [12]:
titanic.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [ ]:
# 1st method
titanic=titanic.drop(columns='deck')

In [30]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [37]:
titanic["survived"].mean()*100

np.float64(38.38383838383838)

In [38]:
titanic["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
# dropping multiple columns

In [40]:
titanic.drop(columns=["age","sex","pclass"])

,survived,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [11]:
import pandas as pd
f1=pd.read_csv(r"C:\Users\HP\Downloads\products-100.csv",encoding="latin1")
f1

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [4]:
f1

NameError: name 'f1' is not defined

In [1]:
import pandas as pd
data={
    "Name":["vaishnavi","om","rahul","rajesh","ramesh","ram","manoj","shyam"],
    "Age":[23,4,5,3,2,5,5,7],
    "salary":[845,4865,947,975,497,9567,958,5876],
    "performance_score":[405,5,4,4,4,5,44,67]
}
df=pd.DataFrame(data)
print(df)

        Name  Age  salary  performance_score
0  vaishnavi   23     845                405
1         om    4    4865                  5
2      rahul    5     947                  4
3     rajesh    3     975                  4
4     ramesh    2     497                  4
5        ram    5    9567                  5
6      manoj    5     958                 44
7      shyam    7    5876                 67

In [2]:
df.describe()

             Age       salary  performance_score
count   8.000000     8.000000            8.00000
mean    6.750000  3066.250000           67.25000
std     6.734771  3343.099706          138.54731
min     2.000000   497.000000            4.00000
25%     3.750000   921.500000            4.00000
50%     5.000000   966.500000            5.00000
75%     5.500000  5117.750000           49.75000
max    23.000000  9567.000000          405.00000

In [13]:
import pandas as pd
import seaborn as sns
import numpy as np
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
# pclass 
titanic["pclass"].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [14]:
titanic.groupby("pclass")["survived"].size()

pclass
1    216
2    184
3    491
Name: survived, dtype: int64

In [17]:
titanic.groupby("survived")["pclass"].value_counts()

survived  pclass
0         3         372
          2          97
          1          80
1         1         136
          3         119
          2          87
Name: count, dtype: int64

In [18]:
titanic.groupby("pclass")["survived"].value_counts()

pclass  survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [ ]:
# calculate survival rate by gender

In [20]:
titanic.groupby("sex")["survived"].mean()*100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [ ]:
# survival rate of pclass

In [21]:
titanic.groupby("pclass")["survived"].mean()*100

pclass
1    62.962963
2    47.282609
3    24.236253
Name: survived, dtype: float64

In [22]:
titanic.groupby("embark_town")["survived"].mean()*100

embark_town
Cherbourg      55.357143
Queenstown     38.961039
Southampton    33.695652
Name: survived, dtype: float64

In [23]:
titanic.groupby("who")["survived"].mean()*100

who
child    59.036145
man      16.387337
woman    75.645756
Name: survived, dtype: float64

In [24]:
titanic.groupby("alone")["survived"].mean()*100

alone
False    50.564972
True     30.353818
Name: survived, dtype: float64

In [27]:
titanic.groupby(["pclass","sex"])["survived"].mean()*100

pclass  sex
1       female    96.808511
        male      36.885246
2       female    92.105263
        male      15.740741
3       female    50.000000
        male      13.544669
Name: survived, dtype: float64

In [30]:
titanic.groupby(["pclass","sex"])["survived"].value_counts()

pclass  sex     survived
1       female  1            91
                0             3
        male    0            77
                1            45
2       female  1            70
                0             6
        male    0            91
                1            17
3       female  0            72
                1            72
        male    0           300
                1            47
Name: count, dtype: int64

In [ ]:
# lets find minimum age from each pclass

In [34]:
titanic.groupby(["pclass"])["age"].min()

pclass
1    0.92
2    0.67
3    0.42
Name: age, dtype: float64

In [35]:
titanic.groupby(["pclass"])["age"].agg(["min","max","mean"])

         min   max       mean
pclass
1       0.92  80.0  38.233441
2       0.67  70.0  29.877630
3       0.42  74.0  25.140620

In [ ]:
# from each class for male and female find min,max,mean for survived and dead

In [40]:
titanic.groupby(["pclass","sex","survived"])["age"].agg(["min","max","mean"])

                          min   max       mean
pclass sex    survived
1      female 0          2.00  50.0  25.666667
              1         14.00  63.0  34.939024
       male   0         18.00  71.0  44.581967
              1          0.92  80.0  36.248000
2      female 0         24.00  57.0  36.000000
              1          2.00  55.0  28.080882
       male   0         16.00  70.0  33.369048
              1          0.67  62.0  16.022000
3      female 0          2.00  48.0  23.818182
              1          0.75  63.0  19.329787
       male   0          1.00  74.0  27.255814
              1          0.42  45.0  22.274211

In [45]:
titanic.groupby("sex")["age"].count()  # we cannot use the count because it ignores the missing value

sex
female    261
male      453
Name: age, dtype: int64

In [46]:
titanic.groupby("sex")["age"].size()

sex
female    314
male      577
Name: age, dtype: int64

In [ ]:
# show passangesr with correct entry of their age

In [43]:
titanic["age"].isnull().sum()

np.int64(177)

In [66]:
import warnings
warnings.filterwarnings("ignore")
tips=sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# show min max bill for day and time

In [67]:
tips.groupby(["day","time"])["total_bill"].agg(["min","max"])

               min    max
day  time
Thur Lunch    7.51  43.11
     Dinner  18.78  18.78
Fri  Lunch    8.58  16.27
     Dinner   5.75  40.17
Sat  Lunch     NaN    NaN
     Dinner   3.07  50.81
Sun  Lunch     NaN    NaN
     Dinner   7.25  48.17

In [ ]:
# show min max avg bill for size and day

In [68]:
tips.groupby(["size","day"])["total_bill"].agg(["min","max","mean"])

             min    max       mean
size day
1    Thur  10.07  10.07  10.070000
     Fri    8.58   8.58   8.580000
     Sat    3.07   7.25   5.160000
     Sun     NaN    NaN        NaN
2    Thur   7.51  32.68  15.156875
     Fri    5.75  28.97  16.321875
     Sat    7.74  32.83  16.837170
     Sun    7.25  40.55  17.560000
3    Thur  16.47  22.82  19.160000
     Fri   15.98  15.98  15.980000
     Sat   15.69  50.81  25.509444
     Sun   10.33  45.35  22.184000
4    Thur  20.53  43.11  29.950000
     Fri   40.17  40.17  40.170000
     Sat   17.81  48.33  29.876154
     Sun   16.49  35.26  26.688333
5    Thur  41.19  41.19  41.190000
     Fri     NaN    NaN        NaN
     Sat   28.15  28.15  28.150000
     Sun   20.69  30.46  27.000000
6    Thur  27.05  34.30  30.383333
     Fri     NaN    NaN        NaN
     Sat     NaN    NaN        NaN
     Sun   48.17  48.17  48.170000

In [ ]:
# show min max avg bill for smoker and non smoker

In [69]:
tips.groupby(["smoker","sex"])["total_bill"].agg(["min","max","mean"])

                min    max       mean
smoker sex
Yes    Male    7.25  50.81  22.284500
       Female  3.07  44.30  17.977879
No     Male    7.51  48.33  19.791237
       Female  7.25  35.83  18.105185

In [ ]:
# show min max tip for day and time

In [70]:
tips.groupby(["day","time"])["tip"].agg(["min","max","mean"])

              min    max      mean
day  time
Thur Lunch   1.25   6.70  2.767705
     Dinner  3.00   3.00  3.000000
Fri  Lunch   1.58   3.48  2.382857
     Dinner  1.00   4.73  2.940000
Sat  Lunch    NaN    NaN       NaN
     Dinner  1.00  10.00  2.993103
Sun  Lunch    NaN    NaN       NaN
     Dinner  1.01   6.50  3.255132

In [ ]:
# for size and day

In [71]:
tips.groupby(["size","day"])["tip"].agg(["min","max"])

            min    max
size day
1    Thur  1.83   1.83
     Fri   1.92   1.92
     Sat   1.00   1.00
     Sun    NaN    NaN
2    Thur  1.25   5.85
     Fri   1.00   4.30
     Sat   1.00   5.00
     Sun   1.01   5.65
3    Thur  1.36   4.00
     Fri   3.00   3.00
     Sat   2.00  10.00
     Sun   1.66   4.00
4    Thur  2.92   5.17
     Fri   4.73   4.73
     Sat   2.00   9.00
     Sun   2.00   6.50
5    Thur  5.00   5.00
     Fri    NaN    NaN
     Sat   3.00   3.00
     Sun   2.00   5.14
6    Thur  4.20   6.70
     Fri    NaN    NaN
     Sat    NaN    NaN
     Sun   5.00   5.00

In [ ]:
# tip for smoker and non smoker

In [72]:
tips.groupby(["sex","smoker"])["tip"].agg(["min","max","mean"])

                min   max      mean
sex    smoker
Male   Yes     1.00  10.0  3.051167
       No      1.25   9.0  3.113402
Female Yes     1.00   6.5  2.931515
       No      1.00   5.2  2.773519

In [ ]:
# renaming columns

In [73]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [76]:
tips.rename(columns={"total_bill":"Total_Bill"},inplace=True)
tips

     Total_Bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# multiple columns at once

In [77]:
tips.rename(columns={
    "tip":"Tip",
    "sex":"Gender"
},inplace=True)
tips

     Total_Bill   Tip  Gender smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [1]:
import pandas as pd
data={
    "Name":["vaishnavi","om","rahul","rajesh","ramesh","ram","manoj","shyam"],
    "Age":[23,4,5,3,2,5,5,7],
    "salary":[845,4865,947,975,497,9567,958,5876],
    "performance_score":[405,5,4,4,4,5,44,67]
}
df=pd.DataFrame(data)
print(df)

        Name  Age  salary  performance_score
0  vaishnavi   23     845                405
1         om    4    4865                  5
2      rahul    5     947                  4
3     rajesh    3     975                  4
4     ramesh    2     497                  4
5        ram    5    9567                  5
6      manoj    5     958                 44
7      shyam    7    5876                 67

In [6]:
import pandas as pd
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
titanic.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [ ]:
# any column that  has missing value more than 30 % , simply drop the column
# and if missing values are below 30% replace with mean or median whichever suits the best.
# if column is categorical replace with mode.

In [ ]:
# replace null values with fillna

In [15]:
titanic["age"].fillna(titanic["age"].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5632\2475312687.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["age"].fillna(titanic["age"].mean(),inplace=True)

In [16]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [19]:
titanic["age"].median()

29.69911764705882

In [20]:
titanic["age"].fillna(titanic["age"].median(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5632\411226054.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["age"].fillna(titanic["age"].median(),inplace=True)

In [18]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [25]:
titanic["age"].fillna(0,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5632\2359026684.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["age"].fillna(0,inplace=True)

In [24]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [26]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# we never remove rows with missing values
# result in loss of huge data

In [46]:
df1=pd.DataFrame([20,30,np.nan,40,50,60,np.nan],columns=["weight"],index=["a","b","c","d","e","f","g"])
df1

   weight
a    20.0
b    30.0
c     NaN
d    40.0
e    50.0
f    60.0
g     NaN

In [ ]:
# forward fill

In [52]:
df1["weight"]=df1["weight"].ffill()
df1

   weight
a    20.0
b    30.0
c    30.0
d    40.0
e    50.0
f    60.0
g    60.0

In [53]:
print(pd.__version__)

2.3.3

In [47]:
df1["weight"].fillna(method="ffill")

C:\Users\HP\AppData\Local\Temp\ipykernel_5632\3288572576.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1["weight"].fillna(method="ffill")

a    20.0
b    30.0
c    30.0
d    40.0
e    50.0
f    60.0
g    60.0
Name: weight, dtype: float64

In [ ]:
# backward fill

In [48]:
df1["weight"].fillna(method="bfill")

C:\Users\HP\AppData\Local\Temp\ipykernel_5632\3627616854.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1["weight"].fillna(method="bfill")

a    20.0
b    30.0
c    40.0
d    40.0
e    50.0
f    60.0
g     NaN
Name: weight, dtype: float64

In [55]:
titanic.rename(columns={"sex":"gender"})

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [56]:
titanic.rename(columns={"pclass":"Passenger_Class","sibsp":"sibling_spouse"})

,survived,Passenger_Class,sex,age,sibling_spouse,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [57]:
titanic["fare_tax"]=titanic["fare"]*0.1
titanic

# feature engineering

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_tax
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [62]:
titanic["family_size"]=titanic["pclass"]+titanic["sibsp"]+titanic["parch"]+1
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_tax,family_size
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500,5
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833,3
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250,4
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000,3
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000,3
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000,2
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500,7
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000,2
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500,4

In [64]:
titanic["embarked_new"]=titanic["embark_town"].str[0]
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_tax,family_size,embarked_new
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500,5,S
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833,3,C
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250,4,S
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000,3,S
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500,4,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000,3,S
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000,2,S
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500,7,S
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000,2,C
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500,4,Q

In [65]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      891 non-null    int64
 1   pclass        891 non-null    int64
 2   sex           891 non-null    object
 3   age           891 non-null    float64
 4   sibsp         891 non-null    int64
 5   parch         891 non-null    int64
 6   fare          891 non-null    float64
 7   embarked      889 non-null    object
 8   class         891 non-null    category
 9   who           891 non-null    object
 10  adult_male    891 non-null    bool
 11  deck          203 non-null    category
 12  embark_town   889 non-null    object
 13  alive         891 non-null    object
 14  alone         891 non-null    bool
 15  fare_tax      891 non-null    float64
 16  family_size   891 non-null    int64
 17  embarked_new  889 non-null    object
dtypes: bool(2), category(2), float64(3), int64(5), object(6)
memory usage: 101.5+ KB

In [ ]:
# chnaging data type of columns or features

In [68]:
titanic["embarked_new"]=titanic["embarked_new"].astype("string")
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      891 non-null    int64
 1   pclass        891 non-null    int64
 2   sex           891 non-null    object
 3   age           891 non-null    float64
 4   sibsp         891 non-null    int64
 5   parch         891 non-null    int64
 6   fare          891 non-null    float64
 7   embarked      889 non-null    object
 8   class         891 non-null    category
 9   who           891 non-null    object
 10  adult_male    891 non-null    bool
 11  deck          203 non-null    category
 12  embark_town   889 non-null    object
 13  alive         891 non-null    object
 14  alone         891 non-null    bool
 15  fare_tax      891 non-null    float64
 16  family_size   891 non-null    int64
 17  embarked_new  891 non-null    string
dtypes: bool(2), category(2), float64(3), int64(5), object(5), string(1)
memory usage: 101.5+ KB

In [67]:
str="vaishanvi"
type(str)

str

In [76]:
titanic["who"]=titanic["who"].astype("string")
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      891 non-null    int64
 1   pclass        891 non-null    int64
 2   sex           891 non-null    object
 3   age           891 non-null    float64
 4   sibsp         891 non-null    int64
 5   parch         891 non-null    int64
 6   fare          891 non-null    float64
 7   embarked      889 non-null    object
 8   class         891 non-null    category
 9   who           891 non-null    string
 10  adult_male    891 non-null    bool
 11  deck          203 non-null    category
 12  embark_town   889 non-null    object
 13  alive         891 non-null    object
 14  alone         891 non-null    bool
 15  fare_tax      891 non-null    float64
 16  family_size   891 non-null    int64
 17  embarked_new  891 non-null    string
 18  who1          891 non-null    string
dtypes: bool(2), category(2), float64(3), int64(5), object(4), string(3)
memory usage: 108.5+ KB